package go.encoding;

/**
    Package binary implements simple translation between numbers and byte
    sequences and encoding and decoding of varints.
    
    Numbers are translated by reading and writing fixed-size values.
    A fixed-size value is either a fixed-size arithmetic
    type (bool, int8, uint8, int16, float32, complex64, ...)
    or an array or struct containing only fixed-size values.
    
    The varint functions encode and decode single integer values using
    a variable-length encoding; smaller values require fewer bytes.
    For a specification, see
    https://developers.google.com/protocol-buffers/docs/encoding.
    
    This package favors simplicity over efficiency. Clients that require
    high-performance serialization, especially for large data structures,
    should look at more advanced solutions such as the [encoding/gob]
    package or [google.golang.org/protobuf] for protocol buffers.
**/
@:go.Type({ name: "binary", instanceName: "binary.binary", imports: ["encoding/binary"] })
extern class Binary {

    /**
        MaxVarintLenN is the maximum length of a varint-encoded N-bit integer.
    **/
    @:native("MaxVarintLen16") static var maxVarintLen16: go.GoInt;
    /**
        MaxVarintLenN is the maximum length of a varint-encoded N-bit integer.
    **/
    @:native("MaxVarintLen32") static var maxVarintLen32: go.GoInt;
    /**
        MaxVarintLenN is the maximum length of a varint-encoded N-bit integer.
    **/
    @:native("MaxVarintLen64") static var maxVarintLen64: go.GoInt;

    /**
        BigEndian is the big-endian implementation of [ByteOrder] and [AppendByteOrder].
    **/
    @:native("BigEndian") static var bigEndian: go.encoding.binary.BigEndian_;
    /**
        LittleEndian is the little-endian implementation of [ByteOrder] and [AppendByteOrder].
    **/
    @:native("LittleEndian") static var littleEndian: go.encoding.binary.LittleEndian_;
    /**
        NativeEndian is the native-endian implementation of [ByteOrder] and [AppendByteOrder].
    **/
    @:native("NativeEndian") static var nativeEndian: go.encoding.binary.NativeEndian_;

    /**
        Append appends the binary representation of data to buf.
        buf may be nil, in which case a new buffer will be allocated.
        See [Write] on which data are acceptable.
        It returns the (possibly extended) buffer containing data or an error.
    **/
    @:native("Append") static function append(buf: go.Slice<go.Byte>, order: go.encoding.binary.ByteOrder, data: Dynamic): (go.Result<go.Slice<go.Byte>>);
    /**
        AppendUvarint appends the varint-encoded form of x,
        as generated by [PutUvarint], to buf and returns the extended buffer.
    **/
    @:native("AppendUvarint") static function appendUvarint(buf: go.Slice<go.Byte>, x: go.UInt64): (go.Slice<go.Byte>);
    /**
        AppendVarint appends the varint-encoded form of x,
        as generated by [PutVarint], to buf and returns the extended buffer.
    **/
    @:native("AppendVarint") static function appendVarint(buf: go.Slice<go.Byte>, x: go.Int64): (go.Slice<go.Byte>);
    /**
        Decode decodes binary data from buf into data according to
        the given byte order.
        It returns an error if buf is too small, otherwise the number of
        bytes consumed from buf.
    **/
    @:native("Decode") static function decode(buf: go.Slice<go.Byte>, order: go.encoding.binary.ByteOrder, data: Dynamic): (go.Result<go.GoInt>);
    /**
        Encode encodes the binary representation of data into buf according to
        the given byte order.
        It returns an error if buf is too small, otherwise the number of
        bytes written into buf.
    **/
    @:native("Encode") static function encode(buf: go.Slice<go.Byte>, order: go.encoding.binary.ByteOrder, data: Dynamic): (go.Result<go.GoInt>);
    /**
        PutUvarint encodes a uint64 into buf and returns the number of bytes written.
        If the buffer is too small, PutUvarint will panic.
    **/
    @:native("PutUvarint") static function putUvarint(buf: go.Slice<go.Byte>, x: go.UInt64): (go.GoInt);
    /**
        PutVarint encodes an int64 into buf and returns the number of bytes written.
        If the buffer is too small, PutVarint will panic.
    **/
    @:native("PutVarint") static function putVarint(buf: go.Slice<go.Byte>, x: go.Int64): (go.GoInt);
    /**
        Read reads structured binary data from r into data.
        Data must be a pointer to a fixed-size value or a slice
        of fixed-size values.
        Bytes read from r are decoded using the specified byte order
        and written to successive fields of the data.
        When decoding boolean values, a zero byte is decoded as false, and
        any other non-zero byte is decoded as true.
        When reading into structs, the field data for fields with
        blank (_) field names is skipped; i.e., blank field names
        may be used for padding.
        When reading into a struct, all non-blank fields must be exported
        or Read may panic.
        
        The error is [io.EOF] only if no bytes were read.
        If an [io.EOF] happens after reading some but not all the bytes,
        Read returns [io.ErrUnexpectedEOF].
    **/
    @:native("Read") static function read(r: go.io.Reader, order: go.encoding.binary.ByteOrder, data: Dynamic): (go.Error);
    /**
        ReadUvarint reads an encoded unsigned integer from r and returns it as a uint64.
        The error is [io.EOF] only if no bytes were read.
        If an [io.EOF] happens after reading some but not all the bytes,
        ReadUvarint returns [io.ErrUnexpectedEOF].
    **/
    @:native("ReadUvarint") static function readUvarint(r: go.io.ByteReader): (go.Result<go.UInt64>);
    /**
        ReadVarint reads an encoded signed integer from r and returns it as an int64.
        The error is [io.EOF] only if no bytes were read.
        If an [io.EOF] happens after reading some but not all the bytes,
        ReadVarint returns [io.ErrUnexpectedEOF].
    **/
    @:native("ReadVarint") static function readVarint(r: go.io.ByteReader): (go.Result<go.Int64>);
    /**
        Size returns how many bytes [Write] would generate to encode the value v, which
        must be a fixed-size value or a slice of fixed-size values, or a pointer to such data.
        If v is neither of these, Size returns -1.
    **/
    @:native("Size") static function size(v: Dynamic): (go.GoInt);
    /**
        Uvarint decodes a uint64 from buf and returns that value and the
        number of bytes read (> 0). If an error occurred, the value is 0
        and the number of bytes n is <= 0 meaning:
          - n == 0: buf too small;
          - n < 0: value larger than 64 bits (overflow) and -n is the number of
            bytes read.
    **/
    @:go.Tuple("p0", "p1") @:native("Uvarint") static function uvarint(buf: go.Slice<go.Byte>): (go.Tuple<{ p0: go.UInt64, p1: go.GoInt }>);
    /**
        Varint decodes an int64 from buf and returns that value and the
        number of bytes read (> 0). If an error occurred, the value is 0
        and the number of bytes n is <= 0 with the following meaning:
          - n == 0: buf too small;
          - n < 0: value larger than 64 bits (overflow)
            and -n is the number of bytes read.
    **/
    @:go.Tuple("p0", "p1") @:native("Varint") static function varint(buf: go.Slice<go.Byte>): (go.Tuple<{ p0: go.Int64, p1: go.GoInt }>);
    /**
        Write writes the binary representation of data into w.
        Data must be a fixed-size value or a slice of fixed-size
        values, or a pointer to such data.
        Boolean values encode as one byte: 1 for true, and 0 for false.
        Bytes written to w are encoded using the specified byte order
        and read from successive fields of the data.
        When writing structs, zero values are written for fields
        with blank (_) field names.
    **/
    @:native("Write") static function write(w: go.io.Writer, order: go.encoding.binary.ByteOrder, data: Dynamic): (go.Error);

}