package go.encoding;

/**
    BinaryUnmarshaler is the interface implemented by an object that can
    unmarshal a binary representation of itself.
    
    UnmarshalBinary must be able to decode the form generated by MarshalBinary.
    UnmarshalBinary must copy the data if it wishes to retain the data
    after returning.
**/
@:go.Type({ name: "BinaryUnmarshaler", instanceName: "encoding.BinaryUnmarshaler", imports: ["encoding"] })
extern typedef BinaryUnmarshaler = {

    @:native("UnmarshalBinary") function unmarshalBinary(data: go.Slice<go.Byte>): (go.Error);

}