package go.encoding;

/**
    TextUnmarshaler is the interface implemented by an object that can
    unmarshal a textual representation of itself.
    
    UnmarshalText must be able to decode the form generated by MarshalText.
    UnmarshalText must copy the text if it wishes to retain the text
    after returning.
**/
@:go.Type({ name: "TextUnmarshaler", instanceName: "encoding.TextUnmarshaler", imports: ["encoding"] })
extern typedef TextUnmarshaler = {

    @:native("UnmarshalText") function unmarshalText(text: go.Slice<go.Byte>): (go.Error);

}