package go.debug;

@:go.Type({ name: "macho", instanceName: "macho.macho", imports: ["debug/macho"] })
extern class Macho {

    @:native("ARM64_RELOC_ADDEND") static var ARM64_RELOC_ADDEND: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_BRANCH26") static var ARM64_RELOC_BRANCH26: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_GOT_LOAD_PAGE21") static var ARM64_RELOC_GOT_LOAD_PAGE21: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_GOT_LOAD_PAGEOFF12") static var ARM64_RELOC_GOT_LOAD_PAGEOFF12: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_PAGE21") static var ARM64_RELOC_PAGE21: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_PAGEOFF12") static var ARM64_RELOC_PAGEOFF12: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_POINTER_TO_GOT") static var ARM64_RELOC_POINTER_TO_GOT: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_SUBTRACTOR") static var ARM64_RELOC_SUBTRACTOR: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_TLVP_LOAD_PAGE21") static var ARM64_RELOC_TLVP_LOAD_PAGE21: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_TLVP_LOAD_PAGEOFF12") static var ARM64_RELOC_TLVP_LOAD_PAGEOFF12: go.debug.macho.RelocTypeARM64;
    @:native("ARM64_RELOC_UNSIGNED") static var ARM64_RELOC_UNSIGNED: go.debug.macho.RelocTypeARM64;
    @:native("ARM_RELOC_BR24") static var ARM_RELOC_BR24: go.debug.macho.RelocTypeARM;
    @:native("ARM_RELOC_HALF") static var ARM_RELOC_HALF: go.debug.macho.RelocTypeARM;
    @:native("ARM_RELOC_HALF_SECTDIFF") static var ARM_RELOC_HALF_SECTDIFF: go.debug.macho.RelocTypeARM;
    @:native("ARM_RELOC_LOCAL_SECTDIFF") static var ARM_RELOC_LOCAL_SECTDIFF: go.debug.macho.RelocTypeARM;
    @:native("ARM_RELOC_PAIR") static var ARM_RELOC_PAIR: go.debug.macho.RelocTypeARM;
    @:native("ARM_RELOC_PB_LA_PTR") static var ARM_RELOC_PB_LA_PTR: go.debug.macho.RelocTypeARM;
    @:native("ARM_RELOC_SECTDIFF") static var ARM_RELOC_SECTDIFF: go.debug.macho.RelocTypeARM;
    @:native("ARM_RELOC_VANILLA") static var ARM_RELOC_VANILLA: go.debug.macho.RelocTypeARM;
    @:native("ARM_THUMB_32BIT_BRANCH") static var ARM_THUMB_32BIT_BRANCH: go.debug.macho.RelocTypeARM;
    @:native("ARM_THUMB_RELOC_BR22") static var ARM_THUMB_RELOC_BR22: go.debug.macho.RelocTypeARM;
    @:native("Cpu386") static var Cpu386: go.debug.macho.Cpu;
    @:native("CpuAmd64") static var CpuAmd64: go.debug.macho.Cpu;
    @:native("CpuArm") static var CpuArm: go.debug.macho.Cpu;
    @:native("CpuArm64") static var CpuArm64: go.debug.macho.Cpu;
    @:native("CpuPpc") static var CpuPpc: go.debug.macho.Cpu;
    @:native("CpuPpc64") static var CpuPpc64: go.debug.macho.Cpu;
    @:native("FlagAllModsBound") static var FlagAllModsBound: go.UInt32;
    @:native("FlagAllowStackExecution") static var FlagAllowStackExecution: go.UInt32;
    @:native("FlagAppExtensionSafe") static var FlagAppExtensionSafe: go.UInt32;
    @:native("FlagBindAtLoad") static var FlagBindAtLoad: go.UInt32;
    @:native("FlagBindsToWeak") static var FlagBindsToWeak: go.UInt32;
    @:native("FlagCanonical") static var FlagCanonical: go.UInt32;
    @:native("FlagDeadStrippableDylib") static var FlagDeadStrippableDylib: go.UInt32;
    @:native("FlagDyldLink") static var FlagDyldLink: go.UInt32;
    @:native("FlagForceFlat") static var FlagForceFlat: go.UInt32;
    @:native("FlagHasTLVDescriptors") static var FlagHasTLVDescriptors: go.UInt32;
    @:native("FlagIncrLink") static var FlagIncrLink: go.UInt32;
    @:native("FlagLazyInit") static var FlagLazyInit: go.UInt32;
    @:native("FlagNoFixPrebinding") static var FlagNoFixPrebinding: go.UInt32;
    @:native("FlagNoHeapExecution") static var FlagNoHeapExecution: go.UInt32;
    @:native("FlagNoMultiDefs") static var FlagNoMultiDefs: go.UInt32;
    @:native("FlagNoReexportedDylibs") static var FlagNoReexportedDylibs: go.UInt32;
    @:native("FlagNoUndefs") static var FlagNoUndefs: go.UInt32;
    @:native("FlagPIE") static var FlagPIE: go.UInt32;
    @:native("FlagPrebindable") static var FlagPrebindable: go.UInt32;
    @:native("FlagPrebound") static var FlagPrebound: go.UInt32;
    @:native("FlagRootSafe") static var FlagRootSafe: go.UInt32;
    @:native("FlagSetuidSafe") static var FlagSetuidSafe: go.UInt32;
    @:native("FlagSplitSegs") static var FlagSplitSegs: go.UInt32;
    @:native("FlagSubsectionsViaSymbols") static var FlagSubsectionsViaSymbols: go.UInt32;
    @:native("FlagTwoLevel") static var FlagTwoLevel: go.UInt32;
    @:native("FlagWeakDefines") static var FlagWeakDefines: go.UInt32;
    @:native("GENERIC_RELOC_LOCAL_SECTDIFF") static var GENERIC_RELOC_LOCAL_SECTDIFF: go.debug.macho.RelocTypeGeneric;
    @:native("GENERIC_RELOC_PAIR") static var GENERIC_RELOC_PAIR: go.debug.macho.RelocTypeGeneric;
    @:native("GENERIC_RELOC_PB_LA_PTR") static var GENERIC_RELOC_PB_LA_PTR: go.debug.macho.RelocTypeGeneric;
    @:native("GENERIC_RELOC_SECTDIFF") static var GENERIC_RELOC_SECTDIFF: go.debug.macho.RelocTypeGeneric;
    @:native("GENERIC_RELOC_TLV") static var GENERIC_RELOC_TLV: go.debug.macho.RelocTypeGeneric;
    @:native("GENERIC_RELOC_VANILLA") static var GENERIC_RELOC_VANILLA: go.debug.macho.RelocTypeGeneric;
    @:native("LoadCmdDylib") static var LoadCmdDylib: go.debug.macho.LoadCmd;
    @:native("LoadCmdDylinker") static var LoadCmdDylinker: go.debug.macho.LoadCmd;
    @:native("LoadCmdDysymtab") static var LoadCmdDysymtab: go.debug.macho.LoadCmd;
    @:native("LoadCmdRpath") static var LoadCmdRpath: go.debug.macho.LoadCmd;
    @:native("LoadCmdSegment") static var LoadCmdSegment: go.debug.macho.LoadCmd;
    @:native("LoadCmdSegment64") static var LoadCmdSegment64: go.debug.macho.LoadCmd;
    @:native("LoadCmdSymtab") static var LoadCmdSymtab: go.debug.macho.LoadCmd;
    @:native("LoadCmdThread") static var LoadCmdThread: go.debug.macho.LoadCmd;
    @:native("LoadCmdUnixThread") static var LoadCmdUnixThread: go.debug.macho.LoadCmd;
    @:native("Magic32") static var Magic32: go.UInt32;
    @:native("Magic64") static var Magic64: go.UInt32;
    @:native("MagicFat") static var MagicFat: go.UInt32;
    @:native("TypeBundle") static var TypeBundle: go.debug.macho.Type;
    @:native("TypeDylib") static var TypeDylib: go.debug.macho.Type;
    @:native("TypeExec") static var TypeExec: go.debug.macho.Type;
    @:native("TypeObj") static var TypeObj: go.debug.macho.Type;
    @:native("X86_64_RELOC_BRANCH") static var X86_64_RELOC_BRANCH: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_GOT") static var X86_64_RELOC_GOT: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_GOT_LOAD") static var X86_64_RELOC_GOT_LOAD: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_SIGNED") static var X86_64_RELOC_SIGNED: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_SIGNED_1") static var X86_64_RELOC_SIGNED_1: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_SIGNED_2") static var X86_64_RELOC_SIGNED_2: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_SIGNED_4") static var X86_64_RELOC_SIGNED_4: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_SUBTRACTOR") static var X86_64_RELOC_SUBTRACTOR: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_TLV") static var X86_64_RELOC_TLV: go.debug.macho.RelocTypeX86_64;
    @:native("X86_64_RELOC_UNSIGNED") static var X86_64_RELOC_UNSIGNED: go.debug.macho.RelocTypeX86_64;

    @:native("ErrNotFat") static var ErrNotFat: go.Pointer<go.debug.macho.FormatError>;

    @:native("NewFatFile") static function newFatFile(r: go.io.ReaderAt): go.Result<go.Pointer<go.debug.macho.FatFile>>;
    @:native("NewFile") static function newFile(r: go.io.ReaderAt): go.Result<go.Pointer<go.debug.macho.File>>;
    @:native("Open") static function open(name: String): go.Result<go.Pointer<go.debug.macho.File>>;
    @:native("OpenFat") static function openFat(name: String): go.Result<go.Pointer<go.debug.macho.FatFile>>;

}