package go;

/**
    Package log implements a simple logging package. It defines a type, [Logger],
    with methods for formatting output. It also has a predefined 'standard'
    Logger accessible through helper functions Print[f|ln], Fatal[f|ln], and
    Panic[f|ln], which are easier to use than creating a Logger manually.
    That logger writes to standard error and prints the date and time
    of each logged message.
    Every log message is output on a separate line: if the message being
    printed does not end in a newline, the logger will add one.
    The Fatal functions call [os.Exit](1) after writing the log message.
    The Panic functions call panic after writing the log message.
**/
@:go.Type({ name: "log", instanceName: "log.log", imports: ["log"] })
extern class Log {

    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("LUTC") static var LUTC: go.GoInt;
    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("Ldate") static var ldate: go.GoInt;
    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("Llongfile") static var llongfile: go.GoInt;
    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("Lmicroseconds") static var lmicroseconds: go.GoInt;
    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("Lmsgprefix") static var lmsgprefix: go.GoInt;
    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("Lshortfile") static var lshortfile: go.GoInt;
    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("LstdFlags") static var lstdFlags: go.GoInt;
    /**
        These flags define which text to prefix to each log entry generated by the [Logger].
        Bits are or'ed together to control what's printed.
        With the exception of the Lmsgprefix flag, there is no
        control over the order they appear (the order listed here)
        or the format they present (as described in the comments).
        The prefix is followed by a colon only when Llongfile or Lshortfile
        is specified.
        For example, flags Ldate | Ltime (or LstdFlags) produce,
        
        	2009/01/23 01:23:23 message
        
        while flags Ldate | Ltime | Lmicroseconds | Llongfile produce,
        
        	2009/01/23 01:23:23.123123 /a/b/c/d.go:23: message
    **/
    @:native("Ltime") static var ltime: go.GoInt;

    /**
        Default returns the standard logger used by the package-level output functions.
    **/
    @:native("Default") static function _default(): (go.Pointer<go.log.Logger>);
    /**
        Fatal is equivalent to [Print] followed by a call to [os.Exit](1).
    **/
    @:native("Fatal") static function fatal(v: haxe.Rest<Dynamic>): Void;
    /**
        Fatalf is equivalent to [Printf] followed by a call to [os.Exit](1).
    **/
    @:native("Fatalf") static function fatalf(format: String, v: haxe.Rest<Dynamic>): Void;
    /**
        Fatalln is equivalent to [Println] followed by a call to [os.Exit](1).
    **/
    @:native("Fatalln") static function fatalln(v: haxe.Rest<Dynamic>): Void;
    /**
        Flags returns the output flags for the standard logger.
        The flag bits are [Ldate], [Ltime], and so on.
    **/
    @:native("Flags") static function flags(): (go.GoInt);
    /**
        New creates a new [Logger]. The out variable sets the
        destination to which log data will be written.
        The prefix appears at the beginning of each generated log line, or
        after the log header if the [Lmsgprefix] flag is provided.
        The flag argument defines the logging properties.
    **/
    @:native("New") static function _new(out: go.io.Writer, prefix: String, flag: go.GoInt): (go.Pointer<go.log.Logger>);
    /**
        Output writes the output for a logging event. The string s contains
        the text to print after the prefix specified by the flags of the
        Logger. A newline is appended if the last character of s is not
        already a newline. Calldepth is the count of the number of
        frames to skip when computing the file name and line number
        if [Llongfile] or [Lshortfile] is set; a value of 1 will print the details
        for the caller of Output.
    **/
    @:native("Output") static function output(calldepth: go.GoInt, s: String): (go.Error);
    /**
        Panic is equivalent to [Print] followed by a call to panic().
    **/
    @:native("Panic") static function panic(v: haxe.Rest<Dynamic>): Void;
    /**
        Panicf is equivalent to [Printf] followed by a call to panic().
    **/
    @:native("Panicf") static function panicf(format: String, v: haxe.Rest<Dynamic>): Void;
    /**
        Panicln is equivalent to [Println] followed by a call to panic().
    **/
    @:native("Panicln") static function panicln(v: haxe.Rest<Dynamic>): Void;
    /**
        Prefix returns the output prefix for the standard logger.
    **/
    @:native("Prefix") static function prefix(): (String);
    /**
        Print calls Output to print to the standard logger.
        Arguments are handled in the manner of [fmt.Print].
    **/
    @:native("Print") static function print(v: haxe.Rest<Dynamic>): Void;
    /**
        Printf calls Output to print to the standard logger.
        Arguments are handled in the manner of [fmt.Printf].
    **/
    @:native("Printf") static function printf(format: String, v: haxe.Rest<Dynamic>): Void;
    /**
        Println calls Output to print to the standard logger.
        Arguments are handled in the manner of [fmt.Println].
    **/
    @:native("Println") static function println(v: haxe.Rest<Dynamic>): Void;
    /**
        SetFlags sets the output flags for the standard logger.
        The flag bits are [Ldate], [Ltime], and so on.
    **/
    @:native("SetFlags") static function setFlags(flag: go.GoInt): Void;
    /**
        SetOutput sets the output destination for the standard logger.
    **/
    @:native("SetOutput") static function setOutput(w: go.io.Writer): Void;
    /**
        SetPrefix sets the output prefix for the standard logger.
    **/
    @:native("SetPrefix") static function setPrefix(prefix: String): Void;
    /**
        Writer returns the output destination for the standard logger.
    **/
    @:native("Writer") static function writer(): (go.io.Writer);

}