package go;

@:go.Type({ name: "os", instanceName: "os.os", imports: ["os"] })
extern class Os {

    @:native("DevNull") static var DevNull: String;
    @:native("ModeAppend") static var ModeAppend: go.io.fs.FileMode;
    @:native("ModeCharDevice") static var ModeCharDevice: go.io.fs.FileMode;
    @:native("ModeDevice") static var ModeDevice: go.io.fs.FileMode;
    @:native("ModeDir") static var ModeDir: go.io.fs.FileMode;
    @:native("ModeExclusive") static var ModeExclusive: go.io.fs.FileMode;
    @:native("ModeIrregular") static var ModeIrregular: go.io.fs.FileMode;
    @:native("ModeNamedPipe") static var ModeNamedPipe: go.io.fs.FileMode;
    @:native("ModePerm") static var ModePerm: go.io.fs.FileMode;
    @:native("ModeSetgid") static var ModeSetgid: go.io.fs.FileMode;
    @:native("ModeSetuid") static var ModeSetuid: go.io.fs.FileMode;
    @:native("ModeSocket") static var ModeSocket: go.io.fs.FileMode;
    @:native("ModeSticky") static var ModeSticky: go.io.fs.FileMode;
    @:native("ModeSymlink") static var ModeSymlink: go.io.fs.FileMode;
    @:native("ModeTemporary") static var ModeTemporary: go.io.fs.FileMode;
    @:native("ModeType") static var ModeType: go.io.fs.FileMode;
    @:native("O_APPEND") static var O_APPEND: go.GoInt;
    @:native("O_CREATE") static var O_CREATE: go.GoInt;
    @:native("O_EXCL") static var O_EXCL: go.GoInt;
    @:native("O_RDONLY") static var O_RDONLY: go.GoInt;
    @:native("O_RDWR") static var O_RDWR: go.GoInt;
    @:native("O_SYNC") static var O_SYNC: go.GoInt;
    @:native("O_TRUNC") static var O_TRUNC: go.GoInt;
    @:native("O_WRONLY") static var O_WRONLY: go.GoInt;
    @:native("PathListSeparator") static var PathListSeparator: go.Rune;
    @:native("PathSeparator") static var PathSeparator: go.Rune;
    @:native("SEEK_CUR") static var SEEK_CUR: go.GoInt;
    @:native("SEEK_END") static var SEEK_END: go.GoInt;
    @:native("SEEK_SET") static var SEEK_SET: go.GoInt;

    @:native("Args") static var Args: go.Slice<String>;
    @:native("Interrupt") static var Interrupt: go.os.Signal;
    @:native("Kill") static var Kill: go.os.Signal;
    @:native("Stderr") static var Stderr: go.Pointer<go.os.File>;
    @:native("Stdin") static var Stdin: go.Pointer<go.os.File>;
    @:native("Stdout") static var Stdout: go.Pointer<go.os.File>;

    @:native("Chdir") static function chdir(dir: String): go.Error;
    @:native("Chmod") static function chmod(name: String, mode: go.os.FileMode): go.Error;
    @:native("Chown") static function chown(name: String, uid: go.GoInt, gid: go.GoInt): go.Error;
    @:native("Chtimes") static function chtimes(name: String, atime: go.time.Time, mtime: go.time.Time): go.Error;
    @:native("Clearenv") static function clearenv(): Void;
    @:native("CopyFS") static function copyFS(dir: String, fsys: go.io.fs.FS): go.Error;
    @:native("Create") static function create(name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("CreateTemp") static function createTemp(dir: String, pattern: String): go.Result<go.Pointer<go.os.File>>;
    @:native("DirFS") static function dirFS(dir: String): go.io.fs.FS;
    @:native("Environ") static function environ(): go.Slice<String>;
    @:native("Executable") static function executable(): go.Result<String>;
    @:native("Exit") static function exit(code: go.GoInt): Void;
    @:native("Expand") static function expand(s: String, mapping: (p0: String) -> String): String;
    @:native("ExpandEnv") static function expandEnv(s: String): String;
    @:native("FindProcess") static function findProcess(pid: go.GoInt): go.Result<go.Pointer<go.os.Process>>;
    @:native("Getegid") static function getegid(): go.GoInt;
    @:native("Getenv") static function getenv(key: String): String;
    @:native("Geteuid") static function geteuid(): go.GoInt;
    @:native("Getgid") static function getgid(): go.GoInt;
    @:native("Getgroups") static function getgroups(): go.Result<go.Slice<go.GoInt>>;
    @:native("Getpagesize") static function getpagesize(): go.GoInt;
    @:native("Getpid") static function getpid(): go.GoInt;
    @:native("Getppid") static function getppid(): go.GoInt;
    @:native("Getuid") static function getuid(): go.GoInt;
    @:native("Getwd") static function getwd(): go.Result<String>;
    @:native("Hostname") static function hostname(): go.Result<String>;
    @:native("IsExist") static function isExist(err: go.Error): Bool;
    @:native("IsNotExist") static function isNotExist(err: go.Error): Bool;
    @:native("IsPathSeparator") static function isPathSeparator(c: go.UInt8): Bool;
    @:native("IsPermission") static function isPermission(err: go.Error): Bool;
    @:native("IsTimeout") static function isTimeout(err: go.Error): Bool;
    @:native("Lchown") static function lchown(name: String, uid: go.GoInt, gid: go.GoInt): go.Error;
    @:native("Link") static function link(oldname: String, newname: String): go.Error;
    @:go.Tuple("p0", "p1") @:native("LookupEnv") static function lookupEnv(key: String): go.Tuple<{ p0: String, p1: Bool }>;
    @:native("Lstat") static function lstat(name: String): go.Result<go.os.FileInfo>;
    @:native("Mkdir") static function mkdir(name: String, perm: go.os.FileMode): go.Error;
    @:native("MkdirAll") static function mkdirAll(path: String, perm: go.os.FileMode): go.Error;
    @:native("MkdirTemp") static function mkdirTemp(dir: String, pattern: String): go.Result<String>;
    @:native("NewFile") static function newFile(fd: go.UIntPtr, name: String): go.Pointer<go.os.File>;
    @:native("NewSyscallError") static function newSyscallError(syscall: String, err: go.Error): go.Error;
    @:native("Open") static function open(name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("OpenFile") static function openFile(name: String, flag: go.GoInt, perm: go.os.FileMode): go.Result<go.Pointer<go.os.File>>;
    @:native("OpenInRoot") static function openInRoot(dir: String, name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("OpenRoot") static function openRoot(name: String): go.Result<go.Pointer<go.os.Root>>;
    @:go.Tuple("r", "w", "err") @:native("Pipe") static function pipe(): go.Tuple<{ r: go.Pointer<go.os.File>, w: go.Pointer<go.os.File>, err: go.Error }>;
    @:native("ReadDir") static function readDir(name: String): go.Result<go.Slice<go.os.DirEntry>>;
    @:native("ReadFile") static function readFile(name: String): go.Result<go.Slice<go.Byte>>;
    @:native("Readlink") static function readlink(name: String): go.Result<String>;
    @:native("Remove") static function remove(name: String): go.Error;
    @:native("RemoveAll") static function removeAll(path: String): go.Error;
    @:native("Rename") static function rename(oldpath: String, newpath: String): go.Error;
    @:native("SameFile") static function sameFile(fi1: go.os.FileInfo, fi2: go.os.FileInfo): Bool;
    @:native("Setenv") static function setenv(key: String, value: String): go.Error;
    @:native("StartProcess") static function startProcess(name: String, argv: go.Slice<String>, attr: go.Pointer<go.os.ProcAttr>): go.Result<go.Pointer<go.os.Process>>;
    @:native("Stat") static function stat(name: String): go.Result<go.os.FileInfo>;
    @:native("Symlink") static function symlink(oldname: String, newname: String): go.Error;
    @:native("TempDir") static function tempDir(): String;
    @:native("Truncate") static function truncate(name: String, size: go.Int64): go.Error;
    @:native("Unsetenv") static function unsetenv(key: String): go.Error;
    @:native("UserCacheDir") static function userCacheDir(): go.Result<String>;
    @:native("UserConfigDir") static function userConfigDir(): go.Result<String>;
    @:native("UserHomeDir") static function userHomeDir(): go.Result<String>;
    @:native("WriteFile") static function writeFile(name: String, data: go.Slice<go.Byte>, perm: go.os.FileMode): go.Error;

}