package go;

@:go.Type({ name: "os", instanceName: "os.os", imports: ["os"] })
extern class Os {

    @:native("DevNull") static var DevNull: String;
    @:native("ModeAppend") static var ModeAppend: go.io.fs.FileMode;
    @:native("ModeCharDevice") static var ModeCharDevice: go.io.fs.FileMode;
    @:native("ModeDevice") static var ModeDevice: go.io.fs.FileMode;
    @:native("ModeDir") static var ModeDir: go.io.fs.FileMode;
    @:native("ModeExclusive") static var ModeExclusive: go.io.fs.FileMode;
    @:native("ModeIrregular") static var ModeIrregular: go.io.fs.FileMode;
    @:native("ModeNamedPipe") static var ModeNamedPipe: go.io.fs.FileMode;
    @:native("ModePerm") static var ModePerm: go.io.fs.FileMode;
    @:native("ModeSetgid") static var ModeSetgid: go.io.fs.FileMode;
    @:native("ModeSetuid") static var ModeSetuid: go.io.fs.FileMode;
    @:native("ModeSocket") static var ModeSocket: go.io.fs.FileMode;
    @:native("ModeSticky") static var ModeSticky: go.io.fs.FileMode;
    @:native("ModeSymlink") static var ModeSymlink: go.io.fs.FileMode;
    @:native("ModeTemporary") static var ModeTemporary: go.io.fs.FileMode;
    @:native("ModeType") static var ModeType: go.io.fs.FileMode;
    @:native("O_APPEND") static var O_APPEND: go.GoInt;
    @:native("O_CREATE") static var O_CREATE: go.GoInt;
    @:native("O_EXCL") static var O_EXCL: go.GoInt;
    @:native("O_RDONLY") static var O_RDONLY: go.GoInt;
    @:native("O_RDWR") static var O_RDWR: go.GoInt;
    @:native("O_SYNC") static var O_SYNC: go.GoInt;
    @:native("O_TRUNC") static var O_TRUNC: go.GoInt;
    @:native("O_WRONLY") static var O_WRONLY: go.GoInt;
    @:native("PathListSeparator") static var PathListSeparator: go.Rune;
    @:native("PathSeparator") static var PathSeparator: go.Rune;
    @:native("SEEK_CUR") static var SEEK_CUR: go.GoInt;
    @:native("SEEK_END") static var SEEK_END: go.GoInt;
    @:native("SEEK_SET") static var SEEK_SET: go.GoInt;

    @:native("Args") static var args: go.Slice<String>;
    @:native("Interrupt") static var interrupt: go.os.Signal;
    @:native("Kill") static var kill: go.os.Signal;
    @:native("Stderr") static var stderr: go.Pointer<go.os.File>;
    @:native("Stdin") static var stdin: go.Pointer<go.os.File>;
    @:native("Stdout") static var stdout: go.Pointer<go.os.File>;
    @:native("checkWrapErr") static var _checkWrapErr: Bool;
    @:native("executablePath") static var _executablePath: String;
    @:native("getwdCache") static var _getwdCache: Dynamic;
    @:native("initCwd") static var _initCwd: String;
    @:native("stathook") static var _stathook: (f: go.Pointer<go.os.File>, name: String) -> go.Result<go.os.FileInfo>;

    @:native("Chdir") static function chdir(dir: String): (go.Error);
    @:native("Chmod") static function chmod(name: String, mode: go.os.FileMode): (go.Error);
    @:native("Chown") static function chown(name: String, uid: go.GoInt, gid: go.GoInt): (go.Error);
    @:native("Chtimes") static function chtimes(name: String, atime: go.time.Time, mtime: go.time.Time): (go.Error);
    @:native("Clearenv") static function clearenv(): Void;
    @:native("CopyFS") static function copyFS(dir: String, fsys: go.io.fs.FS): (go.Error);
    @:native("Create") static function create(name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("CreateTemp") static function createTemp(dir: String, pattern: String): go.Result<go.Pointer<go.os.File>>;
    @:native("DirFS") static function dirFS(dir: String): (go.io.fs.FS);
    @:native("Environ") static function environ(): (go.Slice<String>);
    @:native("Executable") static function executable(): go.Result<String>;
    @:native("Exit") static function exit(code: go.GoInt): Void;
    @:native("Expand") static function expand(s: String, mapping: (p0: String) -> (String)): (String);
    @:native("ExpandEnv") static function expandEnv(s: String): (String);
    @:native("FindProcess") static function findProcess(pid: go.GoInt): go.Result<go.Pointer<go.os.Process>>;
    @:native("Getegid") static function getegid(): (go.GoInt);
    @:native("Getenv") static function getenv(key: String): (String);
    @:native("Geteuid") static function geteuid(): (go.GoInt);
    @:native("Getgid") static function getgid(): (go.GoInt);
    @:native("Getgroups") static function getgroups(): go.Result<go.Slice<go.GoInt>>;
    @:native("Getpagesize") static function getpagesize(): (go.GoInt);
    @:native("Getpid") static function getpid(): (go.GoInt);
    @:native("Getppid") static function getppid(): (go.GoInt);
    @:native("Getuid") static function getuid(): (go.GoInt);
    @:native("Getwd") static function getwd(): go.Result<String>;
    @:native("Hostname") static function hostname(): go.Result<String>;
    @:native("IsExist") static function isExist(err: go.Error): (Bool);
    @:native("IsNotExist") static function isNotExist(err: go.Error): (Bool);
    @:native("IsPathSeparator") static function isPathSeparator(c: go.UInt8): (Bool);
    @:native("IsPermission") static function isPermission(err: go.Error): (Bool);
    @:native("IsTimeout") static function isTimeout(err: go.Error): (Bool);
    @:native("Lchown") static function lchown(name: String, uid: go.GoInt, gid: go.GoInt): (go.Error);
    @:native("Link") static function link(oldname: String, newname: String): (go.Error);
    @:go.Tuple("p0", "p1") @:native("LookupEnv") static function lookupEnv(key: String): go.Tuple<{ p0: String, p1: Bool }>;
    @:native("Lstat") static function lstat(name: String): go.Result<go.os.FileInfo>;
    @:native("Mkdir") static function mkdir(name: String, perm: go.os.FileMode): (go.Error);
    @:native("MkdirAll") static function mkdirAll(path: String, perm: go.os.FileMode): (go.Error);
    @:native("MkdirTemp") static function mkdirTemp(dir: String, pattern: String): go.Result<String>;
    @:native("NewFile") static function newFile(fd: go.UIntPtr, name: String): (go.Pointer<go.os.File>);
    @:native("NewSyscallError") static function newSyscallError(syscall: String, err: go.Error): (go.Error);
    @:native("Open") static function open(name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("OpenFile") static function openFile(name: String, flag: go.GoInt, perm: go.os.FileMode): go.Result<go.Pointer<go.os.File>>;
    @:native("OpenInRoot") static function openInRoot(dir: String, name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("OpenRoot") static function openRoot(name: String): go.Result<go.Pointer<go.os.Root>>;
    @:go.Tuple("r", "w", "err") @:native("Pipe") static function pipe(): go.Tuple<{ r: go.Pointer<go.os.File>, w: go.Pointer<go.os.File>, err: go.Error }>;
    @:native("ReadDir") static function readDir(name: String): go.Result<go.Slice<go.os.DirEntry>>;
    @:native("ReadFile") static function readFile(name: String): go.Result<go.Slice<go.Byte>>;
    @:native("Readlink") static function readlink(name: String): go.Result<String>;
    @:native("Remove") static function remove(name: String): (go.Error);
    @:native("RemoveAll") static function removeAll(path: String): (go.Error);
    @:native("Rename") static function rename(oldpath: String, newpath: String): (go.Error);
    @:native("SameFile") static function sameFile(fi1: go.os.FileInfo, fi2: go.os.FileInfo): (Bool);
    @:native("Setenv") static function setenv(key: String, value: String): (go.Error);
    @:native("StartProcess") static function startProcess(name: String, argv: go.Slice<String>, attr: go.Pointer<go.os.ProcAttr>): go.Result<go.Pointer<go.os.Process>>;
    @:native("Stat") static function stat(name: String): go.Result<go.os.FileInfo>;
    @:native("Symlink") static function symlink(oldname: String, newname: String): (go.Error);
    @:native("TempDir") static function tempDir(): (String);
    @:native("Truncate") static function truncate(name: String, size: go.Int64): (go.Error);
    @:native("Unsetenv") static function unsetenv(key: String): (go.Error);
    @:native("UserCacheDir") static function userCacheDir(): go.Result<String>;
    @:native("UserConfigDir") static function userConfigDir(): go.Result<String>;
    @:native("UserHomeDir") static function userHomeDir(): go.Result<String>;
    @:native("WriteFile") static function writeFile(name: String, data: go.Slice<go.Byte>, perm: go.os.FileMode): (go.Error);
    @:native("afterResolvingSymlink") static function _afterResolvingSymlink(parent: go.GoInt, name: String, f: () -> (go.Error)): (go.Error);
    @:native("atime") static function _atime(fi: go.os.FileInfo): (go.time.Time);
    @:native("checkSymlink") static function _checkSymlink(parent: go.GoInt, name: String, origError: go.Error): (go.Error);
    @:native("chmod") static function _chmod(name: String, mode: go.os.FileMode): (go.Error);
    @:native("chmodat") static function _chmodat(parent: go.GoInt, name: String, mode: go.os.FileMode): (go.Error);
    @:native("chownat") static function _chownat(parent: go.GoInt, name: String, uid: go.GoInt, gid: go.GoInt): (go.Error);
    @:native("chtimesUtimes") static function _chtimesUtimes(atime: go.time.Time, mtime: go.time.Time): (go.GoArray<go.syscall.Timespec, 2>);
    @:native("chtimesat") static function _chtimesat(parent: go.GoInt, name: String, atime: go.time.Time, mtime: go.time.Time): (go.Error);
    @:native("closedir") static function _closedir(dir: go.UIntPtr): (go.Error);
    @:native("convertESRCH") static function _convertESRCH(err: go.Error): (go.Error);
    @:native("doInRoot") static function _doInRoot<T: Dynamic>(r: go.Pointer<go.os.Root>, name: String, openDirFunc: (parent: go.os.SysfdType, name: String) -> go.Result<go.os.SysfdType>, f: (parent: go.os.SysfdType, name: String) -> go.Result<T>): go.Result<T>;
    @:native("dtToType") static function _dtToType(typ: go.UInt8): (go.os.FileMode);
    @:native("endsWithDot") static function _endsWithDot(path: String): (Bool);
    @:go.Tuple("p0", "p1") @:native("ensurePidfd") static function _ensurePidfd(sysAttr: go.Pointer<go.syscall.SysProcAttr>): go.Tuple<{ p0: go.Pointer<go.syscall.SysProcAttr>, p1: Bool }>;
    @:native("epipecheck") static function _epipecheck(file: go.Pointer<go.os.File>, e: go.Error): Void;
    @:native("errDeadlineExceeded") static function _errDeadlineExceeded(): (go.Error);
    @:native("errNoDeadline") static function _errNoDeadline(): (go.Error);
    @:native("executable") static function _executable(): go.Result<String>;
    @:native("fillFileStatFromSys") static function _fillFileStatFromSys(fs: go.Pointer<go.os.FileStat>, name: String): Void;
    @:native("findProcess") static function _findProcess(pid: go.GoInt): go.Result<go.Pointer<go.os.Process>>;
    @:native("fixCount") static function _fixCount(n: go.GoInt, err: go.Error): go.Result<go.GoInt>;
    @:native("fixLongPath") static function _fixLongPath(path: String): (String);
    @:native("genericReadFrom") static function _genericReadFrom(f: go.Pointer<go.os.File>, r: go.io.Reader): go.Result<go.Int64>;
    @:native("genericWriteTo") static function _genericWriteTo(f: go.Pointer<go.os.File>, w: go.io.Writer): go.Result<go.Int64>;
    @:go.Tuple("p0", "p1") @:native("getPidfd") static function _getPidfd(_: go.Pointer<go.syscall.SysProcAttr>, _: Bool): go.Tuple<{ p0: go.UIntPtr, p1: Bool }>;
    @:go.Tuple("p0", "p1") @:native("getShellName") static function _getShellName(s: String): go.Tuple<{ p0: String, p1: go.GoInt }>;
    @:native("hostname") static function _hostname(): go.Result<String>;
    @:native("ignoringEINTR") static function _ignoringEINTR(fn: () -> (go.Error)): (go.Error);
    @:native("ignoringEINTR2") static function _ignoringEINTR2<T: Dynamic>(fn: () -> go.Result<T>): go.Result<T>;
    @:native("isAlphaNum") static function _isAlphaNum(c: go.UInt8): (Bool);
    @:native("isErrNoFollow") static function _isErrNoFollow(err: go.Error): (Bool);
    @:native("isNoFollowErr") static function _isNoFollowErr(err: go.Error): (Bool);
    @:native("isShellSpecialVar") static function _isShellSpecialVar(c: go.UInt8): (Bool);
    @:native("isValidRootFSPath") static function _isValidRootFSPath(name: String): (Bool);
    @:native("joinPath") static function _joinPath(dir: String, name: String): (String);
    @:native("lchownat") static function _lchownat(parent: go.GoInt, name: String, uid: go.GoInt, gid: go.GoInt): (go.Error);
    @:native("linkat") static function _linkat(oldfd: go.GoInt, oldname: String, newfd: go.GoInt, newname: String): (go.Error);
    @:native("lstatNolog") static function _lstatNolog(name: String): go.Result<go.os.FileInfo>;
    @:native("mkdirat") static function _mkdirat(fd: go.GoInt, name: String, perm: go.os.FileMode): (go.Error);
    @:native("modeAt") static function _modeAt(parent: go.GoInt, name: String): go.Result<go.os.FileMode>;
    @:native("net_newUnixFile") static function _net_newUnixFile(fd: go.GoInt, name: String): (go.Pointer<go.os.File>);
    @:native("newDirFile") static function _newDirFile(fd: go.GoInt, name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("newDoneProcess") static function _newDoneProcess(pid: go.GoInt): (go.Pointer<go.os.Process>);
    @:native("newFile") static function _newFile(fd: go.GoInt, name: String, kind: go.os.NewFileKind, nonBlocking: Bool): (go.Pointer<go.os.File>);
    @:native("newFileFromNewFile") static function _newFileFromNewFile(fd: go.UIntPtr, name: String): (go.Pointer<go.os.File>);
    @:native("newHandleProcess") static function _newHandleProcess(pid: go.GoInt, handle: go.UIntPtr): (go.Pointer<go.os.Process>);
    @:native("newPIDProcess") static function _newPIDProcess(pid: go.GoInt): (go.Pointer<go.os.Process>);
    @:native("newRawConn") static function _newRawConn(file: go.Pointer<go.os.File>): go.Result<go.Pointer<go.os.RawConn>>;
    @:native("newRoot") static function _newRoot(fd: go.GoInt, name: String): go.Result<go.Pointer<go.os.Root>>;
    @:native("newUnixDirent") static function _newUnixDirent(parent: go.Pointer<go.os.File>, name: String, typ: go.os.FileMode): go.Result<go.os.DirEntry>;
    @:native("nextRandom") static function _nextRandom(): (String);
    @:go.Tuple("p0", "p1", "p2") @:native("open") static function _open(path: String, flag: go.GoInt, perm: go.UInt32): go.Tuple<{ p0: go.GoInt, p1: go.internal.poll.SysFile, p2: go.Error }>;
    @:native("openDir") static function _openDir(name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("openDirAt") static function _openDirAt(dirfd: go.os.SysfdType, name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("openDirNolog") static function _openDirNolog(name: String): go.Result<go.Pointer<go.os.File>>;
    @:native("openFileNolog") static function _openFileNolog(name: String, flag: go.GoInt, perm: go.os.FileMode): go.Result<go.Pointer<go.os.File>>;
    @:native("openRootInRoot") static function _openRootInRoot(r: go.Pointer<go.os.Root>, name: String): go.Result<go.Pointer<go.os.Root>>;
    @:native("openRootNolog") static function _openRootNolog(name: String): go.Result<go.Pointer<go.os.Root>>;
    @:native("pidfdFind") static function _pidfdFind(_: go.GoInt): go.Result<go.UIntPtr>;
    @:go.Tuple("prefix", "suffix", "err") @:native("prefixAndSuffix") static function _prefixAndSuffix(pattern: String): go.Tuple<{ prefix: String, suffix: String, err: go.Error }>;
    @:native("readFileContents") static function _readFileContents(statSize: go.Int64, read: (p0: go.Slice<go.Byte>) -> go.Result<go.GoInt>): go.Result<go.Slice<go.Byte>>;
    @:native("readdir_r") static function _readdir_r(dir: go.UIntPtr, entry: go.Pointer<go.syscall.Dirent>, result: go.Pointer<go.Pointer<go.syscall.Dirent>>): (go.syscall.Errno);
    @:native("readlink") static function _readlink(name: String): go.Result<String>;
    @:native("readlinkat") static function _readlinkat(fd: go.GoInt, name: String): go.Result<String>;
    @:native("removeAll") static function _removeAll(path: String): (go.Error);
    @:native("removeAllFrom") static function _removeAllFrom(parentFd: go.os.SysfdType, base: String): (go.Error);
    @:native("removeat") static function _removeat(fd: go.GoInt, name: String): (go.Error);
    @:native("removedirat") static function _removedirat(fd: go.GoInt, name: String): (go.Error);
    @:native("removefileat") static function _removefileat(fd: go.GoInt, name: String): (go.Error);
    @:native("rename") static function _rename(oldname: String, newname: String): (go.Error);
    @:native("renameat") static function _renameat(oldfd: go.GoInt, oldname: String, newfd: go.GoInt, newname: String): (go.Error);
    @:native("rootChmod") static function _rootChmod(r: go.Pointer<go.os.Root>, name: String, mode: go.os.FileMode): (go.Error);
    @:native("rootChown") static function _rootChown(r: go.Pointer<go.os.Root>, name: String, uid: go.GoInt, gid: go.GoInt): (go.Error);
    @:native("rootChtimes") static function _rootChtimes(r: go.Pointer<go.os.Root>, name: String, atime: go.time.Time, mtime: go.time.Time): (go.Error);
    @:native("rootCleanPath") static function _rootCleanPath(s: String, prefix: go.Slice<String>, suffix: go.Slice<String>): go.Result<String>;
    @:native("rootLchown") static function _rootLchown(r: go.Pointer<go.os.Root>, name: String, uid: go.GoInt, gid: go.GoInt): (go.Error);
    @:native("rootLink") static function _rootLink(r: go.Pointer<go.os.Root>, oldname: String, newname: String): (go.Error);
    @:native("rootMkdir") static function _rootMkdir(r: go.Pointer<go.os.Root>, name: String, perm: go.os.FileMode): (go.Error);
    @:native("rootMkdirAll") static function _rootMkdirAll(r: go.Pointer<go.os.Root>, fullname: String, perm: go.os.FileMode): (go.Error);
    @:native("rootOpenDir") static function _rootOpenDir(parent: go.GoInt, name: String): go.Result<go.GoInt>;
    @:native("rootOpenFileNolog") static function _rootOpenFileNolog(root: go.Pointer<go.os.Root>, name: String, flag: go.GoInt, perm: go.os.FileMode): go.Result<go.Pointer<go.os.File>>;
    @:native("rootReadlink") static function _rootReadlink(r: go.Pointer<go.os.Root>, name: String): go.Result<String>;
    @:native("rootRemove") static function _rootRemove(r: go.Pointer<go.os.Root>, name: String): (go.Error);
    @:native("rootRemoveAll") static function _rootRemoveAll(r: go.Pointer<go.os.Root>, name: String): (go.Error);
    @:native("rootRename") static function _rootRename(r: go.Pointer<go.os.Root>, oldname: String, newname: String): (go.Error);
    @:native("rootStat") static function _rootStat(r: go.Pointer<go.os.Root>, name: String, lstat: Bool): go.Result<go.os.FileInfo>;
    @:native("rootSymlink") static function _rootSymlink(r: go.Pointer<go.os.Root>, oldname: String, newname: String): (go.Error);
    @:native("runtime_args") static function _runtime_args(): (go.Slice<String>);
    @:native("runtime_beforeExit") static function _runtime_beforeExit(exitCode: go.GoInt): Void;
    @:native("runtime_rand") static function _runtime_rand(): (go.UInt64);
    @:native("sameFile") static function _sameFile(fs1: go.Pointer<go.os.FileStat>, fs2: go.Pointer<go.os.FileStat>): (Bool);
    @:native("setStickyBit") static function _setStickyBit(name: String): (go.Error);
    @:native("sigpipe") static function _sigpipe(): Void;
    @:go.Tuple("p0", "p1") @:native("splitPath") static function _splitPath(path: String): go.Tuple<{ p0: String, p1: String }>;
    @:go.Tuple("_", "suffixSep", "err") @:native("splitPathInRoot") static function _splitPathInRoot(s: String, prefix: go.Slice<String>, suffix: go.Slice<String>): go.Tuple<{ _: go.Slice<String>, suffixSep: String, err: go.Error }>;
    @:native("startProcess") static function _startProcess(name: String, argv: go.Slice<String>, attr: go.Pointer<go.os.ProcAttr>): go.Result<go.Pointer<go.os.Process>>;
    @:native("statNolog") static function _statNolog(name: String): go.Result<go.os.FileInfo>;
    @:native("statOrZero") static function _statOrZero(f: go.Pointer<go.os.File>): (go.Int64);
    @:native("symlinkat") static function _symlinkat(oldname: String, newfd: go.GoInt, newname: String): (go.Error);
    @:native("syscallMode") static function _syscallMode(i: go.os.FileMode): (go.UInt32);
    @:native("tempDir") static function _tempDir(): (String);
    @:go.Tuple("p0", "p1", "p2") @:native("tryLimitedReader") static function _tryLimitedReader(r: go.io.Reader): go.Tuple<{ p0: go.Pointer<go.io.LimitedReader>, p1: go.io.Reader, p2: go.Int64 }>;
    @:native("underlyingError") static function _underlyingError(err: go.Error): (go.Error);
    @:native("underlyingErrorIs") static function _underlyingErrorIs(err: go.Error, target: go.Error): (Bool);
    @:native("wrapSyscallError") static function _wrapSyscallError(name: String, err: go.Error): (go.Error);

}