package go;

@:go.Type({ name: "reflect", instanceName: "reflect.reflect", imports: ["reflect"] })
extern class Reflect {

    @:native("Array") static var Array: go.reflect.Kind;
    @:native("Bool") static var Bool: go.reflect.Kind;
    @:native("BothDir") static var BothDir: go.reflect.ChanDir;
    @:native("Chan") static var Chan: go.reflect.Kind;
    @:native("Complex128") static var Complex128: go.reflect.Kind;
    @:native("Complex64") static var Complex64: go.reflect.Kind;
    @:native("Float32") static var Float32: go.reflect.Kind;
    @:native("Float64") static var Float64: go.reflect.Kind;
    @:native("Func") static var Func: go.reflect.Kind;
    @:native("Int") static var Int: go.reflect.Kind;
    @:native("Int16") static var Int16: go.reflect.Kind;
    @:native("Int32") static var Int32: go.reflect.Kind;
    @:native("Int64") static var Int64: go.reflect.Kind;
    @:native("Int8") static var Int8: go.reflect.Kind;
    @:native("Interface") static var Interface: go.reflect.Kind;
    @:native("Invalid") static var Invalid: go.reflect.Kind;
    @:native("Map") static var Map: go.reflect.Kind;
    @:native("Pointer") static var Pointer: go.reflect.Kind;
    @:native("Ptr") static var Ptr: go.reflect.Kind;
    @:native("RecvDir") static var RecvDir: go.reflect.ChanDir;
    @:native("SelectDefault") static var SelectDefault: go.reflect.SelectDir;
    @:native("SelectRecv") static var SelectRecv: go.reflect.SelectDir;
    @:native("SelectSend") static var SelectSend: go.reflect.SelectDir;
    @:native("SendDir") static var SendDir: go.reflect.ChanDir;
    @:native("Slice") static var Slice: go.reflect.Kind;
    @:native("String") static var String: go.reflect.Kind;
    @:native("Struct") static var Struct: go.reflect.Kind;
    @:native("Uint") static var Uint: go.reflect.Kind;
    @:native("Uint16") static var Uint16: go.reflect.Kind;
    @:native("Uint32") static var Uint32: go.reflect.Kind;
    @:native("Uint64") static var Uint64: go.reflect.Kind;
    @:native("Uint8") static var Uint8: go.reflect.Kind;
    @:native("Uintptr") static var Uintptr: go.reflect.Kind;
    @:native("UnsafePointer") static var UnsafePointer: go.reflect.Kind;

    @:native("bytesType") static var _bytesType: go.Pointer<go.internal.abi.Type>;
    @:native("callGC") static var _callGC: Bool;
    @:native("dummy") static var _dummy: Dynamic;
    @:native("floatArgRegs") static var _floatArgRegs: go.GoInt;
    @:native("floatRegSize") static var _floatRegSize: go.UIntPtr;
    @:native("funcLookupCache") static var _funcLookupCache: Dynamic;
    @:native("funcTypes") static var _funcTypes: go.Slice<go.reflect.Type>;
    @:native("funcTypesMutex") static var _funcTypesMutex: go.sync.Mutex;
    @:native("intArgRegs") static var _intArgRegs: go.GoInt;
    @:native("kindNames") static var _kindNames: go.Slice<String>;
    @:native("layoutCache") static var _layoutCache: go.sync.Map;
    @:native("lookupCache") static var _lookupCache: go.sync.Map;
    @:native("ptrMap") static var _ptrMap: go.sync.Map;
    @:native("stringType") static var _stringType: go.Pointer<go.internal.abi.Type>;
    @:native("structLookupCache") static var _structLookupCache: Dynamic;
    @:native("uint8Type") static var _uint8Type: go.Pointer<go.internal.abi.Type>;
    @:native("zeroVal") static var _zeroVal: go.GoArray<go.Byte, 1024>;

    @:native("Append") static function append(s: go.reflect.Value, x: haxe.Rest<go.reflect.Value>): (go.reflect.Value);
    @:native("AppendSlice") static function appendSlice(s: go.reflect.Value, t: go.reflect.Value): (go.reflect.Value);
    @:native("ArrayOf") static function arrayOf(length: go.GoInt, elem: go.reflect.Type): (go.reflect.Type);
    @:native("ChanOf") static function chanOf(dir: go.reflect.ChanDir, t: go.reflect.Type): (go.reflect.Type);
    @:native("Copy") static function copy(dst: go.reflect.Value, src: go.reflect.Value): (go.GoInt);
    @:native("DeepEqual") static function deepEqual(x: Dynamic, y: Dynamic): (Bool);
    @:native("FuncOf") static function funcOf(_in: go.Slice<go.reflect.Type>, out: go.Slice<go.reflect.Type>, variadic: Bool): (go.reflect.Type);
    @:native("Indirect") static function indirect(v: go.reflect.Value): (go.reflect.Value);
    @:native("MakeChan") static function makeChan(typ: go.reflect.Type, buffer: go.GoInt): (go.reflect.Value);
    @:native("MakeFunc") static function makeFunc(typ: go.reflect.Type, fn: (args: go.Slice<go.reflect.Value>) -> (go.Slice<go.reflect.Value>)): (go.reflect.Value);
    @:native("MakeMap") static function makeMap(typ: go.reflect.Type): (go.reflect.Value);
    @:native("MakeMapWithSize") static function makeMapWithSize(typ: go.reflect.Type, n: go.GoInt): (go.reflect.Value);
    @:native("MakeSlice") static function makeSlice(typ: go.reflect.Type, len: go.GoInt, cap: go.GoInt): (go.reflect.Value);
    @:native("MapOf") static function mapOf(key: go.reflect.Type, elem: go.reflect.Type): (go.reflect.Type);
    @:native("New") static function _new(typ: go.reflect.Type): (go.reflect.Value);
    @:native("NewAt") static function newAt(typ: go.reflect.Type, p: go.unsafe.Pointer): (go.reflect.Value);
    @:native("PointerTo") static function pointerTo(t: go.reflect.Type): (go.reflect.Type);
    @:native("PtrTo") static function ptrTo(t: go.reflect.Type): (go.reflect.Type);
    @:go.Tuple("chosen", "recv", "recvOK") @:native("Select") static function select(cases: go.Slice<go.reflect.SelectCase>): go.Tuple<{ chosen: go.GoInt, recv: go.reflect.Value, recvOK: Bool }>;
    @:native("SliceAt") static function sliceAt(typ: go.reflect.Type, p: go.unsafe.Pointer, n: go.GoInt): (go.reflect.Value);
    @:native("SliceOf") static function sliceOf(t: go.reflect.Type): (go.reflect.Type);
    @:native("StructOf") static function structOf(fields: go.Slice<go.reflect.StructField>): (go.reflect.Type);
    @:native("Swapper") static function swapper(slice: Dynamic): ((i: go.GoInt, j: go.GoInt) -> Void);
    @:go.Tuple("p0", "p1") @:native("TypeAssert") static function typeAssert<T: Dynamic>(v: go.reflect.Value): go.Tuple<{ p0: T, p1: Bool }>;
    @:native("TypeFor") static function typeFor<T: Dynamic>(): (go.reflect.Type);
    @:native("TypeOf") static function typeOf(i: Dynamic): (go.reflect.Type);
    @:native("ValueOf") static function valueOf(i: Dynamic): (go.reflect.Value);
    @:native("VisibleFields") static function visibleFields(t: go.reflect.Type): (go.Slice<go.reflect.StructField>);
    @:native("Zero") static function zero(typ: go.reflect.Type): (go.reflect.Value);
    @:native("add") static function _add(p: go.unsafe.Pointer, x: go.UIntPtr, whySafe: String): (go.unsafe.Pointer);
    @:native("addReflectOff") static function _addReflectOff(ptr: go.unsafe.Pointer): (go.Int32);
    @:native("addTypeBits") static function _addTypeBits(bv: go.Pointer<go.reflect.BitVector>, offset: go.UIntPtr, t: go.Pointer<go.internal.abi.Type>): Void;
    @:native("align") static function _align(x: go.UIntPtr, n: go.UIntPtr): (go.UIntPtr);
    @:native("appendVarint") static function _appendVarint(x: go.Slice<go.Byte>, v: go.UIntPtr): (go.Slice<go.Byte>);
    @:native("archFloat32FromReg") static function _archFloat32FromReg(reg: go.UInt64): (go.Float32);
    @:native("archFloat32ToReg") static function _archFloat32ToReg(val: go.Float32): (go.UInt64);
    @:native("arrayAt") static function _arrayAt(p: go.unsafe.Pointer, i: go.GoInt, eltSize: go.UIntPtr, whySafe: String): (go.unsafe.Pointer);
    @:native("badlinkname_Value_pointer") static function _badlinkname_Value_pointer(p0: go.reflect.Value): (go.unsafe.Pointer);
    @:native("badlinkname_rtype_Align") static function _badlinkname_rtype_Align(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_AssignableTo") static function _badlinkname_rtype_AssignableTo(p0: go.Pointer<go.reflect.Rtype>, p1: go.reflect.Type): (Bool);
    @:native("badlinkname_rtype_Bits") static function _badlinkname_rtype_Bits(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_ChanDir") static function _badlinkname_rtype_ChanDir(p0: go.Pointer<go.reflect.Rtype>): (go.reflect.ChanDir);
    @:native("badlinkname_rtype_Comparable") static function _badlinkname_rtype_Comparable(p0: go.Pointer<go.reflect.Rtype>): (Bool);
    @:native("badlinkname_rtype_ConvertibleTo") static function _badlinkname_rtype_ConvertibleTo(p0: go.Pointer<go.reflect.Rtype>, p1: go.reflect.Type): (Bool);
    @:native("badlinkname_rtype_Elem") static function _badlinkname_rtype_Elem(p0: go.Pointer<go.reflect.Rtype>): (go.reflect.Type);
    @:native("badlinkname_rtype_Field") static function _badlinkname_rtype_Field(p0: go.Pointer<go.reflect.Rtype>, p1: go.GoInt): (go.reflect.StructField);
    @:native("badlinkname_rtype_FieldAlign") static function _badlinkname_rtype_FieldAlign(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_FieldByIndex") static function _badlinkname_rtype_FieldByIndex(p0: go.Pointer<go.reflect.Rtype>, p1: go.Slice<go.GoInt>): (go.reflect.StructField);
    @:go.Tuple("p0", "p1") @:native("badlinkname_rtype_FieldByName") static function _badlinkname_rtype_FieldByName(p0: go.Pointer<go.reflect.Rtype>, p1: String): go.Tuple<{ p0: go.reflect.StructField, p1: Bool }>;
    @:go.Tuple("p0", "p1") @:native("badlinkname_rtype_FieldByNameFunc") static function _badlinkname_rtype_FieldByNameFunc(p0: go.Pointer<go.reflect.Rtype>, p1: (p0: String) -> (Bool)): go.Tuple<{ p0: go.reflect.StructField, p1: Bool }>;
    @:native("badlinkname_rtype_Implements") static function _badlinkname_rtype_Implements(p0: go.Pointer<go.reflect.Rtype>, p1: go.reflect.Type): (Bool);
    @:native("badlinkname_rtype_In") static function _badlinkname_rtype_In(p0: go.Pointer<go.reflect.Rtype>, p1: go.GoInt): (go.reflect.Type);
    @:native("badlinkname_rtype_IsVariadic") static function _badlinkname_rtype_IsVariadic(p0: go.Pointer<go.reflect.Rtype>): (Bool);
    @:native("badlinkname_rtype_Key") static function _badlinkname_rtype_Key(p0: go.Pointer<go.reflect.Rtype>): (go.reflect.Type);
    @:native("badlinkname_rtype_Kind") static function _badlinkname_rtype_Kind(p0: go.Pointer<go.reflect.Rtype>): (go.reflect.Kind);
    @:native("badlinkname_rtype_Len") static function _badlinkname_rtype_Len(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_Method") static function _badlinkname_rtype_Method(p0: go.Pointer<go.reflect.Rtype>, p1: go.GoInt): (go.reflect.Method);
    @:go.Tuple("p0", "p1") @:native("badlinkname_rtype_MethodByName") static function _badlinkname_rtype_MethodByName(p0: go.Pointer<go.reflect.Rtype>, p1: String): go.Tuple<{ p0: go.reflect.Method, p1: Bool }>;
    @:native("badlinkname_rtype_Name") static function _badlinkname_rtype_Name(p0: go.Pointer<go.reflect.Rtype>): (String);
    @:native("badlinkname_rtype_NumField") static function _badlinkname_rtype_NumField(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_NumIn") static function _badlinkname_rtype_NumIn(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_NumMethod") static function _badlinkname_rtype_NumMethod(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_NumOut") static function _badlinkname_rtype_NumOut(p0: go.Pointer<go.reflect.Rtype>): (go.GoInt);
    @:native("badlinkname_rtype_Out") static function _badlinkname_rtype_Out(p0: go.Pointer<go.reflect.Rtype>, p1: go.GoInt): (go.reflect.Type);
    @:native("badlinkname_rtype_PkgPath") static function _badlinkname_rtype_PkgPath(p0: go.Pointer<go.reflect.Rtype>): (String);
    @:native("badlinkname_rtype_Size") static function _badlinkname_rtype_Size(p0: go.Pointer<go.reflect.Rtype>): (go.UIntPtr);
    @:native("badlinkname_rtype_String") static function _badlinkname_rtype_String(p0: go.Pointer<go.reflect.Rtype>): (String);
    @:native("badlinkname_rtype_ptrTo") static function _badlinkname_rtype_ptrTo(p0: go.Pointer<go.reflect.Rtype>): (go.Pointer<go.internal.abi.Type>);
    @:native("call") static function _call(stackArgsType: go.Pointer<go.internal.abi.Type>, f: go.unsafe.Pointer, stackArgs: go.unsafe.Pointer, stackArgsSize: go.UInt32, stackRetOffset: go.UInt32, frameSize: go.UInt32, regArgs: go.Pointer<go.internal.abi.RegArgs>): Void;
    @:native("callMethod") static function _callMethod(ctxt: go.Pointer<go.reflect.MethodValue>, frame: go.unsafe.Pointer, retValid: go.Pointer<Bool>, regs: go.Pointer<go.internal.abi.RegArgs>): Void;
    @:native("callReflect") static function _callReflect(ctxt: go.Pointer<go.reflect.MakeFuncImpl>, frame: go.unsafe.Pointer, retValid: go.Pointer<Bool>, regs: go.Pointer<go.internal.abi.RegArgs>): Void;
    @:native("canRangeFunc") static function _canRangeFunc(t: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("canRangeFunc2") static function _canRangeFunc2(t: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("chancap") static function _chancap(ch: go.unsafe.Pointer): (go.GoInt);
    @:native("chanclose") static function _chanclose(ch: go.unsafe.Pointer): Void;
    @:native("chanlen") static function _chanlen(ch: go.unsafe.Pointer): (go.GoInt);
    @:go.Tuple("selected", "received") @:native("chanrecv") static function _chanrecv(ch: go.unsafe.Pointer, nb: Bool, val: go.unsafe.Pointer): go.Tuple<{ selected: Bool, received: Bool }>;
    @:native("chansend") static function _chansend(ch: go.unsafe.Pointer, val: go.unsafe.Pointer, nb: Bool): (Bool);
    @:native("chansend0") static function _chansend0(ch: go.unsafe.Pointer, val: go.unsafe.Pointer, nb: Bool): (Bool);
    @:native("contentEscapes") static function _contentEscapes(x: go.unsafe.Pointer): Void;
    @:native("convertOp") static function _convertOp(dst: go.Pointer<go.internal.abi.Type>, src: go.Pointer<go.internal.abi.Type>): ((p0: go.reflect.Value, p1: go.reflect.Type) -> (go.reflect.Value));
    @:native("copyVal") static function _copyVal(typ: go.Pointer<go.internal.abi.Type>, fl: go.reflect.Flag, ptr: go.unsafe.Pointer): (go.reflect.Value);
    @:native("cvtBytesString") static function _cvtBytesString(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtComplex") static function _cvtComplex(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtDirect") static function _cvtDirect(v: go.reflect.Value, typ: go.reflect.Type): (go.reflect.Value);
    @:native("cvtFloat") static function _cvtFloat(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtFloatInt") static function _cvtFloatInt(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtFloatUint") static function _cvtFloatUint(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtI2I") static function _cvtI2I(v: go.reflect.Value, typ: go.reflect.Type): (go.reflect.Value);
    @:native("cvtInt") static function _cvtInt(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtIntFloat") static function _cvtIntFloat(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtIntString") static function _cvtIntString(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtRunesString") static function _cvtRunesString(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtSliceArray") static function _cvtSliceArray(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtSliceArrayPtr") static function _cvtSliceArrayPtr(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtStringBytes") static function _cvtStringBytes(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtStringRunes") static function _cvtStringRunes(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtT2I") static function _cvtT2I(v: go.reflect.Value, typ: go.reflect.Type): (go.reflect.Value);
    @:native("cvtUint") static function _cvtUint(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtUintFloat") static function _cvtUintFloat(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("cvtUintString") static function _cvtUintString(v: go.reflect.Value, t: go.reflect.Type): (go.reflect.Value);
    @:native("deepValueEqual") static function _deepValueEqual(v1: go.reflect.Value, v2: go.reflect.Value, visited: go.Map<go.reflect.Visit, Bool>): (Bool);
    @:native("directlyAssignable") static function _directlyAssignable(T: go.Pointer<go.internal.abi.Type>, V: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("dumpPtrBitMap") static function _dumpPtrBitMap(b: go.internal.abi.IntArgRegBitmap): Void;
    @:native("elem") static function _elem(t: go.Pointer<go.internal.abi.Type>): (go.Pointer<go.internal.abi.Type>);
    @:native("embeddedIfaceMethStub") static function _embeddedIfaceMethStub(): Void;
    @:native("emitGCMask") static function _emitGCMask(out: go.Slice<go.Byte>, base: go.UIntPtr, typ: go.Pointer<go.internal.abi.Type>, n: go.UIntPtr): Void;
    @:native("escapes") static function _escapes(x: Dynamic): Void;
    @:native("floatFromReg") static function _floatFromReg(r: go.Pointer<go.internal.abi.RegArgs>, reg: go.GoInt, argSize: go.UIntPtr, _to: go.unsafe.Pointer): Void;
    @:native("floatToReg") static function _floatToReg(r: go.Pointer<go.internal.abi.RegArgs>, reg: go.GoInt, argSize: go.UIntPtr, _from: go.unsafe.Pointer): Void;
    @:native("fnv1") static function _fnv1(x: go.UInt32, list: haxe.Rest<go.Byte>): (go.UInt32);
    @:go.Tuple("frametype", "framePool", "abid") @:native("funcLayout") static function _funcLayout(t: go.Pointer<go.reflect.FuncType>, rcvr: go.Pointer<go.internal.abi.Type>): go.Tuple<{ frametype: go.Pointer<go.internal.abi.Type>, framePool: go.Pointer<go.sync.Pool>, abid: go.reflect.AbiDesc }>;
    @:native("funcName") static function _funcName(f: (p0: go.Slice<go.reflect.Value>) -> (go.Slice<go.reflect.Value>)): (String);
    @:native("funcStr") static function _funcStr(ft: go.Pointer<go.reflect.FuncType>): (String);
    @:native("getStaticuint64s") static function _getStaticuint64s(): (go.Pointer<go.GoArray<go.UInt64, 256>>);
    @:go.Tuple("p0", "p1") @:native("groupAndSlotOf") static function _groupAndSlotOf(ktyp: go.reflect.Type, etyp: go.reflect.Type): go.Tuple<{ p0: go.reflect.Type, p1: go.reflect.Type }>;
    @:native("growslice") static function _growslice(t: go.Pointer<go.internal.abi.Type>, old: go.internal.unsafeheader.Slice, num: go.GoInt): (go.internal.unsafeheader.Slice);
    @:native("hashMightPanic") static function _hashMightPanic(t: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("haveIdenticalType") static function _haveIdenticalType(T: go.Pointer<go.internal.abi.Type>, V: go.Pointer<go.internal.abi.Type>, cmpTags: Bool): (Bool);
    @:native("haveIdenticalUnderlyingType") static function _haveIdenticalUnderlyingType(T: go.Pointer<go.internal.abi.Type>, V: go.Pointer<go.internal.abi.Type>, cmpTags: Bool): (Bool);
    @:native("ifaceE2I") static function _ifaceE2I(t: go.Pointer<go.internal.abi.Type>, src: Dynamic, dst: go.unsafe.Pointer): Void;
    @:native("implements") static function _implements(T: go.Pointer<go.internal.abi.Type>, V: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("initFuncTypes") static function _initFuncTypes(n: go.GoInt): (go.reflect.Type);
    @:native("intFromReg") static function _intFromReg(r: go.Pointer<go.internal.abi.RegArgs>, reg: go.GoInt, argSize: go.UIntPtr, _to: go.unsafe.Pointer): Void;
    @:native("intToReg") static function _intToReg(r: go.Pointer<go.internal.abi.RegArgs>, reg: go.GoInt, argSize: go.UIntPtr, _from: go.unsafe.Pointer): Void;
    @:native("isLetter") static function _isLetter(ch: go.Rune): (Bool);
    @:native("isPaddedField") static function _isPaddedField(t: go.reflect.Type, i: go.GoInt): (Bool);
    @:native("isReflexive") static function _isReflexive(t: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("isRegularMemory") static function _isRegularMemory(t: go.reflect.Type): (Bool);
    @:native("isValidFieldName") static function _isValidFieldName(fieldName: String): (Bool);
    @:native("isZero") static function _isZero(b: go.Slice<go.Byte>): (Bool);
    @:native("makeBytes") static function _makeBytes(f: go.reflect.Flag, v: go.Slice<go.Byte>, t: go.reflect.Type): (go.reflect.Value);
    @:native("makeComplex") static function _makeComplex(f: go.reflect.Flag, v: go.Complex128, t: go.reflect.Type): (go.reflect.Value);
    @:native("makeFloat") static function _makeFloat(f: go.reflect.Flag, v: Float, t: go.reflect.Type): (go.reflect.Value);
    @:native("makeFloat32") static function _makeFloat32(f: go.reflect.Flag, v: go.Float32, t: go.reflect.Type): (go.reflect.Value);
    @:native("makeFuncStub") static function _makeFuncStub(): Void;
    @:native("makeInt") static function _makeInt(f: go.reflect.Flag, bits: go.UInt64, t: go.reflect.Type): (go.reflect.Value);
    @:native("makeMethodValue") static function _makeMethodValue(op: String, v: go.reflect.Value): (go.reflect.Value);
    @:native("makeRunes") static function _makeRunes(f: go.reflect.Flag, v: go.Slice<go.Rune>, t: go.reflect.Type): (go.reflect.Value);
    @:native("makeString") static function _makeString(f: go.reflect.Flag, v: String, t: go.reflect.Type): (go.reflect.Value);
    @:native("makechan") static function _makechan(typ: go.Pointer<go.internal.abi.Type>, size: go.GoInt): (go.unsafe.Pointer);
    @:native("makemap") static function _makemap(t: go.Pointer<go.internal.abi.Type>, cap: go.GoInt): (go.unsafe.Pointer);
    @:native("mapIterNext") static function _mapIterNext(it: go.Pointer<go.internal.runtime.maps.Iter>): Void;
    @:native("mapIterStart") static function _mapIterStart(t: go.Pointer<go.internal.abi.MapType>, m: go.Pointer<go.internal.runtime.maps.Map>, it: go.Pointer<go.internal.runtime.maps.Iter>): Void;
    @:native("mapaccess") static function _mapaccess(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: go.unsafe.Pointer): (go.unsafe.Pointer);
    @:native("mapaccess_faststr") static function _mapaccess_faststr(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: String): (go.unsafe.Pointer);
    @:native("mapassign") static function _mapassign(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: go.unsafe.Pointer, val: go.unsafe.Pointer): Void;
    @:native("mapassign0") static function _mapassign0(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: go.unsafe.Pointer, val: go.unsafe.Pointer): Void;
    @:native("mapassign_faststr") static function _mapassign_faststr(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: String, val: go.unsafe.Pointer): Void;
    @:native("mapassign_faststr0") static function _mapassign_faststr0(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: String, val: go.unsafe.Pointer): Void;
    @:native("mapclear") static function _mapclear(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer): Void;
    @:native("mapdelete") static function _mapdelete(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: go.unsafe.Pointer): Void;
    @:native("mapdelete_faststr") static function _mapdelete_faststr(t: go.Pointer<go.internal.abi.Type>, m: go.unsafe.Pointer, key: String): Void;
    @:native("maplen") static function _maplen(m: go.unsafe.Pointer): (go.GoInt);
    @:native("memmove") static function _memmove(dst: go.unsafe.Pointer, src: go.unsafe.Pointer, size: go.UIntPtr): Void;
    @:go.Tuple("rcvrtype", "t", "fn") @:native("methodReceiver") static function _methodReceiver(op: String, v: go.reflect.Value, methodIndex: go.GoInt): go.Tuple<{ rcvrtype: go.Pointer<go.internal.abi.Type>, t: go.Pointer<go.reflect.FuncType>, fn: go.unsafe.Pointer }>;
    @:native("methodValueCall") static function _methodValueCall(): Void;
    @:native("methodValueCallCodePtr") static function _methodValueCallCodePtr(): (go.UIntPtr);
    @:native("moveMakeFuncArgPtrs") static function _moveMakeFuncArgPtrs(ctxt: go.Pointer<go.reflect.MakeFuncCtxt>, args: go.Pointer<go.internal.abi.RegArgs>): Void;
    @:native("nameFor") static function _nameFor(t: go.Pointer<go.internal.abi.Type>): (String);
    @:native("nameOffFor") static function _nameOffFor(t: go.Pointer<go.internal.abi.Type>, off: go.reflect.ANameOff): (go.internal.abi.Name);
    @:native("needKeyUpdate") static function _needKeyUpdate(t: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("newAbiDesc") static function _newAbiDesc(t: go.Pointer<go.reflect.FuncType>, rcvr: go.Pointer<go.internal.abi.Type>): (go.reflect.AbiDesc);
    @:native("newName") static function _newName(n: String, tag: String, exported: Bool, embedded: Bool): (go.internal.abi.Name);
    @:native("overflowFloat32") static function _overflowFloat32(x: Float): (Bool);
    @:native("packEface") static function _packEface(v: go.reflect.Value): (Dynamic);
    @:native("packEfaceData") static function _packEfaceData(v: go.reflect.Value): (go.unsafe.Pointer);
    @:native("packIfaceValueIntoEmptyIface") static function _packIfaceValueIntoEmptyIface(v: go.reflect.Value): (Dynamic);
    @:native("pkgPath") static function _pkgPath(n: go.internal.abi.Name): (String);
    @:native("pkgPathFor") static function _pkgPathFor(t: go.Pointer<go.internal.abi.Type>): (String);
    @:native("ptrTo") static function _ptrTo(t: go.Pointer<go.internal.abi.Type>): (go.Pointer<go.internal.abi.Type>);
    @:native("rangeNum") static function _rangeNum<T: Dynamic, N: Dynamic>(num: N, t: go.reflect.Type): (go.iter.Seq<go.reflect.Value>);
    @:native("resolveNameOff") static function _resolveNameOff(ptrInModule: go.unsafe.Pointer, off: go.Int32): (go.unsafe.Pointer);
    @:native("resolveReflectName") static function _resolveReflectName(n: go.internal.abi.Name): (go.reflect.ANameOff);
    @:native("resolveReflectText") static function _resolveReflectText(ptr: go.unsafe.Pointer): (go.reflect.ATextOff);
    @:native("resolveReflectType") static function _resolveReflectType(t: go.Pointer<go.internal.abi.Type>): (go.reflect.ATypeOff);
    @:native("resolveTextOff") static function _resolveTextOff(rtype: go.unsafe.Pointer, off: go.Int32): (go.unsafe.Pointer);
    @:native("resolveTypeOff") static function _resolveTypeOff(rtype: go.unsafe.Pointer, off: go.Int32): (go.unsafe.Pointer);
    @:go.Tuple("chosen", "recvOK") @:native("rselect") static function _rselect(p0: go.Slice<go.reflect.RuntimeSelect>): go.Tuple<{ chosen: go.GoInt, recvOK: Bool }>;
    @:native("rtypeOf") static function _rtypeOf(i: Dynamic): (go.Pointer<go.internal.abi.Type>);
    @:native("rtypeOff") static function _rtypeOff(section: go.unsafe.Pointer, off: go.Int32): (go.Pointer<go.internal.abi.Type>);
    @:go.Tuple("p0", "p1") @:native("runtimeStructField") static function _runtimeStructField(field: go.reflect.StructField): go.Tuple<{ p0: go.reflect.StructField, p1: String }>;
    @:native("specialChannelAssignability") static function _specialChannelAssignability(T: go.Pointer<go.internal.abi.Type>, V: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("storeRcvr") static function _storeRcvr(v: go.reflect.Value, p: go.unsafe.Pointer): Void;
    @:native("stringFor") static function _stringFor(t: go.Pointer<go.internal.abi.Type>): (String);
    @:native("textOffFor") static function _textOffFor(t: go.Pointer<go.internal.abi.Type>, off: go.reflect.ATextOff): (go.unsafe.Pointer);
    @:native("toRType") static function _toRType(t: go.Pointer<go.internal.abi.Type>): (go.Pointer<go.reflect.Rtype>);
    @:native("toType") static function _toType(t: go.Pointer<go.internal.abi.Type>): (go.reflect.Type);
    @:native("typeOffFor") static function _typeOffFor(t: go.Pointer<go.internal.abi.Type>, off: go.reflect.ATypeOff): (go.Pointer<go.internal.abi.Type>);
    @:native("typedarrayclear") static function _typedarrayclear(elemType: go.Pointer<go.internal.abi.Type>, ptr: go.unsafe.Pointer, len: go.GoInt): Void;
    @:native("typedmemclr") static function _typedmemclr(t: go.Pointer<go.internal.abi.Type>, ptr: go.unsafe.Pointer): Void;
    @:native("typedmemclrpartial") static function _typedmemclrpartial(t: go.Pointer<go.internal.abi.Type>, ptr: go.unsafe.Pointer, off: go.UIntPtr, size: go.UIntPtr): Void;
    @:native("typedmemmove") static function _typedmemmove(t: go.Pointer<go.internal.abi.Type>, dst: go.unsafe.Pointer, src: go.unsafe.Pointer): Void;
    @:native("typedslicecopy") static function _typedslicecopy(t: go.Pointer<go.internal.abi.Type>, dst: go.internal.unsafeheader.Slice, src: go.internal.unsafeheader.Slice): (go.GoInt);
    @:native("typehash") static function _typehash(t: go.Pointer<go.internal.abi.Type>, p: go.unsafe.Pointer, h: go.UIntPtr): (go.UIntPtr);
    @:go.Tuple("sections", "offset") @:native("typelinks") static function _typelinks(): go.Tuple<{ sections: go.Slice<go.unsafe.Pointer>, offset: go.Slice<go.Slice<go.Int32>> }>;
    @:native("typeptrdata") static function _typeptrdata(t: go.Pointer<go.internal.abi.Type>): (go.UIntPtr);
    @:native("typesByString") static function _typesByString(s: String): (go.Slice<go.Pointer<go.internal.abi.Type>>);
    @:native("typesMustMatch") static function _typesMustMatch(what: String, t1: go.reflect.Type, t2: go.reflect.Type): Void;
    @:native("unpackEface") static function _unpackEface(i: Dynamic): (go.reflect.Value);
    @:native("unsafe_New") static function _unsafe_New(p0: go.Pointer<go.internal.abi.Type>): (go.unsafe.Pointer);
    @:native("unsafe_NewArray") static function _unsafe_NewArray(p0: go.Pointer<go.internal.abi.Type>, p1: go.GoInt): (go.unsafe.Pointer);
    @:native("unsafeslice") static function _unsafeslice(t: go.Pointer<go.internal.abi.Type>, ptr: go.unsafe.Pointer, len: go.GoInt): Void;
    @:native("unusedIfaceIndir") static function _unusedIfaceIndir(t: go.Pointer<go.internal.abi.Type>): (Bool);
    @:native("valueInterface") static function _valueInterface(v: go.reflect.Value, safe: Bool): (Dynamic);
    @:native("valueMethodName") static function _valueMethodName(): (String);
    @:native("verifyNotInHeapPtr") static function _verifyNotInHeapPtr(p: go.UIntPtr): (Bool);

}