package go;

@:go.Type({ name: "unicode", instanceName: "unicode.unicode", imports: ["unicode"] })
extern class Unicode {

    @:native("LowerCase") static var LowerCase: go.GoInt;
    @:native("MaxASCII") static var MaxASCII: go.Rune;
    @:native("MaxCase") static var MaxCase: go.GoInt;
    @:native("MaxLatin1") static var MaxLatin1: go.Rune;
    @:native("MaxRune") static var MaxRune: go.Rune;
    @:native("ReplacementChar") static var ReplacementChar: go.Rune;
    @:native("TitleCase") static var TitleCase: go.GoInt;
    @:native("UpperCase") static var UpperCase: go.GoInt;
    @:native("UpperLower") static var UpperLower: go.Rune;
    @:native("Version") static var Version: String;

    @:native("ASCII_Hex_Digit") static var aSCII_Hex_Digit: go.Pointer<go.unicode.RangeTable>;
    @:native("Adlam") static var adlam: go.Pointer<go.unicode.RangeTable>;
    @:native("Ahom") static var ahom: go.Pointer<go.unicode.RangeTable>;
    @:native("Anatolian_Hieroglyphs") static var anatolian_Hieroglyphs: go.Pointer<go.unicode.RangeTable>;
    @:native("Arabic") static var arabic: go.Pointer<go.unicode.RangeTable>;
    @:native("Armenian") static var armenian: go.Pointer<go.unicode.RangeTable>;
    @:native("Avestan") static var avestan: go.Pointer<go.unicode.RangeTable>;
    @:native("AzeriCase") static var azeriCase: go.unicode.SpecialCase;
    @:native("Balinese") static var balinese: go.Pointer<go.unicode.RangeTable>;
    @:native("Bamum") static var bamum: go.Pointer<go.unicode.RangeTable>;
    @:native("Bassa_Vah") static var bassa_Vah: go.Pointer<go.unicode.RangeTable>;
    @:native("Batak") static var batak: go.Pointer<go.unicode.RangeTable>;
    @:native("Bengali") static var bengali: go.Pointer<go.unicode.RangeTable>;
    @:native("Bhaiksuki") static var bhaiksuki: go.Pointer<go.unicode.RangeTable>;
    @:native("Bidi_Control") static var bidi_Control: go.Pointer<go.unicode.RangeTable>;
    @:native("Bopomofo") static var bopomofo: go.Pointer<go.unicode.RangeTable>;
    @:native("Brahmi") static var brahmi: go.Pointer<go.unicode.RangeTable>;
    @:native("Braille") static var braille: go.Pointer<go.unicode.RangeTable>;
    @:native("Buginese") static var buginese: go.Pointer<go.unicode.RangeTable>;
    @:native("Buhid") static var buhid: go.Pointer<go.unicode.RangeTable>;
    @:native("C") static var C: go.Pointer<go.unicode.RangeTable>;
    @:native("Canadian_Aboriginal") static var canadian_Aboriginal: go.Pointer<go.unicode.RangeTable>;
    @:native("Carian") static var carian: go.Pointer<go.unicode.RangeTable>;
    @:native("CaseRanges") static var caseRanges: go.Slice<go.unicode.CaseRange>;
    @:native("Categories") static var categories: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("CategoryAliases") static var categoryAliases: go.Map<String, String>;
    @:native("Caucasian_Albanian") static var caucasian_Albanian: go.Pointer<go.unicode.RangeTable>;
    @:native("Cc") static var cc: go.Pointer<go.unicode.RangeTable>;
    @:native("Cf") static var cf: go.Pointer<go.unicode.RangeTable>;
    @:native("Chakma") static var chakma: go.Pointer<go.unicode.RangeTable>;
    @:native("Cham") static var cham: go.Pointer<go.unicode.RangeTable>;
    @:native("Cherokee") static var cherokee: go.Pointer<go.unicode.RangeTable>;
    @:native("Chorasmian") static var chorasmian: go.Pointer<go.unicode.RangeTable>;
    @:native("Cn") static var cn: go.Pointer<go.unicode.RangeTable>;
    @:native("Co") static var co: go.Pointer<go.unicode.RangeTable>;
    @:native("Common") static var common: go.Pointer<go.unicode.RangeTable>;
    @:native("Coptic") static var coptic: go.Pointer<go.unicode.RangeTable>;
    @:native("Cs") static var cs: go.Pointer<go.unicode.RangeTable>;
    @:native("Cuneiform") static var cuneiform: go.Pointer<go.unicode.RangeTable>;
    @:native("Cypriot") static var cypriot: go.Pointer<go.unicode.RangeTable>;
    @:native("Cypro_Minoan") static var cypro_Minoan: go.Pointer<go.unicode.RangeTable>;
    @:native("Cyrillic") static var cyrillic: go.Pointer<go.unicode.RangeTable>;
    @:native("Dash") static var dash: go.Pointer<go.unicode.RangeTable>;
    @:native("Deprecated") static var deprecated: go.Pointer<go.unicode.RangeTable>;
    @:native("Deseret") static var deseret: go.Pointer<go.unicode.RangeTable>;
    @:native("Devanagari") static var devanagari: go.Pointer<go.unicode.RangeTable>;
    @:native("Diacritic") static var diacritic: go.Pointer<go.unicode.RangeTable>;
    @:native("Digit") static var digit: go.Pointer<go.unicode.RangeTable>;
    @:native("Dives_Akuru") static var dives_Akuru: go.Pointer<go.unicode.RangeTable>;
    @:native("Dogra") static var dogra: go.Pointer<go.unicode.RangeTable>;
    @:native("Duployan") static var duployan: go.Pointer<go.unicode.RangeTable>;
    @:native("Egyptian_Hieroglyphs") static var egyptian_Hieroglyphs: go.Pointer<go.unicode.RangeTable>;
    @:native("Elbasan") static var elbasan: go.Pointer<go.unicode.RangeTable>;
    @:native("Elymaic") static var elymaic: go.Pointer<go.unicode.RangeTable>;
    @:native("Ethiopic") static var ethiopic: go.Pointer<go.unicode.RangeTable>;
    @:native("Extender") static var extender: go.Pointer<go.unicode.RangeTable>;
    @:native("FoldCategory") static var foldCategory: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("FoldScript") static var foldScript: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("Georgian") static var georgian: go.Pointer<go.unicode.RangeTable>;
    @:native("Glagolitic") static var glagolitic: go.Pointer<go.unicode.RangeTable>;
    @:native("Gothic") static var gothic: go.Pointer<go.unicode.RangeTable>;
    @:native("Grantha") static var grantha: go.Pointer<go.unicode.RangeTable>;
    @:native("GraphicRanges") static var graphicRanges: go.Slice<go.Pointer<go.unicode.RangeTable>>;
    @:native("Greek") static var greek: go.Pointer<go.unicode.RangeTable>;
    @:native("Gujarati") static var gujarati: go.Pointer<go.unicode.RangeTable>;
    @:native("Gunjala_Gondi") static var gunjala_Gondi: go.Pointer<go.unicode.RangeTable>;
    @:native("Gurmukhi") static var gurmukhi: go.Pointer<go.unicode.RangeTable>;
    @:native("Han") static var han: go.Pointer<go.unicode.RangeTable>;
    @:native("Hangul") static var hangul: go.Pointer<go.unicode.RangeTable>;
    @:native("Hanifi_Rohingya") static var hanifi_Rohingya: go.Pointer<go.unicode.RangeTable>;
    @:native("Hanunoo") static var hanunoo: go.Pointer<go.unicode.RangeTable>;
    @:native("Hatran") static var hatran: go.Pointer<go.unicode.RangeTable>;
    @:native("Hebrew") static var hebrew: go.Pointer<go.unicode.RangeTable>;
    @:native("Hex_Digit") static var hex_Digit: go.Pointer<go.unicode.RangeTable>;
    @:native("Hiragana") static var hiragana: go.Pointer<go.unicode.RangeTable>;
    @:native("Hyphen") static var hyphen: go.Pointer<go.unicode.RangeTable>;
    @:native("IDS_Binary_Operator") static var iDS_Binary_Operator: go.Pointer<go.unicode.RangeTable>;
    @:native("IDS_Trinary_Operator") static var iDS_Trinary_Operator: go.Pointer<go.unicode.RangeTable>;
    @:native("Ideographic") static var ideographic: go.Pointer<go.unicode.RangeTable>;
    @:native("Imperial_Aramaic") static var imperial_Aramaic: go.Pointer<go.unicode.RangeTable>;
    @:native("Inherited") static var inherited: go.Pointer<go.unicode.RangeTable>;
    @:native("Inscriptional_Pahlavi") static var inscriptional_Pahlavi: go.Pointer<go.unicode.RangeTable>;
    @:native("Inscriptional_Parthian") static var inscriptional_Parthian: go.Pointer<go.unicode.RangeTable>;
    @:native("Javanese") static var javanese: go.Pointer<go.unicode.RangeTable>;
    @:native("Join_Control") static var join_Control: go.Pointer<go.unicode.RangeTable>;
    @:native("Kaithi") static var kaithi: go.Pointer<go.unicode.RangeTable>;
    @:native("Kannada") static var kannada: go.Pointer<go.unicode.RangeTable>;
    @:native("Katakana") static var katakana: go.Pointer<go.unicode.RangeTable>;
    @:native("Kawi") static var kawi: go.Pointer<go.unicode.RangeTable>;
    @:native("Kayah_Li") static var kayah_Li: go.Pointer<go.unicode.RangeTable>;
    @:native("Kharoshthi") static var kharoshthi: go.Pointer<go.unicode.RangeTable>;
    @:native("Khitan_Small_Script") static var khitan_Small_Script: go.Pointer<go.unicode.RangeTable>;
    @:native("Khmer") static var khmer: go.Pointer<go.unicode.RangeTable>;
    @:native("Khojki") static var khojki: go.Pointer<go.unicode.RangeTable>;
    @:native("Khudawadi") static var khudawadi: go.Pointer<go.unicode.RangeTable>;
    @:native("L") static var L: go.Pointer<go.unicode.RangeTable>;
    @:native("LC") static var LC: go.Pointer<go.unicode.RangeTable>;
    @:native("Lao") static var lao: go.Pointer<go.unicode.RangeTable>;
    @:native("Latin") static var latin: go.Pointer<go.unicode.RangeTable>;
    @:native("Lepcha") static var lepcha: go.Pointer<go.unicode.RangeTable>;
    @:native("Letter") static var letter: go.Pointer<go.unicode.RangeTable>;
    @:native("Limbu") static var limbu: go.Pointer<go.unicode.RangeTable>;
    @:native("Linear_A") static var linear_A: go.Pointer<go.unicode.RangeTable>;
    @:native("Linear_B") static var linear_B: go.Pointer<go.unicode.RangeTable>;
    @:native("Lisu") static var lisu: go.Pointer<go.unicode.RangeTable>;
    @:native("Ll") static var ll: go.Pointer<go.unicode.RangeTable>;
    @:native("Lm") static var lm: go.Pointer<go.unicode.RangeTable>;
    @:native("Lo") static var lo: go.Pointer<go.unicode.RangeTable>;
    @:native("Logical_Order_Exception") static var logical_Order_Exception: go.Pointer<go.unicode.RangeTable>;
    @:native("Lower") static var lower: go.Pointer<go.unicode.RangeTable>;
    @:native("Lt") static var lt: go.Pointer<go.unicode.RangeTable>;
    @:native("Lu") static var lu: go.Pointer<go.unicode.RangeTable>;
    @:native("Lycian") static var lycian: go.Pointer<go.unicode.RangeTable>;
    @:native("Lydian") static var lydian: go.Pointer<go.unicode.RangeTable>;
    @:native("M") static var M: go.Pointer<go.unicode.RangeTable>;
    @:native("Mahajani") static var mahajani: go.Pointer<go.unicode.RangeTable>;
    @:native("Makasar") static var makasar: go.Pointer<go.unicode.RangeTable>;
    @:native("Malayalam") static var malayalam: go.Pointer<go.unicode.RangeTable>;
    @:native("Mandaic") static var mandaic: go.Pointer<go.unicode.RangeTable>;
    @:native("Manichaean") static var manichaean: go.Pointer<go.unicode.RangeTable>;
    @:native("Marchen") static var marchen: go.Pointer<go.unicode.RangeTable>;
    @:native("Mark") static var mark: go.Pointer<go.unicode.RangeTable>;
    @:native("Masaram_Gondi") static var masaram_Gondi: go.Pointer<go.unicode.RangeTable>;
    @:native("Mc") static var mc: go.Pointer<go.unicode.RangeTable>;
    @:native("Me") static var me: go.Pointer<go.unicode.RangeTable>;
    @:native("Medefaidrin") static var medefaidrin: go.Pointer<go.unicode.RangeTable>;
    @:native("Meetei_Mayek") static var meetei_Mayek: go.Pointer<go.unicode.RangeTable>;
    @:native("Mende_Kikakui") static var mende_Kikakui: go.Pointer<go.unicode.RangeTable>;
    @:native("Meroitic_Cursive") static var meroitic_Cursive: go.Pointer<go.unicode.RangeTable>;
    @:native("Meroitic_Hieroglyphs") static var meroitic_Hieroglyphs: go.Pointer<go.unicode.RangeTable>;
    @:native("Miao") static var miao: go.Pointer<go.unicode.RangeTable>;
    @:native("Mn") static var mn: go.Pointer<go.unicode.RangeTable>;
    @:native("Modi") static var modi: go.Pointer<go.unicode.RangeTable>;
    @:native("Mongolian") static var mongolian: go.Pointer<go.unicode.RangeTable>;
    @:native("Mro") static var mro: go.Pointer<go.unicode.RangeTable>;
    @:native("Multani") static var multani: go.Pointer<go.unicode.RangeTable>;
    @:native("Myanmar") static var myanmar: go.Pointer<go.unicode.RangeTable>;
    @:native("N") static var N: go.Pointer<go.unicode.RangeTable>;
    @:native("Nabataean") static var nabataean: go.Pointer<go.unicode.RangeTable>;
    @:native("Nag_Mundari") static var nag_Mundari: go.Pointer<go.unicode.RangeTable>;
    @:native("Nandinagari") static var nandinagari: go.Pointer<go.unicode.RangeTable>;
    @:native("Nd") static var nd: go.Pointer<go.unicode.RangeTable>;
    @:native("New_Tai_Lue") static var new_Tai_Lue: go.Pointer<go.unicode.RangeTable>;
    @:native("Newa") static var newa: go.Pointer<go.unicode.RangeTable>;
    @:native("Nko") static var nko: go.Pointer<go.unicode.RangeTable>;
    @:native("Nl") static var nl: go.Pointer<go.unicode.RangeTable>;
    @:native("No") static var no: go.Pointer<go.unicode.RangeTable>;
    @:native("Noncharacter_Code_Point") static var noncharacter_Code_Point: go.Pointer<go.unicode.RangeTable>;
    @:native("Number") static var number: go.Pointer<go.unicode.RangeTable>;
    @:native("Nushu") static var nushu: go.Pointer<go.unicode.RangeTable>;
    @:native("Nyiakeng_Puachue_Hmong") static var nyiakeng_Puachue_Hmong: go.Pointer<go.unicode.RangeTable>;
    @:native("Ogham") static var ogham: go.Pointer<go.unicode.RangeTable>;
    @:native("Ol_Chiki") static var ol_Chiki: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Hungarian") static var old_Hungarian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Italic") static var old_Italic: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_North_Arabian") static var old_North_Arabian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Permic") static var old_Permic: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Persian") static var old_Persian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Sogdian") static var old_Sogdian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_South_Arabian") static var old_South_Arabian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Turkic") static var old_Turkic: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Uyghur") static var old_Uyghur: go.Pointer<go.unicode.RangeTable>;
    @:native("Oriya") static var oriya: go.Pointer<go.unicode.RangeTable>;
    @:native("Osage") static var osage: go.Pointer<go.unicode.RangeTable>;
    @:native("Osmanya") static var osmanya: go.Pointer<go.unicode.RangeTable>;
    @:native("Other") static var other: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Alphabetic") static var other_Alphabetic: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Default_Ignorable_Code_Point") static var other_Default_Ignorable_Code_Point: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Grapheme_Extend") static var other_Grapheme_Extend: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_ID_Continue") static var other_ID_Continue: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_ID_Start") static var other_ID_Start: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Lowercase") static var other_Lowercase: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Math") static var other_Math: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Uppercase") static var other_Uppercase: go.Pointer<go.unicode.RangeTable>;
    @:native("P") static var P: go.Pointer<go.unicode.RangeTable>;
    @:native("Pahawh_Hmong") static var pahawh_Hmong: go.Pointer<go.unicode.RangeTable>;
    @:native("Palmyrene") static var palmyrene: go.Pointer<go.unicode.RangeTable>;
    @:native("Pattern_Syntax") static var pattern_Syntax: go.Pointer<go.unicode.RangeTable>;
    @:native("Pattern_White_Space") static var pattern_White_Space: go.Pointer<go.unicode.RangeTable>;
    @:native("Pau_Cin_Hau") static var pau_Cin_Hau: go.Pointer<go.unicode.RangeTable>;
    @:native("Pc") static var pc: go.Pointer<go.unicode.RangeTable>;
    @:native("Pd") static var pd: go.Pointer<go.unicode.RangeTable>;
    @:native("Pe") static var pe: go.Pointer<go.unicode.RangeTable>;
    @:native("Pf") static var pf: go.Pointer<go.unicode.RangeTable>;
    @:native("Phags_Pa") static var phags_Pa: go.Pointer<go.unicode.RangeTable>;
    @:native("Phoenician") static var phoenician: go.Pointer<go.unicode.RangeTable>;
    @:native("Pi") static var pi: go.Pointer<go.unicode.RangeTable>;
    @:native("Po") static var po: go.Pointer<go.unicode.RangeTable>;
    @:native("Prepended_Concatenation_Mark") static var prepended_Concatenation_Mark: go.Pointer<go.unicode.RangeTable>;
    @:native("PrintRanges") static var printRanges: go.Slice<go.Pointer<go.unicode.RangeTable>>;
    @:native("Properties") static var properties: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("Ps") static var ps: go.Pointer<go.unicode.RangeTable>;
    @:native("Psalter_Pahlavi") static var psalter_Pahlavi: go.Pointer<go.unicode.RangeTable>;
    @:native("Punct") static var punct: go.Pointer<go.unicode.RangeTable>;
    @:native("Quotation_Mark") static var quotation_Mark: go.Pointer<go.unicode.RangeTable>;
    @:native("Radical") static var radical: go.Pointer<go.unicode.RangeTable>;
    @:native("Regional_Indicator") static var regional_Indicator: go.Pointer<go.unicode.RangeTable>;
    @:native("Rejang") static var rejang: go.Pointer<go.unicode.RangeTable>;
    @:native("Runic") static var runic: go.Pointer<go.unicode.RangeTable>;
    @:native("S") static var S: go.Pointer<go.unicode.RangeTable>;
    @:native("STerm") static var sTerm: go.Pointer<go.unicode.RangeTable>;
    @:native("Samaritan") static var samaritan: go.Pointer<go.unicode.RangeTable>;
    @:native("Saurashtra") static var saurashtra: go.Pointer<go.unicode.RangeTable>;
    @:native("Sc") static var sc: go.Pointer<go.unicode.RangeTable>;
    @:native("Scripts") static var scripts: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("Sentence_Terminal") static var sentence_Terminal: go.Pointer<go.unicode.RangeTable>;
    @:native("Sharada") static var sharada: go.Pointer<go.unicode.RangeTable>;
    @:native("Shavian") static var shavian: go.Pointer<go.unicode.RangeTable>;
    @:native("Siddham") static var siddham: go.Pointer<go.unicode.RangeTable>;
    @:native("SignWriting") static var signWriting: go.Pointer<go.unicode.RangeTable>;
    @:native("Sinhala") static var sinhala: go.Pointer<go.unicode.RangeTable>;
    @:native("Sk") static var sk: go.Pointer<go.unicode.RangeTable>;
    @:native("Sm") static var sm: go.Pointer<go.unicode.RangeTable>;
    @:native("So") static var so: go.Pointer<go.unicode.RangeTable>;
    @:native("Soft_Dotted") static var soft_Dotted: go.Pointer<go.unicode.RangeTable>;
    @:native("Sogdian") static var sogdian: go.Pointer<go.unicode.RangeTable>;
    @:native("Sora_Sompeng") static var sora_Sompeng: go.Pointer<go.unicode.RangeTable>;
    @:native("Soyombo") static var soyombo: go.Pointer<go.unicode.RangeTable>;
    @:native("Space") static var space: go.Pointer<go.unicode.RangeTable>;
    @:native("Sundanese") static var sundanese: go.Pointer<go.unicode.RangeTable>;
    @:native("Syloti_Nagri") static var syloti_Nagri: go.Pointer<go.unicode.RangeTable>;
    @:native("Symbol") static var symbol: go.Pointer<go.unicode.RangeTable>;
    @:native("Syriac") static var syriac: go.Pointer<go.unicode.RangeTable>;
    @:native("Tagalog") static var tagalog: go.Pointer<go.unicode.RangeTable>;
    @:native("Tagbanwa") static var tagbanwa: go.Pointer<go.unicode.RangeTable>;
    @:native("Tai_Le") static var tai_Le: go.Pointer<go.unicode.RangeTable>;
    @:native("Tai_Tham") static var tai_Tham: go.Pointer<go.unicode.RangeTable>;
    @:native("Tai_Viet") static var tai_Viet: go.Pointer<go.unicode.RangeTable>;
    @:native("Takri") static var takri: go.Pointer<go.unicode.RangeTable>;
    @:native("Tamil") static var tamil: go.Pointer<go.unicode.RangeTable>;
    @:native("Tangsa") static var tangsa: go.Pointer<go.unicode.RangeTable>;
    @:native("Tangut") static var tangut: go.Pointer<go.unicode.RangeTable>;
    @:native("Telugu") static var telugu: go.Pointer<go.unicode.RangeTable>;
    @:native("Terminal_Punctuation") static var terminal_Punctuation: go.Pointer<go.unicode.RangeTable>;
    @:native("Thaana") static var thaana: go.Pointer<go.unicode.RangeTable>;
    @:native("Thai") static var thai: go.Pointer<go.unicode.RangeTable>;
    @:native("Tibetan") static var tibetan: go.Pointer<go.unicode.RangeTable>;
    @:native("Tifinagh") static var tifinagh: go.Pointer<go.unicode.RangeTable>;
    @:native("Tirhuta") static var tirhuta: go.Pointer<go.unicode.RangeTable>;
    @:native("Title") static var title: go.Pointer<go.unicode.RangeTable>;
    @:native("Toto") static var toto: go.Pointer<go.unicode.RangeTable>;
    @:native("TurkishCase") static var turkishCase: go.unicode.SpecialCase;
    @:native("Ugaritic") static var ugaritic: go.Pointer<go.unicode.RangeTable>;
    @:native("Unified_Ideograph") static var unified_Ideograph: go.Pointer<go.unicode.RangeTable>;
    @:native("Upper") static var upper: go.Pointer<go.unicode.RangeTable>;
    @:native("Vai") static var vai: go.Pointer<go.unicode.RangeTable>;
    @:native("Variation_Selector") static var variation_Selector: go.Pointer<go.unicode.RangeTable>;
    @:native("Vithkuqi") static var vithkuqi: go.Pointer<go.unicode.RangeTable>;
    @:native("Wancho") static var wancho: go.Pointer<go.unicode.RangeTable>;
    @:native("Warang_Citi") static var warang_Citi: go.Pointer<go.unicode.RangeTable>;
    @:native("White_Space") static var white_Space: go.Pointer<go.unicode.RangeTable>;
    @:native("Yezidi") static var yezidi: go.Pointer<go.unicode.RangeTable>;
    @:native("Yi") static var yi: go.Pointer<go.unicode.RangeTable>;
    @:native("Z") static var Z: go.Pointer<go.unicode.RangeTable>;
    @:native("Zanabazar_Square") static var zanabazar_Square: go.Pointer<go.unicode.RangeTable>;
    @:native("Zl") static var zl: go.Pointer<go.unicode.RangeTable>;
    @:native("Zp") static var zp: go.Pointer<go.unicode.RangeTable>;
    @:native("Zs") static var zs: go.Pointer<go.unicode.RangeTable>;

    @:native("In") static function _in(r: go.Rune, ranges: haxe.Rest<go.Pointer<go.unicode.RangeTable>>): (Bool);
    @:native("Is") static function _is(rangeTab: go.Pointer<go.unicode.RangeTable>, r: go.Rune): (Bool);
    @:native("IsControl") static function isControl(r: go.Rune): (Bool);
    @:native("IsDigit") static function isDigit(r: go.Rune): (Bool);
    @:native("IsGraphic") static function isGraphic(r: go.Rune): (Bool);
    @:native("IsLetter") static function isLetter(r: go.Rune): (Bool);
    @:native("IsLower") static function isLower(r: go.Rune): (Bool);
    @:native("IsMark") static function isMark(r: go.Rune): (Bool);
    @:native("IsNumber") static function isNumber(r: go.Rune): (Bool);
    @:native("IsOneOf") static function isOneOf(ranges: go.Slice<go.Pointer<go.unicode.RangeTable>>, r: go.Rune): (Bool);
    @:native("IsPrint") static function isPrint(r: go.Rune): (Bool);
    @:native("IsPunct") static function isPunct(r: go.Rune): (Bool);
    @:native("IsSpace") static function isSpace(r: go.Rune): (Bool);
    @:native("IsSymbol") static function isSymbol(r: go.Rune): (Bool);
    @:native("IsTitle") static function isTitle(r: go.Rune): (Bool);
    @:native("IsUpper") static function isUpper(r: go.Rune): (Bool);
    @:native("SimpleFold") static function simpleFold(r: go.Rune): (go.Rune);
    @:native("To") static function _to(_case: go.GoInt, r: go.Rune): (go.Rune);
    @:native("ToLower") static function toLower(r: go.Rune): (go.Rune);
    @:native("ToTitle") static function toTitle(r: go.Rune): (go.Rune);
    @:native("ToUpper") static function toUpper(r: go.Rune): (go.Rune);

}