package go;

@:go.Type({ name: "unicode", instanceName: "unicode.unicode", imports: ["unicode"] })
extern class Unicode {

    @:native("LowerCase") static var LowerCase: go.GoInt;
    @:native("MaxASCII") static var MaxASCII: go.Rune;
    @:native("MaxCase") static var MaxCase: go.GoInt;
    @:native("MaxLatin1") static var MaxLatin1: go.Rune;
    @:native("MaxRune") static var MaxRune: go.Rune;
    @:native("ReplacementChar") static var ReplacementChar: go.Rune;
    @:native("TitleCase") static var TitleCase: go.GoInt;
    @:native("UpperCase") static var UpperCase: go.GoInt;
    @:native("UpperLower") static var UpperLower: go.Rune;
    @:native("Version") static var Version: String;

    @:native("ASCII_Hex_Digit") static var ASCII_Hex_Digit: go.Pointer<go.unicode.RangeTable>;
    @:native("Adlam") static var Adlam: go.Pointer<go.unicode.RangeTable>;
    @:native("Ahom") static var Ahom: go.Pointer<go.unicode.RangeTable>;
    @:native("Anatolian_Hieroglyphs") static var Anatolian_Hieroglyphs: go.Pointer<go.unicode.RangeTable>;
    @:native("Arabic") static var Arabic: go.Pointer<go.unicode.RangeTable>;
    @:native("Armenian") static var Armenian: go.Pointer<go.unicode.RangeTable>;
    @:native("Avestan") static var Avestan: go.Pointer<go.unicode.RangeTable>;
    @:native("AzeriCase") static var AzeriCase: go.unicode.SpecialCase;
    @:native("Balinese") static var Balinese: go.Pointer<go.unicode.RangeTable>;
    @:native("Bamum") static var Bamum: go.Pointer<go.unicode.RangeTable>;
    @:native("Bassa_Vah") static var Bassa_Vah: go.Pointer<go.unicode.RangeTable>;
    @:native("Batak") static var Batak: go.Pointer<go.unicode.RangeTable>;
    @:native("Bengali") static var Bengali: go.Pointer<go.unicode.RangeTable>;
    @:native("Bhaiksuki") static var Bhaiksuki: go.Pointer<go.unicode.RangeTable>;
    @:native("Bidi_Control") static var Bidi_Control: go.Pointer<go.unicode.RangeTable>;
    @:native("Bopomofo") static var Bopomofo: go.Pointer<go.unicode.RangeTable>;
    @:native("Brahmi") static var Brahmi: go.Pointer<go.unicode.RangeTable>;
    @:native("Braille") static var Braille: go.Pointer<go.unicode.RangeTable>;
    @:native("Buginese") static var Buginese: go.Pointer<go.unicode.RangeTable>;
    @:native("Buhid") static var Buhid: go.Pointer<go.unicode.RangeTable>;
    @:native("C") static var C: go.Pointer<go.unicode.RangeTable>;
    @:native("Canadian_Aboriginal") static var Canadian_Aboriginal: go.Pointer<go.unicode.RangeTable>;
    @:native("Carian") static var Carian: go.Pointer<go.unicode.RangeTable>;
    @:native("CaseRanges") static var CaseRanges: go.Slice<go.unicode.CaseRange>;
    @:native("Categories") static var Categories: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("CategoryAliases") static var CategoryAliases: go.Map<String, String>;
    @:native("Caucasian_Albanian") static var Caucasian_Albanian: go.Pointer<go.unicode.RangeTable>;
    @:native("Cc") static var Cc: go.Pointer<go.unicode.RangeTable>;
    @:native("Cf") static var Cf: go.Pointer<go.unicode.RangeTable>;
    @:native("Chakma") static var Chakma: go.Pointer<go.unicode.RangeTable>;
    @:native("Cham") static var Cham: go.Pointer<go.unicode.RangeTable>;
    @:native("Cherokee") static var Cherokee: go.Pointer<go.unicode.RangeTable>;
    @:native("Chorasmian") static var Chorasmian: go.Pointer<go.unicode.RangeTable>;
    @:native("Cn") static var Cn: go.Pointer<go.unicode.RangeTable>;
    @:native("Co") static var Co: go.Pointer<go.unicode.RangeTable>;
    @:native("Common") static var Common: go.Pointer<go.unicode.RangeTable>;
    @:native("Coptic") static var Coptic: go.Pointer<go.unicode.RangeTable>;
    @:native("Cs") static var Cs: go.Pointer<go.unicode.RangeTable>;
    @:native("Cuneiform") static var Cuneiform: go.Pointer<go.unicode.RangeTable>;
    @:native("Cypriot") static var Cypriot: go.Pointer<go.unicode.RangeTable>;
    @:native("Cypro_Minoan") static var Cypro_Minoan: go.Pointer<go.unicode.RangeTable>;
    @:native("Cyrillic") static var Cyrillic: go.Pointer<go.unicode.RangeTable>;
    @:native("Dash") static var Dash: go.Pointer<go.unicode.RangeTable>;
    @:native("Deprecated") static var Deprecated: go.Pointer<go.unicode.RangeTable>;
    @:native("Deseret") static var Deseret: go.Pointer<go.unicode.RangeTable>;
    @:native("Devanagari") static var Devanagari: go.Pointer<go.unicode.RangeTable>;
    @:native("Diacritic") static var Diacritic: go.Pointer<go.unicode.RangeTable>;
    @:native("Digit") static var Digit: go.Pointer<go.unicode.RangeTable>;
    @:native("Dives_Akuru") static var Dives_Akuru: go.Pointer<go.unicode.RangeTable>;
    @:native("Dogra") static var Dogra: go.Pointer<go.unicode.RangeTable>;
    @:native("Duployan") static var Duployan: go.Pointer<go.unicode.RangeTable>;
    @:native("Egyptian_Hieroglyphs") static var Egyptian_Hieroglyphs: go.Pointer<go.unicode.RangeTable>;
    @:native("Elbasan") static var Elbasan: go.Pointer<go.unicode.RangeTable>;
    @:native("Elymaic") static var Elymaic: go.Pointer<go.unicode.RangeTable>;
    @:native("Ethiopic") static var Ethiopic: go.Pointer<go.unicode.RangeTable>;
    @:native("Extender") static var Extender: go.Pointer<go.unicode.RangeTable>;
    @:native("FoldCategory") static var FoldCategory: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("FoldScript") static var FoldScript: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("Georgian") static var Georgian: go.Pointer<go.unicode.RangeTable>;
    @:native("Glagolitic") static var Glagolitic: go.Pointer<go.unicode.RangeTable>;
    @:native("Gothic") static var Gothic: go.Pointer<go.unicode.RangeTable>;
    @:native("Grantha") static var Grantha: go.Pointer<go.unicode.RangeTable>;
    @:native("GraphicRanges") static var GraphicRanges: go.Slice<go.Pointer<go.unicode.RangeTable>>;
    @:native("Greek") static var Greek: go.Pointer<go.unicode.RangeTable>;
    @:native("Gujarati") static var Gujarati: go.Pointer<go.unicode.RangeTable>;
    @:native("Gunjala_Gondi") static var Gunjala_Gondi: go.Pointer<go.unicode.RangeTable>;
    @:native("Gurmukhi") static var Gurmukhi: go.Pointer<go.unicode.RangeTable>;
    @:native("Han") static var Han: go.Pointer<go.unicode.RangeTable>;
    @:native("Hangul") static var Hangul: go.Pointer<go.unicode.RangeTable>;
    @:native("Hanifi_Rohingya") static var Hanifi_Rohingya: go.Pointer<go.unicode.RangeTable>;
    @:native("Hanunoo") static var Hanunoo: go.Pointer<go.unicode.RangeTable>;
    @:native("Hatran") static var Hatran: go.Pointer<go.unicode.RangeTable>;
    @:native("Hebrew") static var Hebrew: go.Pointer<go.unicode.RangeTable>;
    @:native("Hex_Digit") static var Hex_Digit: go.Pointer<go.unicode.RangeTable>;
    @:native("Hiragana") static var Hiragana: go.Pointer<go.unicode.RangeTable>;
    @:native("Hyphen") static var Hyphen: go.Pointer<go.unicode.RangeTable>;
    @:native("IDS_Binary_Operator") static var IDS_Binary_Operator: go.Pointer<go.unicode.RangeTable>;
    @:native("IDS_Trinary_Operator") static var IDS_Trinary_Operator: go.Pointer<go.unicode.RangeTable>;
    @:native("Ideographic") static var Ideographic: go.Pointer<go.unicode.RangeTable>;
    @:native("Imperial_Aramaic") static var Imperial_Aramaic: go.Pointer<go.unicode.RangeTable>;
    @:native("Inherited") static var Inherited: go.Pointer<go.unicode.RangeTable>;
    @:native("Inscriptional_Pahlavi") static var Inscriptional_Pahlavi: go.Pointer<go.unicode.RangeTable>;
    @:native("Inscriptional_Parthian") static var Inscriptional_Parthian: go.Pointer<go.unicode.RangeTable>;
    @:native("Javanese") static var Javanese: go.Pointer<go.unicode.RangeTable>;
    @:native("Join_Control") static var Join_Control: go.Pointer<go.unicode.RangeTable>;
    @:native("Kaithi") static var Kaithi: go.Pointer<go.unicode.RangeTable>;
    @:native("Kannada") static var Kannada: go.Pointer<go.unicode.RangeTable>;
    @:native("Katakana") static var Katakana: go.Pointer<go.unicode.RangeTable>;
    @:native("Kawi") static var Kawi: go.Pointer<go.unicode.RangeTable>;
    @:native("Kayah_Li") static var Kayah_Li: go.Pointer<go.unicode.RangeTable>;
    @:native("Kharoshthi") static var Kharoshthi: go.Pointer<go.unicode.RangeTable>;
    @:native("Khitan_Small_Script") static var Khitan_Small_Script: go.Pointer<go.unicode.RangeTable>;
    @:native("Khmer") static var Khmer: go.Pointer<go.unicode.RangeTable>;
    @:native("Khojki") static var Khojki: go.Pointer<go.unicode.RangeTable>;
    @:native("Khudawadi") static var Khudawadi: go.Pointer<go.unicode.RangeTable>;
    @:native("L") static var L: go.Pointer<go.unicode.RangeTable>;
    @:native("LC") static var LC: go.Pointer<go.unicode.RangeTable>;
    @:native("Lao") static var Lao: go.Pointer<go.unicode.RangeTable>;
    @:native("Latin") static var Latin: go.Pointer<go.unicode.RangeTable>;
    @:native("Lepcha") static var Lepcha: go.Pointer<go.unicode.RangeTable>;
    @:native("Letter") static var Letter: go.Pointer<go.unicode.RangeTable>;
    @:native("Limbu") static var Limbu: go.Pointer<go.unicode.RangeTable>;
    @:native("Linear_A") static var Linear_A: go.Pointer<go.unicode.RangeTable>;
    @:native("Linear_B") static var Linear_B: go.Pointer<go.unicode.RangeTable>;
    @:native("Lisu") static var Lisu: go.Pointer<go.unicode.RangeTable>;
    @:native("Ll") static var Ll: go.Pointer<go.unicode.RangeTable>;
    @:native("Lm") static var Lm: go.Pointer<go.unicode.RangeTable>;
    @:native("Lo") static var Lo: go.Pointer<go.unicode.RangeTable>;
    @:native("Logical_Order_Exception") static var Logical_Order_Exception: go.Pointer<go.unicode.RangeTable>;
    @:native("Lower") static var Lower: go.Pointer<go.unicode.RangeTable>;
    @:native("Lt") static var Lt: go.Pointer<go.unicode.RangeTable>;
    @:native("Lu") static var Lu: go.Pointer<go.unicode.RangeTable>;
    @:native("Lycian") static var Lycian: go.Pointer<go.unicode.RangeTable>;
    @:native("Lydian") static var Lydian: go.Pointer<go.unicode.RangeTable>;
    @:native("M") static var M: go.Pointer<go.unicode.RangeTable>;
    @:native("Mahajani") static var Mahajani: go.Pointer<go.unicode.RangeTable>;
    @:native("Makasar") static var Makasar: go.Pointer<go.unicode.RangeTable>;
    @:native("Malayalam") static var Malayalam: go.Pointer<go.unicode.RangeTable>;
    @:native("Mandaic") static var Mandaic: go.Pointer<go.unicode.RangeTable>;
    @:native("Manichaean") static var Manichaean: go.Pointer<go.unicode.RangeTable>;
    @:native("Marchen") static var Marchen: go.Pointer<go.unicode.RangeTable>;
    @:native("Mark") static var Mark: go.Pointer<go.unicode.RangeTable>;
    @:native("Masaram_Gondi") static var Masaram_Gondi: go.Pointer<go.unicode.RangeTable>;
    @:native("Mc") static var Mc: go.Pointer<go.unicode.RangeTable>;
    @:native("Me") static var Me: go.Pointer<go.unicode.RangeTable>;
    @:native("Medefaidrin") static var Medefaidrin: go.Pointer<go.unicode.RangeTable>;
    @:native("Meetei_Mayek") static var Meetei_Mayek: go.Pointer<go.unicode.RangeTable>;
    @:native("Mende_Kikakui") static var Mende_Kikakui: go.Pointer<go.unicode.RangeTable>;
    @:native("Meroitic_Cursive") static var Meroitic_Cursive: go.Pointer<go.unicode.RangeTable>;
    @:native("Meroitic_Hieroglyphs") static var Meroitic_Hieroglyphs: go.Pointer<go.unicode.RangeTable>;
    @:native("Miao") static var Miao: go.Pointer<go.unicode.RangeTable>;
    @:native("Mn") static var Mn: go.Pointer<go.unicode.RangeTable>;
    @:native("Modi") static var Modi: go.Pointer<go.unicode.RangeTable>;
    @:native("Mongolian") static var Mongolian: go.Pointer<go.unicode.RangeTable>;
    @:native("Mro") static var Mro: go.Pointer<go.unicode.RangeTable>;
    @:native("Multani") static var Multani: go.Pointer<go.unicode.RangeTable>;
    @:native("Myanmar") static var Myanmar: go.Pointer<go.unicode.RangeTable>;
    @:native("N") static var N: go.Pointer<go.unicode.RangeTable>;
    @:native("Nabataean") static var Nabataean: go.Pointer<go.unicode.RangeTable>;
    @:native("Nag_Mundari") static var Nag_Mundari: go.Pointer<go.unicode.RangeTable>;
    @:native("Nandinagari") static var Nandinagari: go.Pointer<go.unicode.RangeTable>;
    @:native("Nd") static var Nd: go.Pointer<go.unicode.RangeTable>;
    @:native("New_Tai_Lue") static var New_Tai_Lue: go.Pointer<go.unicode.RangeTable>;
    @:native("Newa") static var Newa: go.Pointer<go.unicode.RangeTable>;
    @:native("Nko") static var Nko: go.Pointer<go.unicode.RangeTable>;
    @:native("Nl") static var Nl: go.Pointer<go.unicode.RangeTable>;
    @:native("No") static var No: go.Pointer<go.unicode.RangeTable>;
    @:native("Noncharacter_Code_Point") static var Noncharacter_Code_Point: go.Pointer<go.unicode.RangeTable>;
    @:native("Number") static var Number: go.Pointer<go.unicode.RangeTable>;
    @:native("Nushu") static var Nushu: go.Pointer<go.unicode.RangeTable>;
    @:native("Nyiakeng_Puachue_Hmong") static var Nyiakeng_Puachue_Hmong: go.Pointer<go.unicode.RangeTable>;
    @:native("Ogham") static var Ogham: go.Pointer<go.unicode.RangeTable>;
    @:native("Ol_Chiki") static var Ol_Chiki: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Hungarian") static var Old_Hungarian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Italic") static var Old_Italic: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_North_Arabian") static var Old_North_Arabian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Permic") static var Old_Permic: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Persian") static var Old_Persian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Sogdian") static var Old_Sogdian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_South_Arabian") static var Old_South_Arabian: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Turkic") static var Old_Turkic: go.Pointer<go.unicode.RangeTable>;
    @:native("Old_Uyghur") static var Old_Uyghur: go.Pointer<go.unicode.RangeTable>;
    @:native("Oriya") static var Oriya: go.Pointer<go.unicode.RangeTable>;
    @:native("Osage") static var Osage: go.Pointer<go.unicode.RangeTable>;
    @:native("Osmanya") static var Osmanya: go.Pointer<go.unicode.RangeTable>;
    @:native("Other") static var Other: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Alphabetic") static var Other_Alphabetic: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Default_Ignorable_Code_Point") static var Other_Default_Ignorable_Code_Point: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Grapheme_Extend") static var Other_Grapheme_Extend: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_ID_Continue") static var Other_ID_Continue: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_ID_Start") static var Other_ID_Start: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Lowercase") static var Other_Lowercase: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Math") static var Other_Math: go.Pointer<go.unicode.RangeTable>;
    @:native("Other_Uppercase") static var Other_Uppercase: go.Pointer<go.unicode.RangeTable>;
    @:native("P") static var P: go.Pointer<go.unicode.RangeTable>;
    @:native("Pahawh_Hmong") static var Pahawh_Hmong: go.Pointer<go.unicode.RangeTable>;
    @:native("Palmyrene") static var Palmyrene: go.Pointer<go.unicode.RangeTable>;
    @:native("Pattern_Syntax") static var Pattern_Syntax: go.Pointer<go.unicode.RangeTable>;
    @:native("Pattern_White_Space") static var Pattern_White_Space: go.Pointer<go.unicode.RangeTable>;
    @:native("Pau_Cin_Hau") static var Pau_Cin_Hau: go.Pointer<go.unicode.RangeTable>;
    @:native("Pc") static var Pc: go.Pointer<go.unicode.RangeTable>;
    @:native("Pd") static var Pd: go.Pointer<go.unicode.RangeTable>;
    @:native("Pe") static var Pe: go.Pointer<go.unicode.RangeTable>;
    @:native("Pf") static var Pf: go.Pointer<go.unicode.RangeTable>;
    @:native("Phags_Pa") static var Phags_Pa: go.Pointer<go.unicode.RangeTable>;
    @:native("Phoenician") static var Phoenician: go.Pointer<go.unicode.RangeTable>;
    @:native("Pi") static var Pi: go.Pointer<go.unicode.RangeTable>;
    @:native("Po") static var Po: go.Pointer<go.unicode.RangeTable>;
    @:native("Prepended_Concatenation_Mark") static var Prepended_Concatenation_Mark: go.Pointer<go.unicode.RangeTable>;
    @:native("PrintRanges") static var PrintRanges: go.Slice<go.Pointer<go.unicode.RangeTable>>;
    @:native("Properties") static var Properties: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("Ps") static var Ps: go.Pointer<go.unicode.RangeTable>;
    @:native("Psalter_Pahlavi") static var Psalter_Pahlavi: go.Pointer<go.unicode.RangeTable>;
    @:native("Punct") static var Punct: go.Pointer<go.unicode.RangeTable>;
    @:native("Quotation_Mark") static var Quotation_Mark: go.Pointer<go.unicode.RangeTable>;
    @:native("Radical") static var Radical: go.Pointer<go.unicode.RangeTable>;
    @:native("Regional_Indicator") static var Regional_Indicator: go.Pointer<go.unicode.RangeTable>;
    @:native("Rejang") static var Rejang: go.Pointer<go.unicode.RangeTable>;
    @:native("Runic") static var Runic: go.Pointer<go.unicode.RangeTable>;
    @:native("S") static var S: go.Pointer<go.unicode.RangeTable>;
    @:native("STerm") static var STerm: go.Pointer<go.unicode.RangeTable>;
    @:native("Samaritan") static var Samaritan: go.Pointer<go.unicode.RangeTable>;
    @:native("Saurashtra") static var Saurashtra: go.Pointer<go.unicode.RangeTable>;
    @:native("Sc") static var Sc: go.Pointer<go.unicode.RangeTable>;
    @:native("Scripts") static var Scripts: go.Map<String, go.Pointer<go.unicode.RangeTable>>;
    @:native("Sentence_Terminal") static var Sentence_Terminal: go.Pointer<go.unicode.RangeTable>;
    @:native("Sharada") static var Sharada: go.Pointer<go.unicode.RangeTable>;
    @:native("Shavian") static var Shavian: go.Pointer<go.unicode.RangeTable>;
    @:native("Siddham") static var Siddham: go.Pointer<go.unicode.RangeTable>;
    @:native("SignWriting") static var SignWriting: go.Pointer<go.unicode.RangeTable>;
    @:native("Sinhala") static var Sinhala: go.Pointer<go.unicode.RangeTable>;
    @:native("Sk") static var Sk: go.Pointer<go.unicode.RangeTable>;
    @:native("Sm") static var Sm: go.Pointer<go.unicode.RangeTable>;
    @:native("So") static var So: go.Pointer<go.unicode.RangeTable>;
    @:native("Soft_Dotted") static var Soft_Dotted: go.Pointer<go.unicode.RangeTable>;
    @:native("Sogdian") static var Sogdian: go.Pointer<go.unicode.RangeTable>;
    @:native("Sora_Sompeng") static var Sora_Sompeng: go.Pointer<go.unicode.RangeTable>;
    @:native("Soyombo") static var Soyombo: go.Pointer<go.unicode.RangeTable>;
    @:native("Space") static var Space: go.Pointer<go.unicode.RangeTable>;
    @:native("Sundanese") static var Sundanese: go.Pointer<go.unicode.RangeTable>;
    @:native("Syloti_Nagri") static var Syloti_Nagri: go.Pointer<go.unicode.RangeTable>;
    @:native("Symbol") static var Symbol: go.Pointer<go.unicode.RangeTable>;
    @:native("Syriac") static var Syriac: go.Pointer<go.unicode.RangeTable>;
    @:native("Tagalog") static var Tagalog: go.Pointer<go.unicode.RangeTable>;
    @:native("Tagbanwa") static var Tagbanwa: go.Pointer<go.unicode.RangeTable>;
    @:native("Tai_Le") static var Tai_Le: go.Pointer<go.unicode.RangeTable>;
    @:native("Tai_Tham") static var Tai_Tham: go.Pointer<go.unicode.RangeTable>;
    @:native("Tai_Viet") static var Tai_Viet: go.Pointer<go.unicode.RangeTable>;
    @:native("Takri") static var Takri: go.Pointer<go.unicode.RangeTable>;
    @:native("Tamil") static var Tamil: go.Pointer<go.unicode.RangeTable>;
    @:native("Tangsa") static var Tangsa: go.Pointer<go.unicode.RangeTable>;
    @:native("Tangut") static var Tangut: go.Pointer<go.unicode.RangeTable>;
    @:native("Telugu") static var Telugu: go.Pointer<go.unicode.RangeTable>;
    @:native("Terminal_Punctuation") static var Terminal_Punctuation: go.Pointer<go.unicode.RangeTable>;
    @:native("Thaana") static var Thaana: go.Pointer<go.unicode.RangeTable>;
    @:native("Thai") static var Thai: go.Pointer<go.unicode.RangeTable>;
    @:native("Tibetan") static var Tibetan: go.Pointer<go.unicode.RangeTable>;
    @:native("Tifinagh") static var Tifinagh: go.Pointer<go.unicode.RangeTable>;
    @:native("Tirhuta") static var Tirhuta: go.Pointer<go.unicode.RangeTable>;
    @:native("Title") static var Title: go.Pointer<go.unicode.RangeTable>;
    @:native("Toto") static var Toto: go.Pointer<go.unicode.RangeTable>;
    @:native("TurkishCase") static var TurkishCase: go.unicode.SpecialCase;
    @:native("Ugaritic") static var Ugaritic: go.Pointer<go.unicode.RangeTable>;
    @:native("Unified_Ideograph") static var Unified_Ideograph: go.Pointer<go.unicode.RangeTable>;
    @:native("Upper") static var Upper: go.Pointer<go.unicode.RangeTable>;
    @:native("Vai") static var Vai: go.Pointer<go.unicode.RangeTable>;
    @:native("Variation_Selector") static var Variation_Selector: go.Pointer<go.unicode.RangeTable>;
    @:native("Vithkuqi") static var Vithkuqi: go.Pointer<go.unicode.RangeTable>;
    @:native("Wancho") static var Wancho: go.Pointer<go.unicode.RangeTable>;
    @:native("Warang_Citi") static var Warang_Citi: go.Pointer<go.unicode.RangeTable>;
    @:native("White_Space") static var White_Space: go.Pointer<go.unicode.RangeTable>;
    @:native("Yezidi") static var Yezidi: go.Pointer<go.unicode.RangeTable>;
    @:native("Yi") static var Yi: go.Pointer<go.unicode.RangeTable>;
    @:native("Z") static var Z: go.Pointer<go.unicode.RangeTable>;
    @:native("Zanabazar_Square") static var Zanabazar_Square: go.Pointer<go.unicode.RangeTable>;
    @:native("Zl") static var Zl: go.Pointer<go.unicode.RangeTable>;
    @:native("Zp") static var Zp: go.Pointer<go.unicode.RangeTable>;
    @:native("Zs") static var Zs: go.Pointer<go.unicode.RangeTable>;

    @:native("In") static function _in(r: go.Rune, ranges: haxe.Rest<go.Pointer<go.unicode.RangeTable>>): Bool;
    @:native("Is") static function _is(rangeTab: go.Pointer<go.unicode.RangeTable>, r: go.Rune): Bool;
    @:native("IsControl") static function isControl(r: go.Rune): Bool;
    @:native("IsDigit") static function isDigit(r: go.Rune): Bool;
    @:native("IsGraphic") static function isGraphic(r: go.Rune): Bool;
    @:native("IsLetter") static function isLetter(r: go.Rune): Bool;
    @:native("IsLower") static function isLower(r: go.Rune): Bool;
    @:native("IsMark") static function isMark(r: go.Rune): Bool;
    @:native("IsNumber") static function isNumber(r: go.Rune): Bool;
    @:native("IsOneOf") static function isOneOf(ranges: go.Slice<go.Pointer<go.unicode.RangeTable>>, r: go.Rune): Bool;
    @:native("IsPrint") static function isPrint(r: go.Rune): Bool;
    @:native("IsPunct") static function isPunct(r: go.Rune): Bool;
    @:native("IsSpace") static function isSpace(r: go.Rune): Bool;
    @:native("IsSymbol") static function isSymbol(r: go.Rune): Bool;
    @:native("IsTitle") static function isTitle(r: go.Rune): Bool;
    @:native("IsUpper") static function isUpper(r: go.Rune): Bool;
    @:native("SimpleFold") static function simpleFold(r: go.Rune): go.Rune;
    @:native("To") static function _to(_case: go.GoInt, r: go.Rune): go.Rune;
    @:native("ToLower") static function toLower(r: go.Rune): go.Rune;
    @:native("ToTitle") static function toTitle(r: go.Rune): go.Rune;
    @:native("ToUpper") static function toUpper(r: go.Rune): go.Rune;

}