package go.math;

/**
    Package rand implements pseudo-random number generators suitable for tasks
    such as simulation, but it should not be used for security-sensitive work.
    
    Random numbers are generated by a [Source], usually wrapped in a [Rand].
    Both types should be used by a single goroutine at a time: sharing among
    multiple goroutines requires some kind of synchronization.
    
    Top-level functions, such as [Float64] and [Int],
    are safe for concurrent use by multiple goroutines.
    
    This package's outputs might be easily predictable regardless of how it's
    seeded. For random numbers suitable for security-sensitive work, see the
    crypto/rand package.
**/
@:go.Type({ name: "rand", instanceName: "rand.rand", imports: ["math/rand"] })
extern class Rand {

    /**
        ExpFloat64 returns an exponentially distributed float64 in the range
        (0, +[math.MaxFloat64]] with an exponential distribution whose rate parameter
        (lambda) is 1 and whose mean is 1/lambda (1) from the default [Source].
        To produce a distribution with a different rate parameter,
        callers can adjust the output using:
        
        	sample = ExpFloat64() / desiredRateParameter
    **/
    @:native("ExpFloat64") static function expFloat64(): (Float);
    /**
        Float32 returns, as a float32, a pseudo-random number in the half-open interval [0.0,1.0)
        from the default [Source].
    **/
    @:native("Float32") static function float32(): (go.Float32);
    /**
        Float64 returns, as a float64, a pseudo-random number in the half-open interval [0.0,1.0)
        from the default [Source].
    **/
    @:native("Float64") static function float64(): (Float);
    /**
        Int returns a non-negative pseudo-random int from the default [Source].
    **/
    @:native("Int") static function int(): (go.GoInt);
    /**
        Int31 returns a non-negative pseudo-random 31-bit integer as an int32
        from the default [Source].
    **/
    @:native("Int31") static function int31(): (go.Int32);
    /**
        Int31n returns, as an int32, a non-negative pseudo-random number in the half-open interval [0,n)
        from the default [Source].
        It panics if n <= 0.
    **/
    @:native("Int31n") static function int31n(n: go.Int32): (go.Int32);
    /**
        Int63 returns a non-negative pseudo-random 63-bit integer as an int64
        from the default [Source].
    **/
    @:native("Int63") static function int63(): (go.Int64);
    /**
        Int63n returns, as an int64, a non-negative pseudo-random number in the half-open interval [0,n)
        from the default [Source].
        It panics if n <= 0.
    **/
    @:native("Int63n") static function int63n(n: go.Int64): (go.Int64);
    /**
        Intn returns, as an int, a non-negative pseudo-random number in the half-open interval [0,n)
        from the default [Source].
        It panics if n <= 0.
    **/
    @:native("Intn") static function intn(n: go.GoInt): (go.GoInt);
    /**
        New returns a new [Rand] that uses random values from src
        to generate other random values.
    **/
    @:native("New") static function _new(src: go.math.rand.Source): (go.Pointer<go.math.rand.Rand>);
    /**
        NewSource returns a new pseudo-random [Source] seeded with the given value.
        Unlike the default [Source] used by top-level functions, this source is not
        safe for concurrent use by multiple goroutines.
        The returned [Source] implements [Source64].
    **/
    @:native("NewSource") static function newSource(seed: go.Int64): (go.math.rand.Source);
    /**
        NewZipf returns a [Zipf] variate generator.
        The generator generates values k ∈ [0, imax]
        such that P(k) is proportional to (v + k) ** (-s).
        Requirements: s > 1 and v >= 1.
    **/
    @:native("NewZipf") static function newZipf(r: go.Pointer<go.math.rand.Rand>, s: Float, v: Float, imax: go.UInt64): (go.Pointer<go.math.rand.Zipf>);
    /**
        NormFloat64 returns a normally distributed float64 in the range
        [-[math.MaxFloat64], +[math.MaxFloat64]] with
        standard normal distribution (mean = 0, stddev = 1)
        from the default [Source].
        To produce a different normal distribution, callers can
        adjust the output using:
        
        	sample = NormFloat64() * desiredStdDev + desiredMean
    **/
    @:native("NormFloat64") static function normFloat64(): (Float);
    /**
        Perm returns, as a slice of n ints, a pseudo-random permutation of the integers
        in the half-open interval [0,n) from the default [Source].
    **/
    @:native("Perm") static function perm(n: go.GoInt): (go.Slice<go.GoInt>);
    /**
        Read generates len(p) random bytes from the default [Source] and
        writes them into p. It always returns len(p) and a nil error.
        Read, unlike the [Rand.Read] method, is safe for concurrent use.
        
        Deprecated: For almost all use cases, [crypto/rand.Read] is more appropriate.
        If a deterministic source is required, use [math/rand/v2.ChaCha8.Read].
    **/
    @:native("Read") static function read(p: go.Slice<go.Byte>): (go.Result<go.GoInt>);
    /**
        Seed uses the provided seed value to initialize the default Source to a
        deterministic state. Seed values that have the same remainder when
        divided by 2³¹-1 generate the same pseudo-random sequence.
        Seed, unlike the [Rand.Seed] method, is safe for concurrent use.
        
        If Seed is not called, the generator is seeded randomly at program startup.
        
        Prior to Go 1.20, the generator was seeded like Seed(1) at program startup.
        To force the old behavior, call Seed(1) at program startup.
        Alternately, set GODEBUG=randautoseed=0 in the environment
        before making any calls to functions in this package.
        
        Deprecated: As of Go 1.20 there is no reason to call Seed with
        a random value. Programs that call Seed with a known value to get
        a specific sequence of results should use New(NewSource(seed)) to
        obtain a local random generator.
        
        As of Go 1.24 [Seed] is a no-op. To restore the previous behavior set
        GODEBUG=randseednop=0.
    **/
    @:native("Seed") static function seed(seed: go.Int64): Void;
    /**
        Shuffle pseudo-randomizes the order of elements using the default [Source].
        n is the number of elements. Shuffle panics if n < 0.
        swap swaps the elements with indexes i and j.
    **/
    @:native("Shuffle") static function shuffle(n: go.GoInt, swap: (i: go.GoInt, j: go.GoInt) -> Void): Void;
    /**
        Uint32 returns a pseudo-random 32-bit value as a uint32
        from the default [Source].
    **/
    @:native("Uint32") static function uint32(): (go.UInt32);
    /**
        Uint64 returns a pseudo-random 64-bit value as a uint64
        from the default [Source].
    **/
    @:native("Uint64") static function uint64(): (go.UInt64);

}