package go.mime;

/**
    Package multipart implements MIME multipart parsing, as defined in RFC
    2046.
    
    The implementation is sufficient for HTTP (RFC 2388) and the multipart
    bodies generated by popular browsers.
    
    # Limits
    
    To protect against malicious inputs, this package sets limits on the size
    of the MIME data it processes.
    
    [Reader.NextPart] and [Reader.NextRawPart] limit the number of headers in a
    part to 10000 and [Reader.ReadForm] limits the total number of headers in all
    FileHeaders to 10000.
    These limits may be adjusted with the GODEBUG=multipartmaxheaders=<values>
    setting.
    
    Reader.ReadForm further limits the number of parts in a form to 1000.
    This limit may be adjusted with the GODEBUG=multipartmaxparts=<value>
    setting.
**/
@:go.Type({ name: "multipart", instanceName: "multipart.multipart", imports: ["mime/multipart"] })
extern class Multipart {

    /**
        FileContentDisposition returns the value of a Content-Disposition header
        with the provided field name and file name.
    **/
    @:native("FileContentDisposition") static function fileContentDisposition(fieldname: String, filename: String): (String);
    /**
        NewReader creates a new multipart [Reader] reading from r using the
        given MIME boundary.
        
        The boundary is usually obtained from the "boundary" parameter of
        the message's "Content-Type" header. Use [mime.ParseMediaType] to
        parse such headers.
    **/
    @:native("NewReader") static function newReader(r: go.io.Reader, boundary: String): (go.Pointer<go.mime.multipart.Reader>);
    /**
        NewWriter returns a new multipart [Writer] with a random boundary,
        writing to w.
    **/
    @:native("NewWriter") static function newWriter(w: go.io.Writer): (go.Pointer<go.mime.multipart.Writer>);

}