package go.go;

@:go.Type({ name: "token", instanceName: "token.token", imports: ["go/token"] })
extern class Token {

    @:native("ADD") static var ADD: go.go.token.Token;
    @:native("ADD_ASSIGN") static var ADD_ASSIGN: go.go.token.Token;
    @:native("AND") static var AND: go.go.token.Token;
    @:native("AND_ASSIGN") static var AND_ASSIGN: go.go.token.Token;
    @:native("AND_NOT") static var AND_NOT: go.go.token.Token;
    @:native("AND_NOT_ASSIGN") static var AND_NOT_ASSIGN: go.go.token.Token;
    @:native("ARROW") static var ARROW: go.go.token.Token;
    @:native("ASSIGN") static var ASSIGN: go.go.token.Token;
    @:native("BREAK") static var BREAK: go.go.token.Token;
    @:native("CASE") static var CASE: go.go.token.Token;
    @:native("CHAN") static var CHAN: go.go.token.Token;
    @:native("CHAR") static var CHAR: go.go.token.Token;
    @:native("COLON") static var COLON: go.go.token.Token;
    @:native("COMMA") static var COMMA: go.go.token.Token;
    @:native("COMMENT") static var COMMENT: go.go.token.Token;
    @:native("CONST") static var CONST: go.go.token.Token;
    @:native("CONTINUE") static var CONTINUE: go.go.token.Token;
    @:native("DEC") static var DEC: go.go.token.Token;
    @:native("DEFAULT") static var DEFAULT: go.go.token.Token;
    @:native("DEFER") static var DEFER: go.go.token.Token;
    @:native("DEFINE") static var DEFINE: go.go.token.Token;
    @:native("ELLIPSIS") static var ELLIPSIS: go.go.token.Token;
    @:native("ELSE") static var ELSE: go.go.token.Token;
    @:native("EOF") static var EOF: go.go.token.Token;
    @:native("EQL") static var EQL: go.go.token.Token;
    @:native("FALLTHROUGH") static var FALLTHROUGH: go.go.token.Token;
    @:native("FLOAT") static var FLOAT: go.go.token.Token;
    @:native("FOR") static var FOR: go.go.token.Token;
    @:native("FUNC") static var FUNC: go.go.token.Token;
    @:native("GEQ") static var GEQ: go.go.token.Token;
    @:native("GO") static var GO: go.go.token.Token;
    @:native("GOTO") static var GOTO: go.go.token.Token;
    @:native("GTR") static var GTR: go.go.token.Token;
    @:native("HighestPrec") static var HighestPrec: go.GoInt;
    @:native("IDENT") static var IDENT: go.go.token.Token;
    @:native("IF") static var IF: go.go.token.Token;
    @:native("ILLEGAL") static var ILLEGAL: go.go.token.Token;
    @:native("IMAG") static var IMAG: go.go.token.Token;
    @:native("IMPORT") static var IMPORT: go.go.token.Token;
    @:native("INC") static var INC: go.go.token.Token;
    @:native("INT") static var INT: go.go.token.Token;
    @:native("INTERFACE") static var INTERFACE: go.go.token.Token;
    @:native("LAND") static var LAND: go.go.token.Token;
    @:native("LBRACE") static var LBRACE: go.go.token.Token;
    @:native("LBRACK") static var LBRACK: go.go.token.Token;
    @:native("LEQ") static var LEQ: go.go.token.Token;
    @:native("LOR") static var LOR: go.go.token.Token;
    @:native("LPAREN") static var LPAREN: go.go.token.Token;
    @:native("LSS") static var LSS: go.go.token.Token;
    @:native("LowestPrec") static var LowestPrec: go.GoInt;
    @:native("MAP") static var MAP: go.go.token.Token;
    @:native("MUL") static var MUL: go.go.token.Token;
    @:native("MUL_ASSIGN") static var MUL_ASSIGN: go.go.token.Token;
    @:native("NEQ") static var NEQ: go.go.token.Token;
    @:native("NOT") static var NOT: go.go.token.Token;
    @:native("NoPos") static var NoPos: go.go.token.Pos;
    @:native("OR") static var OR: go.go.token.Token;
    @:native("OR_ASSIGN") static var OR_ASSIGN: go.go.token.Token;
    @:native("PACKAGE") static var PACKAGE: go.go.token.Token;
    @:native("PERIOD") static var PERIOD: go.go.token.Token;
    @:native("QUO") static var QUO: go.go.token.Token;
    @:native("QUO_ASSIGN") static var QUO_ASSIGN: go.go.token.Token;
    @:native("RANGE") static var RANGE: go.go.token.Token;
    @:native("RBRACE") static var RBRACE: go.go.token.Token;
    @:native("RBRACK") static var RBRACK: go.go.token.Token;
    @:native("REM") static var REM: go.go.token.Token;
    @:native("REM_ASSIGN") static var REM_ASSIGN: go.go.token.Token;
    @:native("RETURN") static var RETURN: go.go.token.Token;
    @:native("RPAREN") static var RPAREN: go.go.token.Token;
    @:native("SELECT") static var SELECT: go.go.token.Token;
    @:native("SEMICOLON") static var SEMICOLON: go.go.token.Token;
    @:native("SHL") static var SHL: go.go.token.Token;
    @:native("SHL_ASSIGN") static var SHL_ASSIGN: go.go.token.Token;
    @:native("SHR") static var SHR: go.go.token.Token;
    @:native("SHR_ASSIGN") static var SHR_ASSIGN: go.go.token.Token;
    @:native("STRING") static var STRING: go.go.token.Token;
    @:native("STRUCT") static var STRUCT: go.go.token.Token;
    @:native("SUB") static var SUB: go.go.token.Token;
    @:native("SUB_ASSIGN") static var SUB_ASSIGN: go.go.token.Token;
    @:native("SWITCH") static var SWITCH: go.go.token.Token;
    @:native("TILDE") static var TILDE: go.go.token.Token;
    @:native("TYPE") static var TYPE: go.go.token.Token;
    @:native("UnaryPrec") static var UnaryPrec: go.GoInt;
    @:native("VAR") static var VAR: go.go.token.Token;
    @:native("XOR") static var XOR: go.go.token.Token;
    @:native("XOR_ASSIGN") static var XOR_ASSIGN: go.go.token.Token;

    @:native("IsExported") static function isExported(name: String): Bool;
    @:native("IsIdentifier") static function isIdentifier(name: String): Bool;
    @:native("IsKeyword") static function isKeyword(name: String): Bool;
    @:native("Lookup") static function lookup(ident: String): go.go.token.Token;
    @:native("NewFileSet") static function newFileSet(): go.Pointer<go.go.token.FileSet>;

}