package go.go;

@:go.Type({ name: "types", instanceName: "types.types", imports: ["go/types"] })
extern class Types {

    @:native("Bool") static var Bool: go.go.types.BasicKind;
    @:native("Byte") static var Byte: go.go.types.BasicKind;
    @:native("Complex128") static var Complex128: go.go.types.BasicKind;
    @:native("Complex64") static var Complex64: go.go.types.BasicKind;
    @:native("FieldVal") static var FieldVal: go.go.types.SelectionKind;
    @:native("FieldVar") static var FieldVar: go.go.types.VarKind;
    @:native("Float32") static var Float32: go.go.types.BasicKind;
    @:native("Float64") static var Float64: go.go.types.BasicKind;
    @:native("Int") static var Int: go.go.types.BasicKind;
    @:native("Int16") static var Int16: go.go.types.BasicKind;
    @:native("Int32") static var Int32: go.go.types.BasicKind;
    @:native("Int64") static var Int64: go.go.types.BasicKind;
    @:native("Int8") static var Int8: go.go.types.BasicKind;
    @:native("Invalid") static var Invalid: go.go.types.BasicKind;
    @:native("IsBoolean") static var IsBoolean: go.go.types.BasicInfo;
    @:native("IsComplex") static var IsComplex: go.go.types.BasicInfo;
    @:native("IsConstType") static var IsConstType: go.go.types.BasicInfo;
    @:native("IsFloat") static var IsFloat: go.go.types.BasicInfo;
    @:native("IsInteger") static var IsInteger: go.go.types.BasicInfo;
    @:native("IsNumeric") static var IsNumeric: go.go.types.BasicInfo;
    @:native("IsOrdered") static var IsOrdered: go.go.types.BasicInfo;
    @:native("IsString") static var IsString: go.go.types.BasicInfo;
    @:native("IsUnsigned") static var IsUnsigned: go.go.types.BasicInfo;
    @:native("IsUntyped") static var IsUntyped: go.go.types.BasicInfo;
    @:native("LocalVar") static var LocalVar: go.go.types.VarKind;
    @:native("MethodExpr") static var MethodExpr: go.go.types.SelectionKind;
    @:native("MethodVal") static var MethodVal: go.go.types.SelectionKind;
    @:native("PackageVar") static var PackageVar: go.go.types.VarKind;
    @:native("ParamVar") static var ParamVar: go.go.types.VarKind;
    @:native("RecvOnly") static var RecvOnly: go.go.types.ChanDir;
    @:native("RecvVar") static var RecvVar: go.go.types.VarKind;
    @:native("ResultVar") static var ResultVar: go.go.types.VarKind;
    @:native("Rune") static var Rune: go.go.types.BasicKind;
    @:native("SendOnly") static var SendOnly: go.go.types.ChanDir;
    @:native("SendRecv") static var SendRecv: go.go.types.ChanDir;
    @:native("String") static var String: go.go.types.BasicKind;
    @:native("Uint") static var Uint: go.go.types.BasicKind;
    @:native("Uint16") static var Uint16: go.go.types.BasicKind;
    @:native("Uint32") static var Uint32: go.go.types.BasicKind;
    @:native("Uint64") static var Uint64: go.go.types.BasicKind;
    @:native("Uint8") static var Uint8: go.go.types.BasicKind;
    @:native("Uintptr") static var Uintptr: go.go.types.BasicKind;
    @:native("UnsafePointer") static var UnsafePointer: go.go.types.BasicKind;
    @:native("UntypedBool") static var UntypedBool: go.go.types.BasicKind;
    @:native("UntypedComplex") static var UntypedComplex: go.go.types.BasicKind;
    @:native("UntypedFloat") static var UntypedFloat: go.go.types.BasicKind;
    @:native("UntypedInt") static var UntypedInt: go.go.types.BasicKind;
    @:native("UntypedNil") static var UntypedNil: go.go.types.BasicKind;
    @:native("UntypedRune") static var UntypedRune: go.go.types.BasicKind;
    @:native("UntypedString") static var UntypedString: go.go.types.BasicKind;

    @:native("Typ") static var typ: go.Slice<go.Pointer<go.go.types.Basic>>;
    @:native("Universe") static var universe: go.Pointer<go.go.types.Scope>;
    @:native("Unsafe") static var unsafe: go.Pointer<go.go.types.Package>;

    @:native("AssertableTo") static function assertableTo(V: go.Pointer<go.go.types.Interface>, T: go.go.types.Type): (Bool);
    @:native("AssignableTo") static function assignableTo(V: go.go.types.Type, T: go.go.types.Type): (Bool);
    @:native("CheckExpr") static function checkExpr(fset: go.Pointer<go.go.token.FileSet>, pkg: go.Pointer<go.go.types.Package>, pos: go.go.token.Pos, expr: go.go.ast.Expr, info: go.Pointer<go.go.types.Info>): (go.Error);
    @:native("Comparable") static function comparable(T: go.go.types.Type): (Bool);
    @:native("ConvertibleTo") static function convertibleTo(V: go.go.types.Type, T: go.go.types.Type): (Bool);
    @:native("DefPredeclaredTestFuncs") static function defPredeclaredTestFuncs(): Void;
    @:native("Default") static function _default(t: go.go.types.Type): (go.go.types.Type);
    @:native("Eval") static function eval(fset: go.Pointer<go.go.token.FileSet>, pkg: go.Pointer<go.go.types.Package>, pos: go.go.token.Pos, expr: String): (go.Result<go.go.types.TypeAndValue>);
    @:native("ExprString") static function exprString(x: go.go.ast.Expr): (String);
    @:native("Id") static function id(pkg: go.Pointer<go.go.types.Package>, name: String): (String);
    @:native("Identical") static function identical(x: go.go.types.Type, y: go.go.types.Type): (Bool);
    @:native("IdenticalIgnoreTags") static function identicalIgnoreTags(x: go.go.types.Type, y: go.go.types.Type): (Bool);
    @:native("Implements") static function _implements(V: go.go.types.Type, T: go.Pointer<go.go.types.Interface>): (Bool);
    @:native("Instantiate") static function instantiate(ctxt: go.Pointer<go.go.types.Context>, orig: go.go.types.Type, targs: go.Slice<go.go.types.Type>, validate: Bool): (go.Result<go.go.types.Type>);
    @:native("IsInterface") static function isInterface(t: go.go.types.Type): (Bool);
    @:go.Tuple("obj", "index", "indirect") @:native("LookupFieldOrMethod") static function lookupFieldOrMethod(T: go.go.types.Type, addressable: Bool, pkg: go.Pointer<go.go.types.Package>, name: String): (go.Tuple<{ obj: go.go.types.Object, index: go.Slice<go.GoInt>, indirect: Bool }>);
    @:go.Tuple("p0", "p1") @:native("LookupSelection") static function lookupSelection(T: go.go.types.Type, addressable: Bool, pkg: go.Pointer<go.go.types.Package>, name: String): (go.Tuple<{ p0: go.go.types.Selection, p1: Bool }>);
    @:go.Tuple("method", "wrongType") @:native("MissingMethod") static function missingMethod(V: go.go.types.Type, T: go.Pointer<go.go.types.Interface>, _static: Bool): (go.Tuple<{ method: go.Pointer<go.go.types.Func>, wrongType: Bool }>);
    @:native("NewAlias") static function newAlias(obj: go.Pointer<go.go.types.TypeName>, rhs: go.go.types.Type): (go.Pointer<go.go.types.Alias>);
    @:native("NewArray") static function newArray(elem: go.go.types.Type, len: go.Int64): (go.Pointer<go.go.types.Array>);
    @:native("NewChan") static function newChan(dir: go.go.types.ChanDir, elem: go.go.types.Type): (go.Pointer<go.go.types.Chan>);
    @:native("NewChecker") static function newChecker(conf: go.Pointer<go.go.types.Config>, fset: go.Pointer<go.go.token.FileSet>, pkg: go.Pointer<go.go.types.Package>, info: go.Pointer<go.go.types.Info>): (go.Pointer<go.go.types.Checker>);
    @:native("NewConst") static function newConst(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String, typ: go.go.types.Type, val: go.go.constant.Value): (go.Pointer<go.go.types.Const>);
    @:native("NewContext") static function newContext(): (go.Pointer<go.go.types.Context>);
    @:native("NewField") static function newField(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String, typ: go.go.types.Type, embedded: Bool): (go.Pointer<go.go.types.Var>);
    @:native("NewFunc") static function newFunc(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String, sig: go.Pointer<go.go.types.Signature>): (go.Pointer<go.go.types.Func>);
    @:native("NewInterface") static function newInterface(methods: go.Slice<go.Pointer<go.go.types.Func>>, embeddeds: go.Slice<go.Pointer<go.go.types.Named>>): (go.Pointer<go.go.types.Interface>);
    @:native("NewInterfaceType") static function newInterfaceType(methods: go.Slice<go.Pointer<go.go.types.Func>>, embeddeds: go.Slice<go.go.types.Type>): (go.Pointer<go.go.types.Interface>);
    @:native("NewLabel") static function newLabel(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String): (go.Pointer<go.go.types.Label>);
    @:native("NewMap") static function newMap(key: go.go.types.Type, elem: go.go.types.Type): (go.Pointer<go.go.types.Map>);
    @:native("NewMethodSet") static function newMethodSet(T: go.go.types.Type): (go.Pointer<go.go.types.MethodSet>);
    @:native("NewNamed") static function newNamed(obj: go.Pointer<go.go.types.TypeName>, underlying: go.go.types.Type, methods: go.Slice<go.Pointer<go.go.types.Func>>): (go.Pointer<go.go.types.Named>);
    @:native("NewPackage") static function newPackage(path: String, name: String): (go.Pointer<go.go.types.Package>);
    @:native("NewParam") static function newParam(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String, typ: go.go.types.Type): (go.Pointer<go.go.types.Var>);
    @:native("NewPkgName") static function newPkgName(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String, imported: go.Pointer<go.go.types.Package>): (go.Pointer<go.go.types.PkgName>);
    @:native("NewPointer") static function newPointer(elem: go.go.types.Type): (go.Pointer<go.go.types.Pointer>);
    @:native("NewScope") static function newScope(parent: go.Pointer<go.go.types.Scope>, pos: go.go.token.Pos, end: go.go.token.Pos, comment: String): (go.Pointer<go.go.types.Scope>);
    @:native("NewSignature") static function newSignature(recv: go.Pointer<go.go.types.Var>, params: go.Pointer<go.go.types.Tuple>, results: go.Pointer<go.go.types.Tuple>, variadic: Bool): (go.Pointer<go.go.types.Signature>);
    @:native("NewSignatureType") static function newSignatureType(recv: go.Pointer<go.go.types.Var>, recvTypeParams: go.Slice<go.Pointer<go.go.types.TypeParam>>, typeParams: go.Slice<go.Pointer<go.go.types.TypeParam>>, params: go.Pointer<go.go.types.Tuple>, results: go.Pointer<go.go.types.Tuple>, variadic: Bool): (go.Pointer<go.go.types.Signature>);
    @:native("NewSlice") static function newSlice(elem: go.go.types.Type): (go.Pointer<go.go.types.Slice>);
    @:native("NewStruct") static function newStruct(fields: go.Slice<go.Pointer<go.go.types.Var>>, tags: go.Slice<String>): (go.Pointer<go.go.types.Struct>);
    @:native("NewTerm") static function newTerm(tilde: Bool, typ: go.go.types.Type): (go.Pointer<go.go.types.Term>);
    @:native("NewTuple") static function newTuple(x: haxe.Rest<go.Pointer<go.go.types.Var>>): (go.Pointer<go.go.types.Tuple>);
    @:native("NewTypeName") static function newTypeName(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String, typ: go.go.types.Type): (go.Pointer<go.go.types.TypeName>);
    @:native("NewTypeParam") static function newTypeParam(obj: go.Pointer<go.go.types.TypeName>, constraint: go.go.types.Type): (go.Pointer<go.go.types.TypeParam>);
    @:native("NewUnion") static function newUnion(terms: go.Slice<go.Pointer<go.go.types.Term>>): (go.Pointer<go.go.types.Union>);
    @:native("NewVar") static function newVar(pos: go.go.token.Pos, pkg: go.Pointer<go.go.types.Package>, name: String, typ: go.go.types.Type): (go.Pointer<go.go.types.Var>);
    @:native("ObjectString") static function objectString(obj: go.go.types.Object, qf: go.go.types.Qualifier): (String);
    @:native("RelativeTo") static function relativeTo(pkg: go.Pointer<go.go.types.Package>): (go.go.types.Qualifier);
    @:native("Satisfies") static function satisfies(V: go.go.types.Type, T: go.Pointer<go.go.types.Interface>): (Bool);
    @:native("SelectionString") static function selectionString(s: go.Pointer<go.go.types.Selection>, qf: go.go.types.Qualifier): (String);
    @:native("SizesFor") static function sizesFor(compiler: String, arch: String): (go.go.types.Sizes);
    @:native("TypeString") static function typeString(typ: go.go.types.Type, qf: go.go.types.Qualifier): (String);
    @:native("Unalias") static function unalias(t: go.go.types.Type): (go.go.types.Type);
    @:native("WriteExpr") static function writeExpr(buf: go.Pointer<go.bytes.Buffer>, x: go.go.ast.Expr): Void;
    @:native("WriteSignature") static function writeSignature(buf: go.Pointer<go.bytes.Buffer>, sig: go.Pointer<go.go.types.Signature>, qf: go.go.types.Qualifier): Void;
    @:native("WriteType") static function writeType(buf: go.Pointer<go.bytes.Buffer>, typ: go.go.types.Type, qf: go.go.types.Qualifier): Void;

}