package hx2go;

class RttiMap {
	static var finished = new sys.thread.Semaphore(0); // released by startBuild when done
	static var fallbackOutputDir:String = "";
	static var fallbackGopackage:String = "";

	static public function awaitBuild() {
		if ( ! finished.tryAcquire(1) ) // try to acquire the semaphore with a timeout in seconds
		{ // timeout occurred, fallback to default Rtti.getRtti()
			writeGoFile(fallbackOutputDir, fallbackGopackage, "");
			Sys.println("Timeout waiting for RttiMap build from XML to finish, fallback to default Rtti.getRtti()");
		}
	}

	static function writeGoFile(outputDir:String, gopackage:String, mapEntries:String) {
		sys.io.File.saveContent(haxe.io.Path.join([outputDir, "rttimap.go"]),
			"// This code was automatically generated by class RttiMap in hx2go; DO NOT EDIT.\n"
			+ "package "
			+ gopackage
			+ "\n\nvar HxRttiMap = map[string]string {\n"
			+ mapEntries
			+ "}\n");
	}

	static public function startThreadedBuild(gopackage:String, inputHxb:String, outputDir:String) {
		fallbackOutputDir = outputDir;
		fallbackGopackage = gopackage;
		sys.thread.Thread.create("RttiMapBuilder", function() {
			//var start = Sys.time();
			var mapEntries = "";

			#if !eval
			var input:String = StringTools.replace(inputHxb, ".hxb", ".xml");
			mapEntries = process(input);
			#end

			writeGoFile(outputDir, gopackage, mapEntries);

			finished.release();
			//var end = Sys.time();
			//Sys.println('RttiMap build took ${Std.string(Math.round((end - start) * 100000) / 100)}ms');
			// results from previous runs: 39.8ms to process 2.2 MB XML file
		});
	}

	#if !eval
	static function process(filePath:String):String {
		var fTup = go.Os.open(filePath);
		if (fTup.tuple().error != null) {
			Sys.println('Using fallback Rtti.getRtti() implementation, as unable to open: $filePath');
			return "";
		}
		var f = fTup.tuple().result;

		var linesChan = new go.Chan<String>(100); // probably maximum size in lines of a class

        // go routine to read lines from the file and put them down the lines channel
		go.Syntax.go(() -> {
			go.Syntax.defer(() -> f.close());
			var scanner = go.Bufio.newReader(f);
			while (true) {
				var tup:go.Result<String, go.Error> = scanner.readString('\n'.code);
				var textLine = tup.tuple().result;
				var err = tup.tuple().error;
				if (err != null) {
					if (textLine.length != 0) {
						linesChan.send(textLine);
					}
					break; // hopefully end of file
				}
				linesChan.send(textLine);
			}
			linesChan.send(null);
		}); // end of go routine

		var classChan = new go.Chan<String>(10); // probably maximum number of classes which need to be processed

        // go routine to detect relevant classes from the lines channel and put them down the class channel
		go.Syntax.go(() -> {
			var classBuffer = new Array<String>();
			var inClass = false;
			var keepClass = false;
			while (true) {
				var line = linesChan.receive();
				if (line == null) {
					break;
				}
				var trimmedLine = go.Strings.trim(line, " \t");
				if (go.Strings.hasPrefix(trimmedLine, "<class ")) {
					inClass = true;
					classBuffer = [];
				}
				if (inClass) {
					classBuffer.push(line);
					if (!keepClass) {
						if (go.Strings.hasPrefix(trimmedLine, "<extends")) {
							keepClass = true;
						} else if (go.Strings.contains(trimmedLine, "<m n=\":rtti\"/>")) {
							keepClass = true;
						}
					}
				}
				if (go.Strings.hasPrefix(trimmedLine, "</class>")) {
					inClass = false;
					if (keepClass) {
						classChan.send(classBuffer.join(""));
					}
					keepClass = false;
				}
			}
			classChan.send(null);
		}); // end of go routine

        // process the classes received from the class channel and write to the output if they are correct 
		var goOutput = go.Bytes.newBuffer([]);
		while (true) {
			var classXML = classChan.receive();
			if (classXML == null) {
				break;
			}
			var cl = readClass(classXML);
			if (cl != null)
				goOutput.writeString("\t" + go.Strconv.quoteToASCII(cl.path) + " : " + go.Strconv.quoteToASCII(classXML) + ",\n");
		}
		return goOutput.string();
	}
	#end

    // reads a class from its XML representation and returns the class information if it has ":rtti" metadata or a superclass, otherwise returns null
	static function readClass(content:String) {
		var xml = Xml.parse(content);
		var cl = xml.firstElement();
		var infos = new haxe.rtti.XmlParser().processElement(cl);
		switch (infos) {
			case TClassdecl(c):
				for (m in c.meta) {
					if (m.name == ":rtti") {
						return c;
					}
				}
				return c.superClass != null ? c : null;
			case _:
		}
		return null;
	}
}
