package go.net;

@:go.Type({ name: "http", instanceName: "http.http", imports: ["net/http"] })
extern class Http {

    @:native("DefaultMaxHeaderBytes") static var defaultMaxHeaderBytes: go.GoInt;
    @:native("DefaultMaxIdleConnsPerHost") static var defaultMaxIdleConnsPerHost: go.GoInt;
    @:native("MethodConnect") static var methodConnect: String;
    @:native("MethodDelete") static var methodDelete: String;
    @:native("MethodGet") static var methodGet: String;
    @:native("MethodHead") static var methodHead: String;
    @:native("MethodOptions") static var methodOptions: String;
    @:native("MethodPatch") static var methodPatch: String;
    @:native("MethodPost") static var methodPost: String;
    @:native("MethodPut") static var methodPut: String;
    @:native("MethodTrace") static var methodTrace: String;
    @:native("SameSiteDefaultMode") static var sameSiteDefaultMode: go.net.http.SameSite;
    @:native("SameSiteLaxMode") static var sameSiteLaxMode: go.net.http.SameSite;
    @:native("SameSiteNoneMode") static var sameSiteNoneMode: go.net.http.SameSite;
    @:native("SameSiteStrictMode") static var sameSiteStrictMode: go.net.http.SameSite;
    @:native("StateActive") static var stateActive: go.net.http.ConnState;
    @:native("StateClosed") static var stateClosed: go.net.http.ConnState;
    @:native("StateHijacked") static var stateHijacked: go.net.http.ConnState;
    @:native("StateIdle") static var stateIdle: go.net.http.ConnState;
    @:native("StateNew") static var stateNew: go.net.http.ConnState;
    @:native("StatusAccepted") static var statusAccepted: go.GoInt;
    @:native("StatusAlreadyReported") static var statusAlreadyReported: go.GoInt;
    @:native("StatusBadGateway") static var statusBadGateway: go.GoInt;
    @:native("StatusBadRequest") static var statusBadRequest: go.GoInt;
    @:native("StatusConflict") static var statusConflict: go.GoInt;
    @:native("StatusContinue") static var statusContinue: go.GoInt;
    @:native("StatusCreated") static var statusCreated: go.GoInt;
    @:native("StatusEarlyHints") static var statusEarlyHints: go.GoInt;
    @:native("StatusExpectationFailed") static var statusExpectationFailed: go.GoInt;
    @:native("StatusFailedDependency") static var statusFailedDependency: go.GoInt;
    @:native("StatusForbidden") static var statusForbidden: go.GoInt;
    @:native("StatusFound") static var statusFound: go.GoInt;
    @:native("StatusGatewayTimeout") static var statusGatewayTimeout: go.GoInt;
    @:native("StatusGone") static var statusGone: go.GoInt;
    @:native("StatusHTTPVersionNotSupported") static var statusHTTPVersionNotSupported: go.GoInt;
    @:native("StatusIMUsed") static var statusIMUsed: go.GoInt;
    @:native("StatusInsufficientStorage") static var statusInsufficientStorage: go.GoInt;
    @:native("StatusInternalServerError") static var statusInternalServerError: go.GoInt;
    @:native("StatusLengthRequired") static var statusLengthRequired: go.GoInt;
    @:native("StatusLocked") static var statusLocked: go.GoInt;
    @:native("StatusLoopDetected") static var statusLoopDetected: go.GoInt;
    @:native("StatusMethodNotAllowed") static var statusMethodNotAllowed: go.GoInt;
    @:native("StatusMisdirectedRequest") static var statusMisdirectedRequest: go.GoInt;
    @:native("StatusMovedPermanently") static var statusMovedPermanently: go.GoInt;
    @:native("StatusMultiStatus") static var statusMultiStatus: go.GoInt;
    @:native("StatusMultipleChoices") static var statusMultipleChoices: go.GoInt;
    @:native("StatusNetworkAuthenticationRequired") static var statusNetworkAuthenticationRequired: go.GoInt;
    @:native("StatusNoContent") static var statusNoContent: go.GoInt;
    @:native("StatusNonAuthoritativeInfo") static var statusNonAuthoritativeInfo: go.GoInt;
    @:native("StatusNotAcceptable") static var statusNotAcceptable: go.GoInt;
    @:native("StatusNotExtended") static var statusNotExtended: go.GoInt;
    @:native("StatusNotFound") static var statusNotFound: go.GoInt;
    @:native("StatusNotImplemented") static var statusNotImplemented: go.GoInt;
    @:native("StatusNotModified") static var statusNotModified: go.GoInt;
    @:native("StatusOK") static var statusOK: go.GoInt;
    @:native("StatusPartialContent") static var statusPartialContent: go.GoInt;
    @:native("StatusPaymentRequired") static var statusPaymentRequired: go.GoInt;
    @:native("StatusPermanentRedirect") static var statusPermanentRedirect: go.GoInt;
    @:native("StatusPreconditionFailed") static var statusPreconditionFailed: go.GoInt;
    @:native("StatusPreconditionRequired") static var statusPreconditionRequired: go.GoInt;
    @:native("StatusProcessing") static var statusProcessing: go.GoInt;
    @:native("StatusProxyAuthRequired") static var statusProxyAuthRequired: go.GoInt;
    @:native("StatusRequestEntityTooLarge") static var statusRequestEntityTooLarge: go.GoInt;
    @:native("StatusRequestHeaderFieldsTooLarge") static var statusRequestHeaderFieldsTooLarge: go.GoInt;
    @:native("StatusRequestTimeout") static var statusRequestTimeout: go.GoInt;
    @:native("StatusRequestURITooLong") static var statusRequestURITooLong: go.GoInt;
    @:native("StatusRequestedRangeNotSatisfiable") static var statusRequestedRangeNotSatisfiable: go.GoInt;
    @:native("StatusResetContent") static var statusResetContent: go.GoInt;
    @:native("StatusSeeOther") static var statusSeeOther: go.GoInt;
    @:native("StatusServiceUnavailable") static var statusServiceUnavailable: go.GoInt;
    @:native("StatusSwitchingProtocols") static var statusSwitchingProtocols: go.GoInt;
    @:native("StatusTeapot") static var statusTeapot: go.GoInt;
    @:native("StatusTemporaryRedirect") static var statusTemporaryRedirect: go.GoInt;
    @:native("StatusTooEarly") static var statusTooEarly: go.GoInt;
    @:native("StatusTooManyRequests") static var statusTooManyRequests: go.GoInt;
    @:native("StatusUnauthorized") static var statusUnauthorized: go.GoInt;
    @:native("StatusUnavailableForLegalReasons") static var statusUnavailableForLegalReasons: go.GoInt;
    @:native("StatusUnprocessableEntity") static var statusUnprocessableEntity: go.GoInt;
    @:native("StatusUnsupportedMediaType") static var statusUnsupportedMediaType: go.GoInt;
    @:native("StatusUpgradeRequired") static var statusUpgradeRequired: go.GoInt;
    @:native("StatusUseProxy") static var statusUseProxy: go.GoInt;
    @:native("StatusVariantAlsoNegotiates") static var statusVariantAlsoNegotiates: go.GoInt;
    @:native("TimeFormat") static var timeFormat: String;
    @:native("TrailerPrefix") static var trailerPrefix: String;

    @:native("DefaultClient") static var defaultClient: go.Pointer<go.net.http.Client>;
    @:native("DefaultServeMux") static var defaultServeMux: go.Pointer<go.net.http.ServeMux>;
    @:native("DefaultTransport") static var defaultTransport: go.net.http.RoundTripper;
    @:native("ErrHeaderTooLong") static var errHeaderTooLong: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrMissingBoundary") static var errMissingBoundary: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrMissingContentLength") static var errMissingContentLength: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrNotMultipart") static var errNotMultipart: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrNotSupported") static var errNotSupported: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrShortBody") static var errShortBody: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrUnexpectedTrailer") static var errUnexpectedTrailer: go.Pointer<go.net.http.ProtocolError>;

    @:native("AllowQuerySemicolons") static function allowQuerySemicolons(h: go.net.http.Handler): (go.net.http.Handler);
    @:native("CanonicalHeaderKey") static function canonicalHeaderKey(s: String): (String);
    @:native("DetectContentType") static function detectContentType(data: go.Slice<go.Byte>): (String);
    @:native("Error") static function error(w: go.net.http.ResponseWriter, error: String, code: go.GoInt): Void;
    @:native("FS") static function FS(fsys: go.io.fs.FS): (go.net.http.FileSystem);
    @:native("FileServer") static function fileServer(root: go.net.http.FileSystem): (go.net.http.Handler);
    @:native("FileServerFS") static function fileServerFS(root: go.io.fs.FS): (go.net.http.Handler);
    @:native("Get") static function get(url: String): (go.Result<go.Pointer<go.net.http.Response>>);
    @:native("Handle") static function handle(pattern: String, handler: go.net.http.Handler): Void;
    @:native("HandleFunc") static function handleFunc(pattern: String, handler: (p0: go.net.http.ResponseWriter, p1: go.Pointer<go.net.http.Request>) -> Void): Void;
    @:native("Head") static function head(url: String): (go.Result<go.Pointer<go.net.http.Response>>);
    @:native("ListenAndServe") static function listenAndServe(addr: String, handler: go.net.http.Handler): (go.Error);
    @:native("ListenAndServeTLS") static function listenAndServeTLS(addr: String, certFile: String, keyFile: String, handler: go.net.http.Handler): (go.Error);
    @:native("MaxBytesHandler") static function maxBytesHandler(h: go.net.http.Handler, n: go.Int64): (go.net.http.Handler);
    @:native("MaxBytesReader") static function maxBytesReader(w: go.net.http.ResponseWriter, r: go.io.ReadCloser, n: go.Int64): (go.io.ReadCloser);
    @:native("NewCrossOriginProtection") static function newCrossOriginProtection(): (go.Pointer<go.net.http.CrossOriginProtection>);
    @:native("NewFileTransport") static function newFileTransport(fs: go.net.http.FileSystem): (go.net.http.RoundTripper);
    @:native("NewFileTransportFS") static function newFileTransportFS(fsys: go.io.fs.FS): (go.net.http.RoundTripper);
    @:native("NewRequest") static function newRequest(method: String, url: String, body: go.io.Reader): (go.Result<go.Pointer<go.net.http.Request>>);
    @:native("NewRequestWithContext") static function newRequestWithContext(ctx: go.context.Context, method: String, url: String, body: go.io.Reader): (go.Result<go.Pointer<go.net.http.Request>>);
    @:native("NewResponseController") static function newResponseController(rw: go.net.http.ResponseWriter): (go.Pointer<go.net.http.ResponseController>);
    @:native("NewServeMux") static function newServeMux(): (go.Pointer<go.net.http.ServeMux>);
    @:native("NotFound") static function notFound(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>): Void;
    @:native("NotFoundHandler") static function notFoundHandler(): (go.net.http.Handler);
    @:native("ParseCookie") static function parseCookie(line: String): (go.Result<go.Slice<go.Pointer<go.net.http.Cookie>>>);
    @:go.Tuple("major", "minor", "ok") @:native("ParseHTTPVersion") static function parseHTTPVersion(vers: String): (go.Tuple<{ major: go.GoInt, minor: go.GoInt, ok: Bool }>);
    @:native("ParseSetCookie") static function parseSetCookie(line: String): (go.Result<go.Pointer<go.net.http.Cookie>>);
    @:native("ParseTime") static function parseTime(text: String): (go.Result<go.time.Time>);
    @:native("Post") static function post(url: String, contentType: String, body: go.io.Reader): (go.Result<go.Pointer<go.net.http.Response>>);
    @:native("PostForm") static function postForm(url: String, data: go.net.url.Values): (go.Result<go.Pointer<go.net.http.Response>>);
    @:native("ProxyFromEnvironment") static function proxyFromEnvironment(req: go.Pointer<go.net.http.Request>): (go.Result<go.Pointer<go.net.url.URL>>);
    @:native("ProxyURL") static function proxyURL(fixedURL: go.Pointer<go.net.url.URL>): ((p0: go.Pointer<go.net.http.Request>) -> (go.Result<go.Pointer<go.net.url.URL>>));
    @:native("ReadRequest") static function readRequest(b: go.Pointer<go.bufio.Reader>): (go.Result<go.Pointer<go.net.http.Request>>);
    @:native("ReadResponse") static function readResponse(r: go.Pointer<go.bufio.Reader>, req: go.Pointer<go.net.http.Request>): (go.Result<go.Pointer<go.net.http.Response>>);
    @:native("Redirect") static function redirect(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>, url: String, code: go.GoInt): Void;
    @:native("RedirectHandler") static function redirectHandler(url: String, code: go.GoInt): (go.net.http.Handler);
    @:native("Serve") static function serve(l: go.net.Listener, handler: go.net.http.Handler): (go.Error);
    @:native("ServeContent") static function serveContent(w: go.net.http.ResponseWriter, req: go.Pointer<go.net.http.Request>, name: String, modtime: go.time.Time, content: go.io.ReadSeeker): Void;
    @:native("ServeFile") static function serveFile(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>, name: String): Void;
    @:native("ServeFileFS") static function serveFileFS(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>, fsys: go.io.fs.FS, name: String): Void;
    @:native("ServeTLS") static function serveTLS(l: go.net.Listener, handler: go.net.http.Handler, certFile: String, keyFile: String): (go.Error);
    @:native("SetCookie") static function setCookie(w: go.net.http.ResponseWriter, cookie: go.Pointer<go.net.http.Cookie>): Void;
    @:native("StatusText") static function statusText(code: go.GoInt): (String);
    @:native("StripPrefix") static function stripPrefix(prefix: String, h: go.net.http.Handler): (go.net.http.Handler);
    @:native("TimeoutHandler") static function timeoutHandler(h: go.net.http.Handler, dt: go.time.Duration, msg: String): (go.net.http.Handler);

}