package go.net;

@:go.Type({ name: "http", instanceName: "http.http", imports: ["net/http"] })
extern class Http {

    @:native("DefaultMaxHeaderBytes") static var DefaultMaxHeaderBytes: go.GoInt;
    @:native("DefaultMaxIdleConnsPerHost") static var DefaultMaxIdleConnsPerHost: go.GoInt;
    @:native("MethodConnect") static var MethodConnect: String;
    @:native("MethodDelete") static var MethodDelete: String;
    @:native("MethodGet") static var MethodGet: String;
    @:native("MethodHead") static var MethodHead: String;
    @:native("MethodOptions") static var MethodOptions: String;
    @:native("MethodPatch") static var MethodPatch: String;
    @:native("MethodPost") static var MethodPost: String;
    @:native("MethodPut") static var MethodPut: String;
    @:native("MethodTrace") static var MethodTrace: String;
    @:native("SameSiteDefaultMode") static var SameSiteDefaultMode: go.net.http.SameSite;
    @:native("SameSiteLaxMode") static var SameSiteLaxMode: go.net.http.SameSite;
    @:native("SameSiteNoneMode") static var SameSiteNoneMode: go.net.http.SameSite;
    @:native("SameSiteStrictMode") static var SameSiteStrictMode: go.net.http.SameSite;
    @:native("StateActive") static var StateActive: go.net.http.ConnState;
    @:native("StateClosed") static var StateClosed: go.net.http.ConnState;
    @:native("StateHijacked") static var StateHijacked: go.net.http.ConnState;
    @:native("StateIdle") static var StateIdle: go.net.http.ConnState;
    @:native("StateNew") static var StateNew: go.net.http.ConnState;
    @:native("StatusAccepted") static var StatusAccepted: go.GoInt;
    @:native("StatusAlreadyReported") static var StatusAlreadyReported: go.GoInt;
    @:native("StatusBadGateway") static var StatusBadGateway: go.GoInt;
    @:native("StatusBadRequest") static var StatusBadRequest: go.GoInt;
    @:native("StatusConflict") static var StatusConflict: go.GoInt;
    @:native("StatusContinue") static var StatusContinue: go.GoInt;
    @:native("StatusCreated") static var StatusCreated: go.GoInt;
    @:native("StatusEarlyHints") static var StatusEarlyHints: go.GoInt;
    @:native("StatusExpectationFailed") static var StatusExpectationFailed: go.GoInt;
    @:native("StatusFailedDependency") static var StatusFailedDependency: go.GoInt;
    @:native("StatusForbidden") static var StatusForbidden: go.GoInt;
    @:native("StatusFound") static var StatusFound: go.GoInt;
    @:native("StatusGatewayTimeout") static var StatusGatewayTimeout: go.GoInt;
    @:native("StatusGone") static var StatusGone: go.GoInt;
    @:native("StatusHTTPVersionNotSupported") static var StatusHTTPVersionNotSupported: go.GoInt;
    @:native("StatusIMUsed") static var StatusIMUsed: go.GoInt;
    @:native("StatusInsufficientStorage") static var StatusInsufficientStorage: go.GoInt;
    @:native("StatusInternalServerError") static var StatusInternalServerError: go.GoInt;
    @:native("StatusLengthRequired") static var StatusLengthRequired: go.GoInt;
    @:native("StatusLocked") static var StatusLocked: go.GoInt;
    @:native("StatusLoopDetected") static var StatusLoopDetected: go.GoInt;
    @:native("StatusMethodNotAllowed") static var StatusMethodNotAllowed: go.GoInt;
    @:native("StatusMisdirectedRequest") static var StatusMisdirectedRequest: go.GoInt;
    @:native("StatusMovedPermanently") static var StatusMovedPermanently: go.GoInt;
    @:native("StatusMultiStatus") static var StatusMultiStatus: go.GoInt;
    @:native("StatusMultipleChoices") static var StatusMultipleChoices: go.GoInt;
    @:native("StatusNetworkAuthenticationRequired") static var StatusNetworkAuthenticationRequired: go.GoInt;
    @:native("StatusNoContent") static var StatusNoContent: go.GoInt;
    @:native("StatusNonAuthoritativeInfo") static var StatusNonAuthoritativeInfo: go.GoInt;
    @:native("StatusNotAcceptable") static var StatusNotAcceptable: go.GoInt;
    @:native("StatusNotExtended") static var StatusNotExtended: go.GoInt;
    @:native("StatusNotFound") static var StatusNotFound: go.GoInt;
    @:native("StatusNotImplemented") static var StatusNotImplemented: go.GoInt;
    @:native("StatusNotModified") static var StatusNotModified: go.GoInt;
    @:native("StatusOK") static var StatusOK: go.GoInt;
    @:native("StatusPartialContent") static var StatusPartialContent: go.GoInt;
    @:native("StatusPaymentRequired") static var StatusPaymentRequired: go.GoInt;
    @:native("StatusPermanentRedirect") static var StatusPermanentRedirect: go.GoInt;
    @:native("StatusPreconditionFailed") static var StatusPreconditionFailed: go.GoInt;
    @:native("StatusPreconditionRequired") static var StatusPreconditionRequired: go.GoInt;
    @:native("StatusProcessing") static var StatusProcessing: go.GoInt;
    @:native("StatusProxyAuthRequired") static var StatusProxyAuthRequired: go.GoInt;
    @:native("StatusRequestEntityTooLarge") static var StatusRequestEntityTooLarge: go.GoInt;
    @:native("StatusRequestHeaderFieldsTooLarge") static var StatusRequestHeaderFieldsTooLarge: go.GoInt;
    @:native("StatusRequestTimeout") static var StatusRequestTimeout: go.GoInt;
    @:native("StatusRequestURITooLong") static var StatusRequestURITooLong: go.GoInt;
    @:native("StatusRequestedRangeNotSatisfiable") static var StatusRequestedRangeNotSatisfiable: go.GoInt;
    @:native("StatusResetContent") static var StatusResetContent: go.GoInt;
    @:native("StatusSeeOther") static var StatusSeeOther: go.GoInt;
    @:native("StatusServiceUnavailable") static var StatusServiceUnavailable: go.GoInt;
    @:native("StatusSwitchingProtocols") static var StatusSwitchingProtocols: go.GoInt;
    @:native("StatusTeapot") static var StatusTeapot: go.GoInt;
    @:native("StatusTemporaryRedirect") static var StatusTemporaryRedirect: go.GoInt;
    @:native("StatusTooEarly") static var StatusTooEarly: go.GoInt;
    @:native("StatusTooManyRequests") static var StatusTooManyRequests: go.GoInt;
    @:native("StatusUnauthorized") static var StatusUnauthorized: go.GoInt;
    @:native("StatusUnavailableForLegalReasons") static var StatusUnavailableForLegalReasons: go.GoInt;
    @:native("StatusUnprocessableEntity") static var StatusUnprocessableEntity: go.GoInt;
    @:native("StatusUnsupportedMediaType") static var StatusUnsupportedMediaType: go.GoInt;
    @:native("StatusUpgradeRequired") static var StatusUpgradeRequired: go.GoInt;
    @:native("StatusUseProxy") static var StatusUseProxy: go.GoInt;
    @:native("StatusVariantAlsoNegotiates") static var StatusVariantAlsoNegotiates: go.GoInt;
    @:native("TimeFormat") static var TimeFormat: String;
    @:native("TrailerPrefix") static var TrailerPrefix: String;

    @:native("DefaultClient") static var DefaultClient: go.Pointer<go.net.http.Client>;
    @:native("DefaultServeMux") static var DefaultServeMux: go.Pointer<go.net.http.ServeMux>;
    @:native("DefaultTransport") static var DefaultTransport: go.net.http.RoundTripper;
    @:native("ErrHeaderTooLong") static var ErrHeaderTooLong: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrMissingBoundary") static var ErrMissingBoundary: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrMissingContentLength") static var ErrMissingContentLength: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrNotMultipart") static var ErrNotMultipart: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrNotSupported") static var ErrNotSupported: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrShortBody") static var ErrShortBody: go.Pointer<go.net.http.ProtocolError>;
    @:native("ErrUnexpectedTrailer") static var ErrUnexpectedTrailer: go.Pointer<go.net.http.ProtocolError>;

    @:native("AllowQuerySemicolons") static function allowQuerySemicolons(h: go.net.http.Handler): go.net.http.Handler;
    @:native("CanonicalHeaderKey") static function canonicalHeaderKey(s: String): String;
    @:native("DetectContentType") static function detectContentType(data: go.Slice<go.Byte>): String;
    @:native("Error") static function error(w: go.net.http.ResponseWriter, error: String, code: go.GoInt): Void;
    @:native("FS") static function FS(fsys: go.io.fs.FS): go.net.http.FileSystem;
    @:native("FileServer") static function fileServer(root: go.net.http.FileSystem): go.net.http.Handler;
    @:native("FileServerFS") static function fileServerFS(root: go.io.fs.FS): go.net.http.Handler;
    @:native("Get") static function get(url: String): go.Result<go.Pointer<go.net.http.Response>>;
    @:native("Handle") static function handle(pattern: String, handler: go.net.http.Handler): Void;
    @:native("HandleFunc") static function handleFunc(pattern: String, handler: (p0: go.net.http.ResponseWriter, p1: go.Pointer<go.net.http.Request>) -> Void): Void;
    @:native("Head") static function head(url: String): go.Result<go.Pointer<go.net.http.Response>>;
    @:native("ListenAndServe") static function listenAndServe(addr: String, handler: go.net.http.Handler): go.Error;
    @:native("ListenAndServeTLS") static function listenAndServeTLS(addr: String, certFile: String, keyFile: String, handler: go.net.http.Handler): go.Error;
    @:native("MaxBytesHandler") static function maxBytesHandler(h: go.net.http.Handler, n: go.Int64): go.net.http.Handler;
    @:native("MaxBytesReader") static function maxBytesReader(w: go.net.http.ResponseWriter, r: go.io.ReadCloser, n: go.Int64): go.io.ReadCloser;
    @:native("NewCrossOriginProtection") static function newCrossOriginProtection(): go.Pointer<go.net.http.CrossOriginProtection>;
    @:native("NewFileTransport") static function newFileTransport(fs: go.net.http.FileSystem): go.net.http.RoundTripper;
    @:native("NewFileTransportFS") static function newFileTransportFS(fsys: go.io.fs.FS): go.net.http.RoundTripper;
    @:native("NewRequest") static function newRequest(method: String, url: String, body: go.io.Reader): go.Result<go.Pointer<go.net.http.Request>>;
    @:native("NewRequestWithContext") static function newRequestWithContext(ctx: go.context.Context, method: String, url: String, body: go.io.Reader): go.Result<go.Pointer<go.net.http.Request>>;
    @:native("NewResponseController") static function newResponseController(rw: go.net.http.ResponseWriter): go.Pointer<go.net.http.ResponseController>;
    @:native("NewServeMux") static function newServeMux(): go.Pointer<go.net.http.ServeMux>;
    @:native("NotFound") static function notFound(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>): Void;
    @:native("NotFoundHandler") static function notFoundHandler(): go.net.http.Handler;
    @:native("ParseCookie") static function parseCookie(line: String): go.Result<go.Slice<go.Pointer<go.net.http.Cookie>>>;
    @:go.Tuple("major", "minor", "ok") @:native("ParseHTTPVersion") static function parseHTTPVersion(vers: String): go.Tuple<{ major: go.GoInt, minor: go.GoInt, ok: Bool }>;
    @:native("ParseSetCookie") static function parseSetCookie(line: String): go.Result<go.Pointer<go.net.http.Cookie>>;
    @:native("ParseTime") static function parseTime(text: String): go.Result<go.time.Time>;
    @:native("Post") static function post(url: String, contentType: String, body: go.io.Reader): go.Result<go.Pointer<go.net.http.Response>>;
    @:native("PostForm") static function postForm(url: String, data: go.net.url.Values): go.Result<go.Pointer<go.net.http.Response>>;
    @:native("ProxyFromEnvironment") static function proxyFromEnvironment(req: go.Pointer<go.net.http.Request>): go.Result<go.Pointer<go.net.url.URL>>;
    @:native("ProxyURL") static function proxyURL(fixedURL: go.Pointer<go.net.url.URL>): (p0: go.Pointer<go.net.http.Request>) -> go.Result<go.Pointer<go.net.url.URL>>;
    @:native("ReadRequest") static function readRequest(b: go.Pointer<go.bufio.Reader>): go.Result<go.Pointer<go.net.http.Request>>;
    @:native("ReadResponse") static function readResponse(r: go.Pointer<go.bufio.Reader>, req: go.Pointer<go.net.http.Request>): go.Result<go.Pointer<go.net.http.Response>>;
    @:native("Redirect") static function redirect(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>, url: String, code: go.GoInt): Void;
    @:native("RedirectHandler") static function redirectHandler(url: String, code: go.GoInt): go.net.http.Handler;
    @:native("Serve") static function serve(l: go.net.Listener, handler: go.net.http.Handler): go.Error;
    @:native("ServeContent") static function serveContent(w: go.net.http.ResponseWriter, req: go.Pointer<go.net.http.Request>, name: String, modtime: go.time.Time, content: go.io.ReadSeeker): Void;
    @:native("ServeFile") static function serveFile(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>, name: String): Void;
    @:native("ServeFileFS") static function serveFileFS(w: go.net.http.ResponseWriter, r: go.Pointer<go.net.http.Request>, fsys: go.io.fs.FS, name: String): Void;
    @:native("ServeTLS") static function serveTLS(l: go.net.Listener, handler: go.net.http.Handler, certFile: String, keyFile: String): go.Error;
    @:native("SetCookie") static function setCookie(w: go.net.http.ResponseWriter, cookie: go.Pointer<go.net.http.Cookie>): Void;
    @:native("StatusText") static function statusText(code: go.GoInt): String;
    @:native("StripPrefix") static function stripPrefix(prefix: String, h: go.net.http.Handler): go.net.http.Handler;
    @:native("TimeoutHandler") static function timeoutHandler(h: go.net.http.Handler, dt: go.time.Duration, msg: String): go.net.http.Handler;

}