package go.net.http.httptest;

/**
    ResponseRecorder is an implementation of [http.ResponseWriter] that
    records its mutations for later inspection in tests.
**/
@:structInit
@:go.Type({ name: "ResponseRecorder", instanceName: "httptest.ResponseRecorder", imports: ["net/http/httptest"] })
extern class ResponseRecorder {

    @:native("Code") var code: go.GoInt;
    @:native("HeaderMap") var headerMap: go.net.http.Header;
    @:native("Body") var body: go.Pointer<go.bytes.Buffer>;
    @:native("Flushed") var flushed: Bool;

    function new(code: go.GoInt=0, headerMap: go.net.http.Header=null, body: go.Pointer<go.bytes.Buffer>=null, flushed: Bool=false);

    /**
        Flush implements [http.Flusher]. To test whether Flush was
        called, see rw.Flushed.
    **/
    @:native("Flush") function flush(): Void;
    /**
        Header implements [http.ResponseWriter]. It returns the response
        headers to mutate within a handler. To test the headers that were
        written after a handler completes, use the [ResponseRecorder.Result] method and see
        the returned Response value's Header.
    **/
    @:native("Header") function header(): (go.net.http.Header);
    /**
        Result returns the response generated by the handler.
        
        The returned Response will have at least its StatusCode,
        Header, Body, and optionally Trailer populated.
        More fields may be populated in the future, so callers should
        not DeepEqual the result in tests.
        
        The Response.Header is a snapshot of the headers at the time of the
        first write call, or at the time of this call, if the handler never
        did a write.
        
        The Response.Body is guaranteed to be non-nil and Body.Read call is
        guaranteed to not return any error other than [io.EOF].
        
        Result must only be called after the handler has finished running.
    **/
    @:native("Result") function result(): (go.Pointer<go.net.http.Response>);
    /**
        Write implements http.ResponseWriter. The data in buf is written to
        rw.Body, if not nil.
    **/
    @:native("Write") function write(buf: go.Slice<go.Byte>): (go.Result<go.GoInt>);
    /**
        WriteHeader implements [http.ResponseWriter].
    **/
    @:native("WriteHeader") function writeHeader(code: go.GoInt): Void;
    /**
        WriteString implements [io.StringWriter]. The data in str is written
        to rw.Body, if not nil.
    **/
    @:native("WriteString") function writeString(str: String): (go.Result<go.GoInt>);

}