package go.reflect;

@:structInit
@:go.Type({ name: "Value", instanceName: "reflect.Value", imports: ["reflect"] })
extern class Value {

    @:native("Addr") function addr(): go.reflect.Value;
    @:native("Bool") function bool(): Bool;
    @:native("Bytes") function bytes(): go.Slice<go.Byte>;
    @:native("Call") function call(_in: go.Slice<go.reflect.Value>): go.Slice<go.reflect.Value>;
    @:native("CallSlice") function callSlice(_in: go.Slice<go.reflect.Value>): go.Slice<go.reflect.Value>;
    @:native("CanAddr") function canAddr(): Bool;
    @:native("CanComplex") function canComplex(): Bool;
    @:native("CanConvert") function canConvert(t: go.reflect.Type): Bool;
    @:native("CanFloat") function canFloat(): Bool;
    @:native("CanInt") function canInt(): Bool;
    @:native("CanInterface") function canInterface(): Bool;
    @:native("CanSet") function canSet(): Bool;
    @:native("CanUint") function canUint(): Bool;
    @:native("Cap") function cap(): go.GoInt;
    @:native("Clear") function clear(): Void;
    @:native("Close") function close(): Void;
    @:native("Comparable") function comparable(): Bool;
    @:native("Complex") function complex(): go.Complex128;
    @:native("Convert") function convert(t: go.reflect.Type): go.reflect.Value;
    @:native("Elem") function elem(): go.reflect.Value;
    @:native("Equal") function equal(u: go.reflect.Value): Bool;
    @:native("Field") function field(i: go.GoInt): go.reflect.Value;
    @:native("FieldByIndex") function fieldByIndex(index: go.Slice<go.GoInt>): go.reflect.Value;
    @:native("FieldByIndexErr") function fieldByIndexErr(index: go.Slice<go.GoInt>): go.Result<go.reflect.Value>;
    @:native("FieldByName") function fieldByName(name: String): go.reflect.Value;
    @:native("FieldByNameFunc") function fieldByNameFunc(match: (p0: String) -> Bool): go.reflect.Value;
    @:native("Fields") function fields(): go.iter.Seq2<go.reflect.StructField, go.reflect.Value>;
    @:native("Float") function float(): Float;
    @:native("Grow") function grow(n: go.GoInt): Void;
    @:native("Index") function index(i: go.GoInt): go.reflect.Value;
    @:native("Int") function int(): go.Int64;
    @:native("Interface") function iface(): Dynamic;
    @:native("InterfaceData") function interfaceData(): go.GoArray<go.UIntPtr, 2>;
    @:native("IsNil") function isNil(): Bool;
    @:native("IsValid") function isValid(): Bool;
    @:native("IsZero") function isZero(): Bool;
    @:native("Kind") function kind(): go.reflect.Kind;
    @:native("Len") function len(): go.GoInt;
    @:native("MapIndex") function mapIndex(key: go.reflect.Value): go.reflect.Value;
    @:native("MapKeys") function mapKeys(): go.Slice<go.reflect.Value>;
    @:native("MapRange") function mapRange(): go.Pointer<go.reflect.MapIter>;
    @:native("Method") function method(i: go.GoInt): go.reflect.Value;
    @:native("MethodByName") function methodByName(name: String): go.reflect.Value;
    @:native("Methods") function methods(): go.iter.Seq2<go.reflect.Method, go.reflect.Value>;
    @:native("NumField") function numField(): go.GoInt;
    @:native("NumMethod") function numMethod(): go.GoInt;
    @:native("OverflowComplex") function overflowComplex(x: go.Complex128): Bool;
    @:native("OverflowFloat") function overflowFloat(x: Float): Bool;
    @:native("OverflowInt") function overflowInt(x: go.Int64): Bool;
    @:native("OverflowUint") function overflowUint(x: go.UInt64): Bool;
    @:native("Pointer") function pointer(): go.UIntPtr;
    @:go.Tuple("x", "ok") @:native("Recv") function recv(): go.Tuple<{ x: go.reflect.Value, ok: Bool }>;
    @:native("Send") function send(x: go.reflect.Value): Void;
    @:native("Seq") function seq(): go.iter.Seq<go.reflect.Value>;
    @:native("Seq2") function seq2(): go.iter.Seq2<go.reflect.Value, go.reflect.Value>;
    @:native("Set") function set(x: go.reflect.Value): Void;
    @:native("SetBool") function setBool(x: Bool): Void;
    @:native("SetBytes") function setBytes(x: go.Slice<go.Byte>): Void;
    @:native("SetCap") function setCap(n: go.GoInt): Void;
    @:native("SetComplex") function setComplex(x: go.Complex128): Void;
    @:native("SetFloat") function setFloat(x: Float): Void;
    @:native("SetInt") function setInt(x: go.Int64): Void;
    @:native("SetIterKey") function setIterKey(iter: go.Pointer<go.reflect.MapIter>): Void;
    @:native("SetIterValue") function setIterValue(iter: go.Pointer<go.reflect.MapIter>): Void;
    @:native("SetLen") function setLen(n: go.GoInt): Void;
    @:native("SetMapIndex") function setMapIndex(key: go.reflect.Value, elem: go.reflect.Value): Void;
    @:native("SetPointer") function setPointer(x: go.unsafe.Pointer): Void;
    @:native("SetString") function setString(x: String): Void;
    @:native("SetUint") function setUint(x: go.UInt64): Void;
    @:native("SetZero") function setZero(): Void;
    @:native("Slice") function slice(i: go.GoInt, j: go.GoInt): go.reflect.Value;
    @:native("Slice3") function slice3(i: go.GoInt, j: go.GoInt, k: go.GoInt): go.reflect.Value;
    @:native("String") function string(): String;
    @:go.Tuple("x", "ok") @:native("TryRecv") function tryRecv(): go.Tuple<{ x: go.reflect.Value, ok: Bool }>;
    @:native("TrySend") function trySend(x: go.reflect.Value): Bool;
    @:native("Type") function type(): go.reflect.Type;
    @:native("Uint") function uint(): go.UInt64;
    @:native("UnsafeAddr") function unsafeAddr(): go.UIntPtr;
    @:native("UnsafePointer") function unsafePointer(): go.unsafe.Pointer;

}