package go;

@:go.Type({ name: "math", instanceName: "math.math", imports: ["math"] })
extern class Math {

    @:native("E") static var E: Float;
    @:native("Ln10") static var ln10: Float;
    @:native("Ln2") static var ln2: Float;
    @:native("Log10E") static var log10E: Float;
    @:native("Log2E") static var log2E: Float;
    @:native("MaxFloat32") static var maxFloat32: Float;
    @:native("MaxFloat64") static var maxFloat64: Float;
    @:native("MaxInt") static var maxInt: go.GoInt;
    @:native("MaxInt16") static var maxInt16: go.GoInt;
    @:native("MaxInt32") static var maxInt32: go.GoInt;
    @:native("MaxInt64") static var maxInt64: go.GoInt;
    @:native("MaxInt8") static var maxInt8: go.GoInt;
    @:native("MaxUint") static var maxUint: go.GoInt;
    @:native("MaxUint16") static var maxUint16: go.GoInt;
    @:native("MaxUint32") static var maxUint32: go.GoInt;
    @:native("MaxUint64") static var maxUint64: go.GoInt;
    @:native("MaxUint8") static var maxUint8: go.GoInt;
    @:native("MinInt") static var minInt: go.GoInt;
    @:native("MinInt16") static var minInt16: go.GoInt;
    @:native("MinInt32") static var minInt32: go.GoInt;
    @:native("MinInt64") static var minInt64: go.GoInt;
    @:native("MinInt8") static var minInt8: go.GoInt;
    @:native("Phi") static var phi: Float;
    @:native("Pi") static var pi: Float;
    @:native("SmallestNonzeroFloat32") static var smallestNonzeroFloat32: Float;
    @:native("SmallestNonzeroFloat64") static var smallestNonzeroFloat64: Float;
    @:native("Sqrt2") static var sqrt2: Float;
    @:native("SqrtE") static var sqrtE: Float;
    @:native("SqrtPhi") static var sqrtPhi: Float;
    @:native("SqrtPi") static var sqrtPi: Float;

    @:native("Abs") static function abs(x: Float): (Float);
    @:native("Acos") static function acos(x: Float): (Float);
    @:native("Acosh") static function acosh(x: Float): (Float);
    @:native("Asin") static function asin(x: Float): (Float);
    @:native("Asinh") static function asinh(x: Float): (Float);
    @:native("Atan") static function atan(x: Float): (Float);
    @:native("Atan2") static function atan2(y: Float, x: Float): (Float);
    @:native("Atanh") static function atanh(x: Float): (Float);
    @:native("Cbrt") static function cbrt(x: Float): (Float);
    @:native("Ceil") static function ceil(x: Float): (Float);
    @:native("Copysign") static function copysign(f: Float, sign: Float): (Float);
    @:native("Cos") static function cos(x: Float): (Float);
    @:native("Cosh") static function cosh(x: Float): (Float);
    @:native("Dim") static function dim(x: Float, y: Float): (Float);
    @:native("Erf") static function erf(x: Float): (Float);
    @:native("Erfc") static function erfc(x: Float): (Float);
    @:native("Erfcinv") static function erfcinv(x: Float): (Float);
    @:native("Erfinv") static function erfinv(x: Float): (Float);
    @:native("Exp") static function exp(x: Float): (Float);
    @:native("Exp2") static function exp2(x: Float): (Float);
    @:native("Expm1") static function expm1(x: Float): (Float);
    @:native("FMA") static function FMA(x: Float, y: Float, z: Float): (Float);
    @:native("Float32bits") static function float32bits(f: go.Float32): (go.UInt32);
    @:native("Float32frombits") static function float32frombits(b: go.UInt32): (go.Float32);
    @:native("Float64bits") static function float64bits(f: Float): (go.UInt64);
    @:native("Float64frombits") static function float64frombits(b: go.UInt64): (Float);
    @:native("Floor") static function floor(x: Float): (Float);
    @:go.Tuple("frac", "exp") @:native("Frexp") static function frexp(f: Float): (go.Tuple<{ frac: Float, exp: go.GoInt }>);
    @:native("Gamma") static function gamma(x: Float): (Float);
    @:native("Hypot") static function hypot(p: Float, q: Float): (Float);
    @:native("Ilogb") static function ilogb(x: Float): (go.GoInt);
    @:native("Inf") static function inf(sign: go.GoInt): (Float);
    @:native("IsInf") static function isInf(f: Float, sign: go.GoInt): (Bool);
    @:native("IsNaN") static function isNaN(f: Float): (Bool);
    @:native("J0") static function J0(x: Float): (Float);
    @:native("J1") static function J1(x: Float): (Float);
    @:native("Jn") static function jn(n: go.GoInt, x: Float): (Float);
    @:native("Ldexp") static function ldexp(frac: Float, exp: go.GoInt): (Float);
    @:go.Tuple("lgamma", "sign") @:native("Lgamma") static function lgamma(x: Float): (go.Tuple<{ lgamma: Float, sign: go.GoInt }>);
    @:native("Log") static function log(x: Float): (Float);
    @:native("Log10") static function log10(x: Float): (Float);
    @:native("Log1p") static function log1p(x: Float): (Float);
    @:native("Log2") static function log2(x: Float): (Float);
    @:native("Logb") static function logb(x: Float): (Float);
    @:native("Max") static function max(x: Float, y: Float): (Float);
    @:native("Min") static function min(x: Float, y: Float): (Float);
    @:native("Mod") static function mod(x: Float, y: Float): (Float);
    @:go.Tuple("integer", "fractional") @:native("Modf") static function modf(f: Float): (go.Tuple<{ integer: Float, fractional: Float }>);
    @:native("NaN") static function naN(): (Float);
    @:native("Nextafter") static function nextafter(x: Float, y: Float): (Float);
    @:native("Nextafter32") static function nextafter32(x: go.Float32, y: go.Float32): (go.Float32);
    @:native("Pow") static function pow(x: Float, y: Float): (Float);
    @:native("Pow10") static function pow10(n: go.GoInt): (Float);
    @:native("Remainder") static function remainder(x: Float, y: Float): (Float);
    @:native("Round") static function round(x: Float): (Float);
    @:native("RoundToEven") static function roundToEven(x: Float): (Float);
    @:native("Signbit") static function signbit(x: Float): (Bool);
    @:native("Sin") static function sin(x: Float): (Float);
    @:go.Tuple("sin", "cos") @:native("Sincos") static function sincos(x: Float): (go.Tuple<{ sin: Float, cos: Float }>);
    @:native("Sinh") static function sinh(x: Float): (Float);
    @:native("Sqrt") static function sqrt(x: Float): (Float);
    @:native("Tan") static function tan(x: Float): (Float);
    @:native("Tanh") static function tanh(x: Float): (Float);
    @:native("Trunc") static function trunc(x: Float): (Float);
    @:native("Y0") static function Y0(x: Float): (Float);
    @:native("Y1") static function Y1(x: Float): (Float);
    @:native("Yn") static function yn(n: go.GoInt, x: Float): (Float);

}