package go.internal;

@:go.Type({ name: "abi", instanceName: "abi.abi", imports: ["internal/abi"] })
extern class Abi {

    @:native("ArgsSizeUnknown") static var ArgsSizeUnknown: go.GoInt;
    @:native("Array") static var Array: go.internal.abi.Kind;
    @:native("Bool") static var Bool: go.internal.abi.Kind;
    @:native("BothDir") static var BothDir: go.internal.abi.ChanDir;
    @:native("BoundsConvert") static var BoundsConvert: go.internal.abi.BoundsErrorCode;
    @:native("BoundsIndex") static var BoundsIndex: go.internal.abi.BoundsErrorCode;
    @:native("BoundsMaxConst") static var BoundsMaxConst: go.GoInt;
    @:native("BoundsMaxReg") static var BoundsMaxReg: go.GoInt;
    @:native("BoundsSlice3Acap") static var BoundsSlice3Acap: go.internal.abi.BoundsErrorCode;
    @:native("BoundsSlice3Alen") static var BoundsSlice3Alen: go.internal.abi.BoundsErrorCode;
    @:native("BoundsSlice3B") static var BoundsSlice3B: go.internal.abi.BoundsErrorCode;
    @:native("BoundsSlice3C") static var BoundsSlice3C: go.internal.abi.BoundsErrorCode;
    @:native("BoundsSliceAcap") static var BoundsSliceAcap: go.internal.abi.BoundsErrorCode;
    @:native("BoundsSliceAlen") static var BoundsSliceAlen: go.internal.abi.BoundsErrorCode;
    @:native("BoundsSliceB") static var BoundsSliceB: go.internal.abi.BoundsErrorCode;
    @:native("Chan") static var Chan: go.internal.abi.Kind;
    @:native("Complex128") static var Complex128: go.internal.abi.Kind;
    @:native("Complex64") static var Complex64: go.internal.abi.Kind;
    @:native("CurrentPCLnTabMagic") static var CurrentPCLnTabMagic: go.internal.abi.PCLnTabMagic;
    @:native("EffectiveFloatRegSize") static var EffectiveFloatRegSize: go.GoInt;
    @:native("FUNCDATA_ArgInfo") static var FUNCDATA_ArgInfo: go.GoInt;
    @:native("FUNCDATA_ArgLiveInfo") static var FUNCDATA_ArgLiveInfo: go.GoInt;
    @:native("FUNCDATA_ArgsPointerMaps") static var FUNCDATA_ArgsPointerMaps: go.GoInt;
    @:native("FUNCDATA_InlTree") static var FUNCDATA_InlTree: go.GoInt;
    @:native("FUNCDATA_LocalsPointerMaps") static var FUNCDATA_LocalsPointerMaps: go.GoInt;
    @:native("FUNCDATA_OpenCodedDeferInfo") static var FUNCDATA_OpenCodedDeferInfo: go.GoInt;
    @:native("FUNCDATA_StackObjects") static var FUNCDATA_StackObjects: go.GoInt;
    @:native("FUNCDATA_WrapInfo") static var FUNCDATA_WrapInfo: go.GoInt;
    @:native("Float32") static var Float32: go.internal.abi.Kind;
    @:native("Float64") static var Float64: go.internal.abi.Kind;
    @:native("FloatArgRegs") static var FloatArgRegs: go.GoInt;
    @:native("Func") static var Func: go.internal.abi.Kind;
    @:native("FuncFlagAsm") static var FuncFlagAsm: go.internal.abi.FuncFlag;
    @:native("FuncFlagSPWrite") static var FuncFlagSPWrite: go.internal.abi.FuncFlag;
    @:native("FuncFlagTopFrame") static var FuncFlagTopFrame: go.internal.abi.FuncFlag;
    @:native("FuncIDNormal") static var FuncIDNormal: go.internal.abi.FuncID;
    @:native("FuncIDWrapper") static var FuncIDWrapper: go.internal.abi.FuncID;
    @:native("FuncID_abort") static var FuncID_abort: go.internal.abi.FuncID;
    @:native("FuncID_asmcgocall") static var FuncID_asmcgocall: go.internal.abi.FuncID;
    @:native("FuncID_asyncPreempt") static var FuncID_asyncPreempt: go.internal.abi.FuncID;
    @:native("FuncID_cgocallback") static var FuncID_cgocallback: go.internal.abi.FuncID;
    @:native("FuncID_corostart") static var FuncID_corostart: go.internal.abi.FuncID;
    @:native("FuncID_debugCallV2") static var FuncID_debugCallV2: go.internal.abi.FuncID;
    @:native("FuncID_gcBgMarkWorker") static var FuncID_gcBgMarkWorker: go.internal.abi.FuncID;
    @:native("FuncID_goexit") static var FuncID_goexit: go.internal.abi.FuncID;
    @:native("FuncID_gogo") static var FuncID_gogo: go.internal.abi.FuncID;
    @:native("FuncID_gopanic") static var FuncID_gopanic: go.internal.abi.FuncID;
    @:native("FuncID_handleAsyncEvent") static var FuncID_handleAsyncEvent: go.internal.abi.FuncID;
    @:native("FuncID_mcall") static var FuncID_mcall: go.internal.abi.FuncID;
    @:native("FuncID_morestack") static var FuncID_morestack: go.internal.abi.FuncID;
    @:native("FuncID_mstart") static var FuncID_mstart: go.internal.abi.FuncID;
    @:native("FuncID_panicwrap") static var FuncID_panicwrap: go.internal.abi.FuncID;
    @:native("FuncID_rt0_go") static var FuncID_rt0_go: go.internal.abi.FuncID;
    @:native("FuncID_runCleanups") static var FuncID_runCleanups: go.internal.abi.FuncID;
    @:native("FuncID_runFinalizers") static var FuncID_runFinalizers: go.internal.abi.FuncID;
    @:native("FuncID_runtime_main") static var FuncID_runtime_main: go.internal.abi.FuncID;
    @:native("FuncID_sigpanic") static var FuncID_sigpanic: go.internal.abi.FuncID;
    @:native("FuncID_systemstack") static var FuncID_systemstack: go.internal.abi.FuncID;
    @:native("FuncID_systemstack_switch") static var FuncID_systemstack_switch: go.internal.abi.FuncID;
    @:native("FuncTabBucketSize") static var FuncTabBucketSize: go.GoInt;
    @:native("Go116PCLnTabMagic") static var Go116PCLnTabMagic: go.internal.abi.PCLnTabMagic;
    @:native("Go118PCLnTabMagic") static var Go118PCLnTabMagic: go.internal.abi.PCLnTabMagic;
    @:native("Go120PCLnTabMagic") static var Go120PCLnTabMagic: go.internal.abi.PCLnTabMagic;
    @:native("Go12PCLnTabMagic") static var Go12PCLnTabMagic: go.internal.abi.PCLnTabMagic;
    @:native("Int") static var Int: go.internal.abi.Kind;
    @:native("Int16") static var Int16: go.internal.abi.Kind;
    @:native("Int32") static var Int32: go.internal.abi.Kind;
    @:native("Int64") static var Int64: go.internal.abi.Kind;
    @:native("Int8") static var Int8: go.internal.abi.Kind;
    @:native("IntArgRegs") static var IntArgRegs: go.GoInt;
    @:native("Interface") static var Interface: go.internal.abi.Kind;
    @:native("Invalid") static var Invalid: go.internal.abi.Kind;
    @:native("InvalidDir") static var InvalidDir: go.internal.abi.ChanDir;
    @:native("KindDirectIface") static var KindDirectIface: go.internal.abi.Kind;
    @:native("MINFUNC") static var MINFUNC: go.GoInt;
    @:native("Map") static var Map: go.internal.abi.Kind;
    @:native("MapCtrlEmpty") static var MapCtrlEmpty: go.UInt64;
    @:native("MapGroupSlots") static var MapGroupSlots: go.GoInt;
    @:native("MapGroupSlotsBits") static var MapGroupSlotsBits: go.GoInt;
    @:native("MapHashMightPanic") static var MapHashMightPanic: go.GoInt;
    @:native("MapIndirectElem") static var MapIndirectElem: go.GoInt;
    @:native("MapIndirectKey") static var MapIndirectKey: go.GoInt;
    @:native("MapMaxElemBytes") static var MapMaxElemBytes: go.GoInt;
    @:native("MapMaxKeyBytes") static var MapMaxKeyBytes: go.GoInt;
    @:native("MapNeedKeyUpdate") static var MapNeedKeyUpdate: go.GoInt;
    @:native("MaxPtrmaskBytes") static var MaxPtrmaskBytes: go.GoInt;
    @:native("PCDATA_ArgLiveIndex") static var PCDATA_ArgLiveIndex: go.GoInt;
    @:native("PCDATA_InlTreeIndex") static var PCDATA_InlTreeIndex: go.GoInt;
    @:native("PCDATA_PanicBounds") static var PCDATA_PanicBounds: go.GoInt;
    @:native("PCDATA_StackMapIndex") static var PCDATA_StackMapIndex: go.GoInt;
    @:native("PCDATA_UnsafePoint") static var PCDATA_UnsafePoint: go.GoInt;
    @:native("Pointer") static var Pointer: go.internal.abi.Kind;
    @:native("RF_DONE") static var RF_DONE: go.internal.abi.RF_State;
    @:native("RF_EXHAUSTED") static var RF_EXHAUSTED: go.internal.abi.RF_State;
    @:native("RF_MISSING_PANIC") static var RF_MISSING_PANIC: go.GoInt;
    @:native("RF_PANIC") static var RF_PANIC: go.internal.abi.RF_State;
    @:native("RF_READY") static var RF_READY: go.internal.abi.RF_State;
    @:native("RecvDir") static var RecvDir: go.internal.abi.ChanDir;
    @:native("SendDir") static var SendDir: go.internal.abi.ChanDir;
    @:native("Slice") static var Slice: go.internal.abi.Kind;
    @:native("StackBig") static var StackBig: go.GoInt;
    @:native("StackNosplitBase") static var StackNosplitBase: go.GoInt;
    @:native("StackSmall") static var StackSmall: go.GoInt;
    @:native("String") static var String: go.internal.abi.Kind;
    @:native("Struct") static var Struct: go.internal.abi.Kind;
    @:native("TFlagDirectIface") static var TFlagDirectIface: go.internal.abi.TFlag;
    @:native("TFlagExtraStar") static var TFlagExtraStar: go.internal.abi.TFlag;
    @:native("TFlagGCMaskOnDemand") static var TFlagGCMaskOnDemand: go.internal.abi.TFlag;
    @:native("TFlagNamed") static var TFlagNamed: go.internal.abi.TFlag;
    @:native("TFlagRegularMemory") static var TFlagRegularMemory: go.internal.abi.TFlag;
    @:native("TFlagUncommon") static var TFlagUncommon: go.internal.abi.TFlag;
    @:native("TraceArgsDotdotdot") static var TraceArgsDotdotdot: go.GoInt;
    @:native("TraceArgsEndAgg") static var TraceArgsEndAgg: go.GoInt;
    @:native("TraceArgsEndSeq") static var TraceArgsEndSeq: go.GoInt;
    @:native("TraceArgsLimit") static var TraceArgsLimit: go.GoInt;
    @:native("TraceArgsMaxDepth") static var TraceArgsMaxDepth: go.GoInt;
    @:native("TraceArgsMaxLen") static var TraceArgsMaxLen: go.GoInt;
    @:native("TraceArgsOffsetTooLarge") static var TraceArgsOffsetTooLarge: go.GoInt;
    @:native("TraceArgsSpecial") static var TraceArgsSpecial: go.GoInt;
    @:native("TraceArgsStartAgg") static var TraceArgsStartAgg: go.GoInt;
    @:native("Uint") static var Uint: go.internal.abi.Kind;
    @:native("Uint16") static var Uint16: go.internal.abi.Kind;
    @:native("Uint32") static var Uint32: go.internal.abi.Kind;
    @:native("Uint64") static var Uint64: go.internal.abi.Kind;
    @:native("Uint8") static var Uint8: go.internal.abi.Kind;
    @:native("Uintptr") static var Uintptr: go.internal.abi.Kind;
    @:native("UnsafePointRestart1") static var UnsafePointRestart1: go.GoInt;
    @:native("UnsafePointRestart2") static var UnsafePointRestart2: go.GoInt;
    @:native("UnsafePointRestartAtEntry") static var UnsafePointRestartAtEntry: go.GoInt;
    @:native("UnsafePointSafe") static var UnsafePointSafe: go.GoInt;
    @:native("UnsafePointUnsafe") static var UnsafePointUnsafe: go.GoInt;
    @:native("UnsafePointer") static var UnsafePointer: go.internal.abi.Kind;
    @:native("ZeroValSize") static var ZeroValSize: go.GoInt;

    @:go.Tuple("code", "signed", "xIsReg", "yIsReg", "xVal", "yVal") @:native("BoundsDecode") static function boundsDecode(v: go.GoInt): go.Tuple<{ code: go.internal.abi.BoundsErrorCode, signed: Bool, xIsReg: Bool, yIsReg: Bool, xVal: go.GoInt, yVal: go.GoInt }>;
    @:native("BoundsEncode") static function boundsEncode(code: go.internal.abi.BoundsErrorCode, signed: Bool, xIsReg: Bool, yIsReg: Bool, xVal: go.GoInt, yVal: go.GoInt): go.GoInt;
    @:native("CommonSize") static function commonSize(ptrSize: go.GoInt): go.GoInt;
    @:native("Escape") static function escape<T: Dynamic>(x: T): T;
    @:native("EscapeNonString") static function escapeNonString<T: Dynamic>(v: T): Void;
    @:native("EscapeToResultNonString") static function escapeToResultNonString<T: Dynamic>(v: T): T;
    @:native("FuncPCABI0") static function funcPCABI0(f: Dynamic): go.UIntPtr;
    @:native("FuncPCABIInternal") static function funcPCABIInternal(f: Dynamic): go.UIntPtr;
    @:native("ITabTypeOff") static function iTabTypeOff(ptrSize: go.GoInt): go.GoInt;
    @:native("NewName") static function newName(n: String, tag: String, exported: Bool, embedded: Bool): go.internal.abi.Name;
    @:native("NoEscape") static function noEscape(p: go.unsafe.Pointer): go.unsafe.Pointer;
    @:native("StructFieldSize") static function structFieldSize(ptrSize: go.GoInt): go.GoInt;
    @:native("TFlagOff") static function tFlagOff(ptrSize: go.GoInt): go.GoInt;
    @:native("TypeFor") static function typeFor<T: Dynamic>(): go.Pointer<go.internal.abi.Type>;
    @:native("TypeOf") static function typeOf(a: Dynamic): go.Pointer<go.internal.abi.Type>;
    @:native("UncommonSize") static function uncommonSize(): go.UInt64;
    @:native("UseInterfaceSwitchCache") static function useInterfaceSwitchCache(arch: go.internal.goarch.ArchFamilyType): Bool;

}