package go.crypto;

/**
    Package ecdsa implements the Elliptic Curve Digital Signature Algorithm, as
    defined in [FIPS 186-5].
    
    Signatures generated by this package are not deterministic, but entropy is
    mixed with the private key and the message, achieving the same level of
    security in case of randomness source failure.
    
    Operations involving private keys are implemented using constant-time
    algorithms, as long as an [elliptic.Curve] returned by [elliptic.P224],
    [elliptic.P256], [elliptic.P384], or [elliptic.P521] is used.
    
    [FIPS 186-5]: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf
**/
@:go.Type({ name: "ecdsa", instanceName: "ecdsa.ecdsa", imports: ["crypto/ecdsa"] })
extern class Ecdsa {

    /**
        GenerateKey generates a new ECDSA private key for the specified curve.
        
        Since Go 1.26, a secure source of random bytes is always used, and the Reader is
        ignored unless GODEBUG=cryptocustomrand=1 is set. This setting will be removed
        in a future Go release. Instead, use [testing/cryptotest.SetGlobalRandom].
    **/
    @:native("GenerateKey") static function generateKey(c: go.crypto.elliptic.Curve, r: go.io.Reader): (go.Result<go.Pointer<go.crypto.ecdsa.PrivateKey>>);
    /**
        ParseRawPrivateKey parses a private key encoded as a fixed-length big-endian
        integer, according to SEC 1, Version 2.0, Section 2.3.6 (sometimes referred
        to as the raw format). It returns an error if the value is not reduced modulo
        the curve's order, or if it's zero.
        
        curve must be one of [elliptic.P224], [elliptic.P256], [elliptic.P384], or
        [elliptic.P521], or ParseRawPrivateKey returns an error.
        
        ParseRawPrivateKey accepts the same format as [ecdh.Curve.NewPrivateKey] does
        for NIST curves, but returns a [PrivateKey] instead of an [ecdh.PrivateKey].
        
        Note that private keys are more commonly encoded in ASN.1 or PKCS#8 format,
        which can be parsed with [crypto/x509.ParseECPrivateKey] or
        [crypto/x509.ParsePKCS8PrivateKey] (and [encoding/pem]).
    **/
    @:native("ParseRawPrivateKey") static function parseRawPrivateKey(curve: go.crypto.elliptic.Curve, data: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.ecdsa.PrivateKey>>);
    /**
        ParseUncompressedPublicKey parses a public key encoded as an uncompressed
        point according to SEC 1, Version 2.0, Section 2.3.3 (also known as the X9.62
        uncompressed format). It returns an error if the point is not in uncompressed
        form, is not on the curve, or is the point at infinity.
        
        curve must be one of [elliptic.P224], [elliptic.P256], [elliptic.P384], or
        [elliptic.P521], or ParseUncompressedPublicKey returns an error.
        
        ParseUncompressedPublicKey accepts the same format as
        [ecdh.Curve.NewPublicKey] does for NIST curves, but returns a [PublicKey]
        instead of an [ecdh.PublicKey].
        
        Note that public keys are more commonly encoded in DER (or PEM) format, which
        can be parsed with [crypto/x509.ParsePKIXPublicKey] (and [encoding/pem]).
    **/
    @:native("ParseUncompressedPublicKey") static function parseUncompressedPublicKey(curve: go.crypto.elliptic.Curve, data: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.ecdsa.PublicKey>>);
    /**
        Sign signs a hash (which should be the result of hashing a larger message)
        using the private key, priv. If the hash is longer than the bit-length of the
        private key's curve order, the hash will be truncated to that length. It
        returns the signature as a pair of integers. Most applications should use
        [SignASN1] instead of dealing directly with r, s.
        
        The signature is randomized. Since Go 1.26, a secure source of random bytes
        is always used, and the Reader is ignored unless GODEBUG=cryptocustomrand=1
        is set. This setting will be removed in a future Go release. Instead, use
        [testing/cryptotest.SetGlobalRandom].
    **/
    @:go.Tuple("r", "s", "err") @:native("Sign") static function sign(rand: go.io.Reader, priv: go.Pointer<go.crypto.ecdsa.PrivateKey>, hash: go.Slice<go.Byte>): (go.Tuple<{ r: go.Pointer<go.math.big.Int>, s: go.Pointer<go.math.big.Int>, err: go.Error }>);
    /**
        SignASN1 signs a hash (which should be the result of hashing a larger message)
        using the private key, priv. If the hash is longer than the bit-length of the
        private key's curve order, the hash will be truncated to that length. It
        returns the ASN.1 encoded signature.
        
        The signature is randomized. Since Go 1.26, a secure source of random bytes
        is always used, and the Reader is ignored unless GODEBUG=cryptocustomrand=1
        is set. This setting will be removed in a future Go release. Instead, use
        [testing/cryptotest.SetGlobalRandom].
    **/
    @:native("SignASN1") static function signASN1(r: go.io.Reader, priv: go.Pointer<go.crypto.ecdsa.PrivateKey>, hash: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        Verify verifies the signature in r, s of hash using the public key, pub. Its
        return value records whether the signature is valid. Most applications should
        use VerifyASN1 instead of dealing directly with r, s.
        
        The inputs are not considered confidential, and may leak through timing side
        channels, or if an attacker has control of part of the inputs.
    **/
    @:native("Verify") static function verify(pub: go.Pointer<go.crypto.ecdsa.PublicKey>, hash: go.Slice<go.Byte>, r: go.Pointer<go.math.big.Int>, s: go.Pointer<go.math.big.Int>): (Bool);
    /**
        VerifyASN1 verifies the ASN.1 encoded signature, sig, of hash using the
        public key, pub. Its return value records whether the signature is valid.
        
        The inputs are not considered confidential, and may leak through timing side
        channels, or if an attacker has control of part of the inputs.
    **/
    @:native("VerifyASN1") static function verifyASN1(pub: go.Pointer<go.crypto.ecdsa.PublicKey>, hash: go.Slice<go.Byte>, sig: go.Slice<go.Byte>): (Bool);

}