package go.crypto;

/**
    Package hkdf implements the HMAC-based Extract-and-Expand Key Derivation
    Function (HKDF) as defined in RFC 5869.
    
    HKDF is a cryptographic key derivation function (KDF) with the goal of
    expanding limited input keying material into one or more cryptographically
    strong secret keys.
**/
@:go.Type({ name: "hkdf", instanceName: "hkdf.hkdf", imports: ["crypto/hkdf"] })
extern class Hkdf {

    /**
        Expand derives a key from the given hash, key, and optional context info,
        returning a []byte of length keyLength that can be used as cryptographic key.
        The extraction step is skipped.
        
        The key should have been generated by [Extract], or be a uniformly
        random or pseudorandom cryptographically strong key. See RFC 5869, Section
        3.3. Most common scenarios will want to use [Key] instead.
    **/
    @:native("Expand") static function expand<H: go.hash.Hash>(h: () -> (H), pseudorandomKey: go.Slice<go.Byte>, info: String, keyLength: go.GoInt): (go.Result<go.Slice<go.Byte>>);
    /**
        Extract generates a pseudorandom key for use with [Expand] from an input
        secret and an optional independent salt.
        
        Only use this function if you need to reuse the extracted key with multiple
        Expand invocations and different context values. Most common scenarios,
        including the generation of multiple keys, should use [Key] instead.
    **/
    @:native("Extract") static function extract<H: go.hash.Hash>(h: () -> (H), secret: go.Slice<go.Byte>, salt: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        Key derives a key from the given hash, secret, salt and context info,
        returning a []byte of length keyLength that can be used as cryptographic key.
        Salt and info can be nil.
    **/
    @:native("Key") static function key<Hash: go.hash.Hash>(h: () -> (Hash), secret: go.Slice<go.Byte>, salt: go.Slice<go.Byte>, info: String, keyLength: go.GoInt): (go.Result<go.Slice<go.Byte>>);

}