package go.crypto;

@:go.Type({ name: "tls", instanceName: "tls.tls", imports: ["crypto/tls"] })
extern class Tls {

    @:native("CurveP256") static var curveP256: go.crypto.tls.CurveID;
    @:native("CurveP384") static var curveP384: go.crypto.tls.CurveID;
    @:native("CurveP521") static var curveP521: go.crypto.tls.CurveID;
    @:native("ECDSAWithP256AndSHA256") static var eCDSAWithP256AndSHA256: go.crypto.tls.SignatureScheme;
    @:native("ECDSAWithP384AndSHA384") static var eCDSAWithP384AndSHA384: go.crypto.tls.SignatureScheme;
    @:native("ECDSAWithP521AndSHA512") static var eCDSAWithP521AndSHA512: go.crypto.tls.SignatureScheme;
    @:native("ECDSAWithSHA1") static var eCDSAWithSHA1: go.crypto.tls.SignatureScheme;
    @:native("Ed25519") static var ed25519: go.crypto.tls.SignatureScheme;
    @:native("NoClientCert") static var noClientCert: go.crypto.tls.ClientAuthType;
    @:native("PKCS1WithSHA1") static var pKCS1WithSHA1: go.crypto.tls.SignatureScheme;
    @:native("PKCS1WithSHA256") static var pKCS1WithSHA256: go.crypto.tls.SignatureScheme;
    @:native("PKCS1WithSHA384") static var pKCS1WithSHA384: go.crypto.tls.SignatureScheme;
    @:native("PKCS1WithSHA512") static var pKCS1WithSHA512: go.crypto.tls.SignatureScheme;
    @:native("PSSWithSHA256") static var pSSWithSHA256: go.crypto.tls.SignatureScheme;
    @:native("PSSWithSHA384") static var pSSWithSHA384: go.crypto.tls.SignatureScheme;
    @:native("PSSWithSHA512") static var pSSWithSHA512: go.crypto.tls.SignatureScheme;
    @:native("QUICEncryptionLevelApplication") static var qUICEncryptionLevelApplication: go.crypto.tls.QUICEncryptionLevel;
    @:native("QUICEncryptionLevelEarly") static var qUICEncryptionLevelEarly: go.crypto.tls.QUICEncryptionLevel;
    @:native("QUICEncryptionLevelHandshake") static var qUICEncryptionLevelHandshake: go.crypto.tls.QUICEncryptionLevel;
    @:native("QUICEncryptionLevelInitial") static var qUICEncryptionLevelInitial: go.crypto.tls.QUICEncryptionLevel;
    @:native("QUICErrorEvent") static var qUICErrorEvent: go.crypto.tls.QUICEventKind;
    @:native("QUICHandshakeDone") static var qUICHandshakeDone: go.crypto.tls.QUICEventKind;
    @:native("QUICNoEvent") static var qUICNoEvent: go.crypto.tls.QUICEventKind;
    @:native("QUICRejectedEarlyData") static var qUICRejectedEarlyData: go.crypto.tls.QUICEventKind;
    @:native("QUICResumeSession") static var qUICResumeSession: go.crypto.tls.QUICEventKind;
    @:native("QUICSetReadSecret") static var qUICSetReadSecret: go.crypto.tls.QUICEventKind;
    @:native("QUICSetWriteSecret") static var qUICSetWriteSecret: go.crypto.tls.QUICEventKind;
    @:native("QUICStoreSession") static var qUICStoreSession: go.crypto.tls.QUICEventKind;
    @:native("QUICTransportParameters") static var qUICTransportParameters: go.crypto.tls.QUICEventKind;
    @:native("QUICTransportParametersRequired") static var qUICTransportParametersRequired: go.crypto.tls.QUICEventKind;
    @:native("QUICWriteData") static var qUICWriteData: go.crypto.tls.QUICEventKind;
    @:native("RenegotiateFreelyAsClient") static var renegotiateFreelyAsClient: go.crypto.tls.RenegotiationSupport;
    @:native("RenegotiateNever") static var renegotiateNever: go.crypto.tls.RenegotiationSupport;
    @:native("RenegotiateOnceAsClient") static var renegotiateOnceAsClient: go.crypto.tls.RenegotiationSupport;
    @:native("RequestClientCert") static var requestClientCert: go.crypto.tls.ClientAuthType;
    @:native("RequireAndVerifyClientCert") static var requireAndVerifyClientCert: go.crypto.tls.ClientAuthType;
    @:native("RequireAnyClientCert") static var requireAnyClientCert: go.crypto.tls.ClientAuthType;
    @:native("SecP256r1MLKEM768") static var secP256r1MLKEM768: go.crypto.tls.CurveID;
    @:native("SecP384r1MLKEM1024") static var secP384r1MLKEM1024: go.crypto.tls.CurveID;
    @:native("TLS_AES_128_GCM_SHA256") static var TLS_AES_128_GCM_SHA256: go.UInt16;
    @:native("TLS_AES_256_GCM_SHA384") static var TLS_AES_256_GCM_SHA384: go.UInt16;
    @:native("TLS_CHACHA20_POLY1305_SHA256") static var TLS_CHACHA20_POLY1305_SHA256: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA") static var TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256") static var TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256") static var TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA") static var TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384") static var TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305") static var TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256") static var TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256: go.UInt16;
    @:native("TLS_ECDHE_ECDSA_WITH_RC4_128_SHA") static var TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA") static var TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA") static var TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256") static var TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256") static var TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA") static var TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384") static var TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305") static var TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256") static var TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256: go.UInt16;
    @:native("TLS_ECDHE_RSA_WITH_RC4_128_SHA") static var TLS_ECDHE_RSA_WITH_RC4_128_SHA: go.UInt16;
    @:native("TLS_FALLBACK_SCSV") static var TLS_FALLBACK_SCSV: go.UInt16;
    @:native("TLS_RSA_WITH_3DES_EDE_CBC_SHA") static var TLS_RSA_WITH_3DES_EDE_CBC_SHA: go.UInt16;
    @:native("TLS_RSA_WITH_AES_128_CBC_SHA") static var TLS_RSA_WITH_AES_128_CBC_SHA: go.UInt16;
    @:native("TLS_RSA_WITH_AES_128_CBC_SHA256") static var TLS_RSA_WITH_AES_128_CBC_SHA256: go.UInt16;
    @:native("TLS_RSA_WITH_AES_128_GCM_SHA256") static var TLS_RSA_WITH_AES_128_GCM_SHA256: go.UInt16;
    @:native("TLS_RSA_WITH_AES_256_CBC_SHA") static var TLS_RSA_WITH_AES_256_CBC_SHA: go.UInt16;
    @:native("TLS_RSA_WITH_AES_256_GCM_SHA384") static var TLS_RSA_WITH_AES_256_GCM_SHA384: go.UInt16;
    @:native("TLS_RSA_WITH_RC4_128_SHA") static var TLS_RSA_WITH_RC4_128_SHA: go.UInt16;
    @:native("VerifyClientCertIfGiven") static var verifyClientCertIfGiven: go.crypto.tls.ClientAuthType;
    @:native("VersionSSL30") static var versionSSL30: go.GoInt;
    @:native("VersionTLS10") static var versionTLS10: go.GoInt;
    @:native("VersionTLS11") static var versionTLS11: go.GoInt;
    @:native("VersionTLS12") static var versionTLS12: go.GoInt;
    @:native("VersionTLS13") static var versionTLS13: go.GoInt;
    @:native("X25519") static var X25519: go.crypto.tls.CurveID;
    @:native("X25519MLKEM768") static var X25519MLKEM768: go.crypto.tls.CurveID;

    @:native("CipherSuiteName") static function cipherSuiteName(id: go.UInt16): (String);
    @:native("CipherSuites") static function cipherSuites(): (go.Slice<go.Pointer<go.crypto.tls.CipherSuite>>);
    @:native("Client") static function client(conn: go.net.Conn, config: go.Pointer<go.crypto.tls.Config>): (go.Pointer<go.crypto.tls.Conn>);
    @:native("Dial") static function dial(network: String, addr: String, config: go.Pointer<go.crypto.tls.Config>): (go.Result<go.Pointer<go.crypto.tls.Conn>>);
    @:native("DialWithDialer") static function dialWithDialer(dialer: go.Pointer<go.net.Dialer>, network: String, addr: String, config: go.Pointer<go.crypto.tls.Config>): (go.Result<go.Pointer<go.crypto.tls.Conn>>);
    @:native("InsecureCipherSuites") static function insecureCipherSuites(): (go.Slice<go.Pointer<go.crypto.tls.CipherSuite>>);
    @:native("Listen") static function listen(network: String, laddr: String, config: go.Pointer<go.crypto.tls.Config>): (go.Result<go.net.Listener>);
    @:native("LoadX509KeyPair") static function loadX509KeyPair(certFile: String, keyFile: String): (go.Result<go.crypto.tls.Certificate>);
    @:native("NewLRUClientSessionCache") static function newLRUClientSessionCache(capacity: go.GoInt): (go.crypto.tls.ClientSessionCache);
    @:native("NewListener") static function newListener(inner: go.net.Listener, config: go.Pointer<go.crypto.tls.Config>): (go.net.Listener);
    @:native("NewResumptionState") static function newResumptionState(ticket: go.Slice<go.Byte>, state: go.Pointer<go.crypto.tls.SessionState>): (go.Result<go.Pointer<go.crypto.tls.ClientSessionState>>);
    @:native("ParseSessionState") static function parseSessionState(data: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.tls.SessionState>>);
    @:native("QUICClient") static function qUICClient(config: go.Pointer<go.crypto.tls.QUICConfig>): (go.Pointer<go.crypto.tls.QUICConn>);
    @:native("QUICServer") static function qUICServer(config: go.Pointer<go.crypto.tls.QUICConfig>): (go.Pointer<go.crypto.tls.QUICConn>);
    @:native("Server") static function server(conn: go.net.Conn, config: go.Pointer<go.crypto.tls.Config>): (go.Pointer<go.crypto.tls.Conn>);
    @:native("VersionName") static function versionName(version: go.UInt16): (String);
    @:native("X509KeyPair") static function x509KeyPair(certPEMBlock: go.Slice<go.Byte>, keyPEMBlock: go.Slice<go.Byte>): (go.Result<go.crypto.tls.Certificate>);

}