package go.crypto;

@:go.Type({ name: "x509", instanceName: "x509.x509", imports: ["crypto/x509"] })
extern class X509 {

    @:native("CANotAuthorizedForExtKeyUsage") static var cANotAuthorizedForExtKeyUsage: go.crypto.x509.InvalidReason;
    @:native("CANotAuthorizedForThisName") static var cANotAuthorizedForThisName: go.crypto.x509.InvalidReason;
    @:native("DSA") static var DSA: go.crypto.x509.PublicKeyAlgorithm;
    @:native("DSAWithSHA1") static var dSAWithSHA1: go.crypto.x509.SignatureAlgorithm;
    @:native("DSAWithSHA256") static var dSAWithSHA256: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSA") static var ECDSA: go.crypto.x509.PublicKeyAlgorithm;
    @:native("ECDSAWithSHA1") static var eCDSAWithSHA1: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSAWithSHA256") static var eCDSAWithSHA256: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSAWithSHA384") static var eCDSAWithSHA384: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSAWithSHA512") static var eCDSAWithSHA512: go.crypto.x509.SignatureAlgorithm;
    @:native("Ed25519") static var ed25519: go.crypto.x509.PublicKeyAlgorithm;
    @:native("Expired") static var expired: go.crypto.x509.InvalidReason;
    @:native("ExtKeyUsageAny") static var extKeyUsageAny: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageClientAuth") static var extKeyUsageClientAuth: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageCodeSigning") static var extKeyUsageCodeSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageEmailProtection") static var extKeyUsageEmailProtection: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageIPSECEndSystem") static var extKeyUsageIPSECEndSystem: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageIPSECTunnel") static var extKeyUsageIPSECTunnel: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageIPSECUser") static var extKeyUsageIPSECUser: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageMicrosoftCommercialCodeSigning") static var extKeyUsageMicrosoftCommercialCodeSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageMicrosoftKernelCodeSigning") static var extKeyUsageMicrosoftKernelCodeSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageMicrosoftServerGatedCrypto") static var extKeyUsageMicrosoftServerGatedCrypto: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageNetscapeServerGatedCrypto") static var extKeyUsageNetscapeServerGatedCrypto: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageOCSPSigning") static var extKeyUsageOCSPSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageServerAuth") static var extKeyUsageServerAuth: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageTimeStamping") static var extKeyUsageTimeStamping: go.crypto.x509.ExtKeyUsage;
    @:native("IncompatibleUsage") static var incompatibleUsage: go.crypto.x509.InvalidReason;
    @:native("KeyUsageCRLSign") static var keyUsageCRLSign: go.crypto.x509.KeyUsage;
    @:native("KeyUsageCertSign") static var keyUsageCertSign: go.crypto.x509.KeyUsage;
    @:native("KeyUsageContentCommitment") static var keyUsageContentCommitment: go.crypto.x509.KeyUsage;
    @:native("KeyUsageDataEncipherment") static var keyUsageDataEncipherment: go.crypto.x509.KeyUsage;
    @:native("KeyUsageDecipherOnly") static var keyUsageDecipherOnly: go.crypto.x509.KeyUsage;
    @:native("KeyUsageDigitalSignature") static var keyUsageDigitalSignature: go.crypto.x509.KeyUsage;
    @:native("KeyUsageEncipherOnly") static var keyUsageEncipherOnly: go.crypto.x509.KeyUsage;
    @:native("KeyUsageKeyAgreement") static var keyUsageKeyAgreement: go.crypto.x509.KeyUsage;
    @:native("KeyUsageKeyEncipherment") static var keyUsageKeyEncipherment: go.crypto.x509.KeyUsage;
    @:native("MD2WithRSA") static var mD2WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("MD5WithRSA") static var mD5WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("NameConstraintsWithoutSANs") static var nameConstraintsWithoutSANs: go.crypto.x509.InvalidReason;
    @:native("NameMismatch") static var nameMismatch: go.crypto.x509.InvalidReason;
    @:native("NoValidChains") static var noValidChains: go.crypto.x509.InvalidReason;
    @:native("NotAuthorizedToSign") static var notAuthorizedToSign: go.crypto.x509.InvalidReason;
    @:native("PEMCipher3DES") static var pEMCipher3DES: go.crypto.x509.PEMCipher;
    @:native("PEMCipherAES128") static var pEMCipherAES128: go.crypto.x509.PEMCipher;
    @:native("PEMCipherAES192") static var pEMCipherAES192: go.crypto.x509.PEMCipher;
    @:native("PEMCipherAES256") static var pEMCipherAES256: go.crypto.x509.PEMCipher;
    @:native("PEMCipherDES") static var pEMCipherDES: go.crypto.x509.PEMCipher;
    @:native("PureEd25519") static var pureEd25519: go.crypto.x509.SignatureAlgorithm;
    @:native("RSA") static var RSA: go.crypto.x509.PublicKeyAlgorithm;
    @:native("SHA1WithRSA") static var sHA1WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA256WithRSA") static var sHA256WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA256WithRSAPSS") static var sHA256WithRSAPSS: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA384WithRSA") static var sHA384WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA384WithRSAPSS") static var sHA384WithRSAPSS: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA512WithRSA") static var sHA512WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA512WithRSAPSS") static var sHA512WithRSAPSS: go.crypto.x509.SignatureAlgorithm;
    @:native("TooManyConstraints") static var tooManyConstraints: go.crypto.x509.InvalidReason;
    @:native("TooManyIntermediates") static var tooManyIntermediates: go.crypto.x509.InvalidReason;
    @:native("UnconstrainedName") static var unconstrainedName: go.crypto.x509.InvalidReason;
    @:native("UnknownPublicKeyAlgorithm") static var unknownPublicKeyAlgorithm: go.crypto.x509.PublicKeyAlgorithm;
    @:native("UnknownSignatureAlgorithm") static var unknownSignatureAlgorithm: go.crypto.x509.SignatureAlgorithm;

    @:native("CreateCertificate") static function createCertificate(rand: go.io.Reader, template: go.Pointer<go.crypto.x509.Certificate>, parent: go.Pointer<go.crypto.x509.Certificate>, pub: Dynamic, priv: Dynamic): (go.Result<go.Slice<go.Byte>>);
    @:native("CreateCertificateRequest") static function createCertificateRequest(rand: go.io.Reader, template: go.Pointer<go.crypto.x509.CertificateRequest>, priv: Dynamic): (go.Result<go.Slice<go.Byte>>);
    @:native("CreateRevocationList") static function createRevocationList(rand: go.io.Reader, template: go.Pointer<go.crypto.x509.RevocationList>, issuer: go.Pointer<go.crypto.x509.Certificate>, priv: go.crypto.Signer): (go.Result<go.Slice<go.Byte>>);
    @:native("DecryptPEMBlock") static function decryptPEMBlock(b: go.Pointer<go.encoding.pem.Block>, password: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    @:native("EncryptPEMBlock") static function encryptPEMBlock(rand: go.io.Reader, blockType: String, data: go.Slice<go.Byte>, password: go.Slice<go.Byte>, alg: go.crypto.x509.PEMCipher): (go.Result<go.Pointer<go.encoding.pem.Block>>);
    @:native("IsEncryptedPEMBlock") static function isEncryptedPEMBlock(b: go.Pointer<go.encoding.pem.Block>): (Bool);
    @:native("MarshalECPrivateKey") static function marshalECPrivateKey(key: go.Pointer<go.crypto.ecdsa.PrivateKey>): (go.Result<go.Slice<go.Byte>>);
    @:native("MarshalPKCS1PrivateKey") static function marshalPKCS1PrivateKey(key: go.Pointer<go.crypto.rsa.PrivateKey>): (go.Slice<go.Byte>);
    @:native("MarshalPKCS1PublicKey") static function marshalPKCS1PublicKey(key: go.Pointer<go.crypto.rsa.PublicKey>): (go.Slice<go.Byte>);
    @:native("MarshalPKCS8PrivateKey") static function marshalPKCS8PrivateKey(key: Dynamic): (go.Result<go.Slice<go.Byte>>);
    @:native("MarshalPKIXPublicKey") static function marshalPKIXPublicKey(pub: Dynamic): (go.Result<go.Slice<go.Byte>>);
    @:native("NewCertPool") static function newCertPool(): (go.Pointer<go.crypto.x509.CertPool>);
    @:native("OIDFromASN1OID") static function oIDFromASN1OID(asn1OID: go.encoding.asn1.ObjectIdentifier): (go.Result<go.crypto.x509.OID>);
    @:native("OIDFromInts") static function oIDFromInts(oid: go.Slice<go.UInt64>): (go.Result<go.crypto.x509.OID>);
    @:native("ParseCRL") static function parseCRL(crlBytes: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.x509.pkix.CertificateList>>);
    @:native("ParseCertificate") static function parseCertificate(der: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.x509.Certificate>>);
    @:native("ParseCertificateRequest") static function parseCertificateRequest(asn1Data: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.x509.CertificateRequest>>);
    @:native("ParseCertificates") static function parseCertificates(der: go.Slice<go.Byte>): (go.Result<go.Slice<go.Pointer<go.crypto.x509.Certificate>>>);
    @:native("ParseDERCRL") static function parseDERCRL(derBytes: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.x509.pkix.CertificateList>>);
    @:native("ParseECPrivateKey") static function parseECPrivateKey(der: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.ecdsa.PrivateKey>>);
    @:native("ParseOID") static function parseOID(oid: String): (go.Result<go.crypto.x509.OID>);
    @:native("ParsePKCS1PrivateKey") static function parsePKCS1PrivateKey(der: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.rsa.PrivateKey>>);
    @:native("ParsePKCS1PublicKey") static function parsePKCS1PublicKey(der: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.rsa.PublicKey>>);
    @:native("ParsePKCS8PrivateKey") static function parsePKCS8PrivateKey(der: go.Slice<go.Byte>): (go.Result<Dynamic>);
    @:native("ParsePKIXPublicKey") static function parsePKIXPublicKey(derBytes: go.Slice<go.Byte>): (go.Result<Dynamic>);
    @:native("ParseRevocationList") static function parseRevocationList(der: go.Slice<go.Byte>): (go.Result<go.Pointer<go.crypto.x509.RevocationList>>);
    @:native("SetFallbackRoots") static function setFallbackRoots(roots: go.Pointer<go.crypto.x509.CertPool>): Void;
    @:native("SystemCertPool") static function systemCertPool(): (go.Result<go.Pointer<go.crypto.x509.CertPool>>);

}