package go.crypto;

@:go.Type({ name: "x509", instanceName: "x509.x509", imports: ["crypto/x509"] })
extern class X509 {

    @:native("CANotAuthorizedForExtKeyUsage") static var CANotAuthorizedForExtKeyUsage: go.crypto.x509.InvalidReason;
    @:native("CANotAuthorizedForThisName") static var CANotAuthorizedForThisName: go.crypto.x509.InvalidReason;
    @:native("DSA") static var DSA: go.crypto.x509.PublicKeyAlgorithm;
    @:native("DSAWithSHA1") static var DSAWithSHA1: go.crypto.x509.SignatureAlgorithm;
    @:native("DSAWithSHA256") static var DSAWithSHA256: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSA") static var ECDSA: go.crypto.x509.PublicKeyAlgorithm;
    @:native("ECDSAWithSHA1") static var ECDSAWithSHA1: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSAWithSHA256") static var ECDSAWithSHA256: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSAWithSHA384") static var ECDSAWithSHA384: go.crypto.x509.SignatureAlgorithm;
    @:native("ECDSAWithSHA512") static var ECDSAWithSHA512: go.crypto.x509.SignatureAlgorithm;
    @:native("Ed25519") static var Ed25519: go.crypto.x509.PublicKeyAlgorithm;
    @:native("Expired") static var Expired: go.crypto.x509.InvalidReason;
    @:native("ExtKeyUsageAny") static var ExtKeyUsageAny: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageClientAuth") static var ExtKeyUsageClientAuth: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageCodeSigning") static var ExtKeyUsageCodeSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageEmailProtection") static var ExtKeyUsageEmailProtection: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageIPSECEndSystem") static var ExtKeyUsageIPSECEndSystem: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageIPSECTunnel") static var ExtKeyUsageIPSECTunnel: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageIPSECUser") static var ExtKeyUsageIPSECUser: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageMicrosoftCommercialCodeSigning") static var ExtKeyUsageMicrosoftCommercialCodeSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageMicrosoftKernelCodeSigning") static var ExtKeyUsageMicrosoftKernelCodeSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageMicrosoftServerGatedCrypto") static var ExtKeyUsageMicrosoftServerGatedCrypto: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageNetscapeServerGatedCrypto") static var ExtKeyUsageNetscapeServerGatedCrypto: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageOCSPSigning") static var ExtKeyUsageOCSPSigning: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageServerAuth") static var ExtKeyUsageServerAuth: go.crypto.x509.ExtKeyUsage;
    @:native("ExtKeyUsageTimeStamping") static var ExtKeyUsageTimeStamping: go.crypto.x509.ExtKeyUsage;
    @:native("IncompatibleUsage") static var IncompatibleUsage: go.crypto.x509.InvalidReason;
    @:native("KeyUsageCRLSign") static var KeyUsageCRLSign: go.crypto.x509.KeyUsage;
    @:native("KeyUsageCertSign") static var KeyUsageCertSign: go.crypto.x509.KeyUsage;
    @:native("KeyUsageContentCommitment") static var KeyUsageContentCommitment: go.crypto.x509.KeyUsage;
    @:native("KeyUsageDataEncipherment") static var KeyUsageDataEncipherment: go.crypto.x509.KeyUsage;
    @:native("KeyUsageDecipherOnly") static var KeyUsageDecipherOnly: go.crypto.x509.KeyUsage;
    @:native("KeyUsageDigitalSignature") static var KeyUsageDigitalSignature: go.crypto.x509.KeyUsage;
    @:native("KeyUsageEncipherOnly") static var KeyUsageEncipherOnly: go.crypto.x509.KeyUsage;
    @:native("KeyUsageKeyAgreement") static var KeyUsageKeyAgreement: go.crypto.x509.KeyUsage;
    @:native("KeyUsageKeyEncipherment") static var KeyUsageKeyEncipherment: go.crypto.x509.KeyUsage;
    @:native("MD2WithRSA") static var MD2WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("MD5WithRSA") static var MD5WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("NameConstraintsWithoutSANs") static var NameConstraintsWithoutSANs: go.crypto.x509.InvalidReason;
    @:native("NameMismatch") static var NameMismatch: go.crypto.x509.InvalidReason;
    @:native("NoValidChains") static var NoValidChains: go.crypto.x509.InvalidReason;
    @:native("NotAuthorizedToSign") static var NotAuthorizedToSign: go.crypto.x509.InvalidReason;
    @:native("PEMCipher3DES") static var PEMCipher3DES: go.crypto.x509.PEMCipher;
    @:native("PEMCipherAES128") static var PEMCipherAES128: go.crypto.x509.PEMCipher;
    @:native("PEMCipherAES192") static var PEMCipherAES192: go.crypto.x509.PEMCipher;
    @:native("PEMCipherAES256") static var PEMCipherAES256: go.crypto.x509.PEMCipher;
    @:native("PEMCipherDES") static var PEMCipherDES: go.crypto.x509.PEMCipher;
    @:native("PureEd25519") static var PureEd25519: go.crypto.x509.SignatureAlgorithm;
    @:native("RSA") static var RSA: go.crypto.x509.PublicKeyAlgorithm;
    @:native("SHA1WithRSA") static var SHA1WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA256WithRSA") static var SHA256WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA256WithRSAPSS") static var SHA256WithRSAPSS: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA384WithRSA") static var SHA384WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA384WithRSAPSS") static var SHA384WithRSAPSS: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA512WithRSA") static var SHA512WithRSA: go.crypto.x509.SignatureAlgorithm;
    @:native("SHA512WithRSAPSS") static var SHA512WithRSAPSS: go.crypto.x509.SignatureAlgorithm;
    @:native("TooManyConstraints") static var TooManyConstraints: go.crypto.x509.InvalidReason;
    @:native("TooManyIntermediates") static var TooManyIntermediates: go.crypto.x509.InvalidReason;
    @:native("UnconstrainedName") static var UnconstrainedName: go.crypto.x509.InvalidReason;
    @:native("UnknownPublicKeyAlgorithm") static var UnknownPublicKeyAlgorithm: go.crypto.x509.PublicKeyAlgorithm;
    @:native("UnknownSignatureAlgorithm") static var UnknownSignatureAlgorithm: go.crypto.x509.SignatureAlgorithm;

    @:native("CreateCertificate") static function createCertificate(rand: go.io.Reader, template: go.Pointer<go.crypto.x509.Certificate>, parent: go.Pointer<go.crypto.x509.Certificate>, pub: Dynamic, priv: Dynamic): go.Result<go.Slice<go.Byte>>;
    @:native("CreateCertificateRequest") static function createCertificateRequest(rand: go.io.Reader, template: go.Pointer<go.crypto.x509.CertificateRequest>, priv: Dynamic): go.Result<go.Slice<go.Byte>>;
    @:native("CreateRevocationList") static function createRevocationList(rand: go.io.Reader, template: go.Pointer<go.crypto.x509.RevocationList>, issuer: go.Pointer<go.crypto.x509.Certificate>, priv: go.crypto.Signer): go.Result<go.Slice<go.Byte>>;
    @:native("DecryptPEMBlock") static function decryptPEMBlock(b: go.Pointer<go.encoding.pem.Block>, password: go.Slice<go.Byte>): go.Result<go.Slice<go.Byte>>;
    @:native("EncryptPEMBlock") static function encryptPEMBlock(rand: go.io.Reader, blockType: String, data: go.Slice<go.Byte>, password: go.Slice<go.Byte>, alg: go.crypto.x509.PEMCipher): go.Result<go.Pointer<go.encoding.pem.Block>>;
    @:native("IsEncryptedPEMBlock") static function isEncryptedPEMBlock(b: go.Pointer<go.encoding.pem.Block>): Bool;
    @:native("MarshalECPrivateKey") static function marshalECPrivateKey(key: go.Pointer<go.crypto.ecdsa.PrivateKey>): go.Result<go.Slice<go.Byte>>;
    @:native("MarshalPKCS1PrivateKey") static function marshalPKCS1PrivateKey(key: go.Pointer<go.crypto.rsa.PrivateKey>): go.Slice<go.Byte>;
    @:native("MarshalPKCS1PublicKey") static function marshalPKCS1PublicKey(key: go.Pointer<go.crypto.rsa.PublicKey>): go.Slice<go.Byte>;
    @:native("MarshalPKCS8PrivateKey") static function marshalPKCS8PrivateKey(key: Dynamic): go.Result<go.Slice<go.Byte>>;
    @:native("MarshalPKIXPublicKey") static function marshalPKIXPublicKey(pub: Dynamic): go.Result<go.Slice<go.Byte>>;
    @:native("NewCertPool") static function newCertPool(): go.Pointer<go.crypto.x509.CertPool>;
    @:native("OIDFromASN1OID") static function oIDFromASN1OID(asn1OID: go.encoding.asn1.ObjectIdentifier): go.Result<go.crypto.x509.OID>;
    @:native("OIDFromInts") static function oIDFromInts(oid: go.Slice<go.UInt64>): go.Result<go.crypto.x509.OID>;
    @:native("ParseCRL") static function parseCRL(crlBytes: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.x509.pkix.CertificateList>>;
    @:native("ParseCertificate") static function parseCertificate(der: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.x509.Certificate>>;
    @:native("ParseCertificateRequest") static function parseCertificateRequest(asn1Data: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.x509.CertificateRequest>>;
    @:native("ParseCertificates") static function parseCertificates(der: go.Slice<go.Byte>): go.Result<go.Slice<go.Pointer<go.crypto.x509.Certificate>>>;
    @:native("ParseDERCRL") static function parseDERCRL(derBytes: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.x509.pkix.CertificateList>>;
    @:native("ParseECPrivateKey") static function parseECPrivateKey(der: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.ecdsa.PrivateKey>>;
    @:native("ParseOID") static function parseOID(oid: String): go.Result<go.crypto.x509.OID>;
    @:native("ParsePKCS1PrivateKey") static function parsePKCS1PrivateKey(der: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.rsa.PrivateKey>>;
    @:native("ParsePKCS1PublicKey") static function parsePKCS1PublicKey(der: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.rsa.PublicKey>>;
    @:native("ParsePKCS8PrivateKey") static function parsePKCS8PrivateKey(der: go.Slice<go.Byte>): go.Result<Dynamic>;
    @:native("ParsePKIXPublicKey") static function parsePKIXPublicKey(derBytes: go.Slice<go.Byte>): go.Result<Dynamic>;
    @:native("ParseRevocationList") static function parseRevocationList(der: go.Slice<go.Byte>): go.Result<go.Pointer<go.crypto.x509.RevocationList>>;
    @:native("SetFallbackRoots") static function setFallbackRoots(roots: go.Pointer<go.crypto.x509.CertPool>): Void;
    @:native("SystemCertPool") static function systemCertPool(): go.Result<go.Pointer<go.crypto.x509.CertPool>>;

}