package go.bufio;

/**
    Scanner provides a convenient interface for reading data such as
    a file of newline-delimited lines of text. Successive calls to
    the [Scanner.Scan] method will step through the 'tokens' of a file, skipping
    the bytes between the tokens. The specification of a token is
    defined by a split function of type [SplitFunc]; the default split
    function breaks the input into lines with line termination stripped. [Scanner.Split]
    functions are defined in this package for scanning a file into
    lines, bytes, UTF-8-encoded runes, and space-delimited words. The
    client may instead provide a custom split function.
    
    Scanning stops unrecoverably at EOF, the first I/O error, or a token too
    large to fit in the [Scanner.Buffer]. When a scan stops, the reader may have
    advanced arbitrarily far past the last token. Programs that need more
    control over error handling or large tokens, or must run sequential scans
    on a reader, should use [bufio.Reader] instead.
**/
@:structInit
@:go.Type({ name: "Scanner", instanceName: "bufio.Scanner", imports: ["bufio"] })
extern class Scanner {

    /**
        Buffer controls memory allocation by the Scanner.
        It sets the initial buffer to use when scanning
        and the maximum size of buffer that may be allocated during scanning.
        The contents of the buffer are ignored.
        
        The maximum token size must be less than the larger of max and cap(buf).
        If max <= cap(buf), [Scanner.Scan] will use this buffer only and do no allocation.
        
        By default, [Scanner.Scan] uses an internal buffer and sets the
        maximum token size to [MaxScanTokenSize].
        
        Buffer panics if it is called after scanning has started.
    **/
    @:native("Buffer") function buffer(buf: go.Slice<go.Byte>, max: go.GoInt): Void;
    /**
        Bytes returns the most recent token generated by a call to [Scanner.Scan].
        The underlying array may point to data that will be overwritten
        by a subsequent call to Scan. It does no allocation.
    **/
    @:native("Bytes") function bytes(): (go.Slice<go.Byte>);
    /**
        Err returns the first non-EOF error that was encountered by the [Scanner].
    **/
    @:native("Err") function err(): (go.Error);
    /**
        Scan advances the [Scanner] to the next token, which will then be
        available through the [Scanner.Bytes] or [Scanner.Text] method. It returns false when
        there are no more tokens, either by reaching the end of the input or an error.
        After Scan returns false, the [Scanner.Err] method will return any error that
        occurred during scanning, except that if it was [io.EOF], [Scanner.Err]
        will return nil.
        Scan panics if the split function returns too many empty
        tokens without advancing the input. This is a common error mode for
        scanners.
    **/
    @:native("Scan") function scan(): (Bool);
    /**
        Split sets the split function for the [Scanner].
        The default split function is [ScanLines].
        
        Split panics if it is called after scanning has started.
    **/
    @:native("Split") function split(split: go.bufio.SplitFunc): Void;
    /**
        Text returns the most recent token generated by a call to [Scanner.Scan]
        as a newly allocated string holding its bytes.
    **/
    @:native("Text") function text(): (String);

}