package go.golang_org.x.tools.go.packages;

/**
    ErrorKind describes the source of the error, allowing the user to
    differentiate between errors generated by the driver, the parser, or the
    type-checker.
**/
@:go.Type({ name: "ErrorKind", instanceName: "packages.ErrorKind", imports: ["golang.org/x/tools/go/packages"] })
extern typedef ErrorKind = go.GoInt