package go.math.big;

/**
    A nonzero finite Float represents a multi-precision floating point number
    
    	sign × mantissa × 2**exponent
    
    with 0.5 <= mantissa < 1.0, and MinExp <= exponent <= MaxExp.
    A Float may also be zero (+0, -0) or infinite (+Inf, -Inf).
    All Floats are ordered, and the ordering of two Floats x and y
    is defined by x.Cmp(y).
    
    Each Float value also has a precision, rounding mode, and accuracy.
    The precision is the maximum number of mantissa bits available to
    represent the value. The rounding mode specifies how a result should
    be rounded to fit into the mantissa bits, and accuracy describes the
    rounding error with respect to the exact result.
    
    Unless specified otherwise, all operations (including setters) that
    specify a *Float variable for the result (usually via the receiver
    with the exception of [Float.MantExp]), round the numeric result according
    to the precision and rounding mode of the result variable.
    
    If the provided result precision is 0 (see below), it is set to the
    precision of the argument with the largest precision value before any
    rounding takes place, and the rounding mode remains unchanged. Thus,
    uninitialized Floats provided as result arguments will have their
    precision set to a reasonable value determined by the operands, and
    their mode is the zero value for RoundingMode (ToNearestEven).
    
    By setting the desired precision to 24 or 53 and using matching rounding
    mode (typically [ToNearestEven]), Float operations produce the same results
    as the corresponding float32 or float64 IEEE 754 arithmetic for operands
    that correspond to normal (i.e., not denormal) float32 or float64 numbers.
    Exponent underflow and overflow lead to a 0 or an Infinity for different
    values than IEEE 754 because Float exponents have a much larger range.
    
    The zero (uninitialized) value for a Float is ready to use and represents
    the number +0.0 exactly, with precision 0 and rounding mode [ToNearestEven].
    
    Operations always take pointer arguments (*Float) rather
    than Float values, and each unique Float value requires
    its own unique *Float pointer. To "copy" a Float value,
    an existing (or newly allocated) Float must be set to
    a new value using the [Float.Set] method; shallow copies
    of Floats are not supported and may lead to errors.
**/
@:structInit
@:go.Type({ name: "Float", instanceName: "big.Float", imports: ["math/big"] })
extern class Float {

    /**
        Abs sets z to the (possibly rounded) value |x| (the absolute value of x)
        and returns z.
    **/
    @:native("Abs") function abs(x: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        Acc returns the accuracy of x produced by the most recent
        operation, unless explicitly documented otherwise by that
        operation.
    **/
    @:native("Acc") function acc(): (go.math.big.Accuracy);
    /**
        Add sets z to the rounded sum x+y and returns z. If z's precision is 0,
        it is changed to the larger of x's or y's precision before the operation.
        Rounding is performed according to z's precision and rounding mode; and
        z's accuracy reports the result error relative to the exact (not rounded)
        result. Add panics with [ErrNaN] if x and y are infinities with opposite
        signs. The value of z is undefined in that case.
    **/
    @:native("Add") function add(x: go.Pointer<go.math.big.Float>, y: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        Append appends to buf the string form of the floating-point number x,
        as generated by x.Text, and returns the extended buffer.
    **/
    @:native("Append") function append(buf: go.Slice<go.Byte>, fmt: go.Byte, prec: go.GoInt): (go.Slice<go.Byte>);
    /**
        AppendText implements the [encoding.TextAppender] interface.
        Only the [Float] value is marshaled (in full precision), other
        attributes such as precision or accuracy are ignored.
    **/
    @:native("AppendText") function appendText(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        Cmp compares x and y and returns:
          - -1 if x < y;
          - 0 if x == y (incl. -0 == 0, -Inf == -Inf, and +Inf == +Inf);
          - +1 if x > y.
    **/
    @:native("Cmp") function cmp(y: go.Pointer<go.math.big.Float>): (go.GoInt);
    /**
        Copy sets z to x, with the same precision, rounding mode, and accuracy as x.
        Copy returns z. If x and z are identical, Copy is a no-op.
    **/
    @:native("Copy") function copy(x: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        Float32 returns the float32 value nearest to x. If x is too small to be
        represented by a float32 (|x| < [math.SmallestNonzeroFloat32]), the result
        is (0, [Below]) or (-0, [Above]), respectively, depending on the sign of x.
        If x is too large to be represented by a float32 (|x| > [math.MaxFloat32]),
        the result is (+Inf, [Above]) or (-Inf, [Below]), depending on the sign of x.
    **/
    @:go.Tuple("p0", "p1") @:native("Float32") function float32(): (go.Tuple<{ p0: go.Float32, p1: go.math.big.Accuracy }>);
    /**
        Float64 returns the float64 value nearest to x. If x is too small to be
        represented by a float64 (|x| < [math.SmallestNonzeroFloat64]), the result
        is (0, [Below]) or (-0, [Above]), respectively, depending on the sign of x.
        If x is too large to be represented by a float64 (|x| > [math.MaxFloat64]),
        the result is (+Inf, [Above]) or (-Inf, [Below]), depending on the sign of x.
    **/
    @:go.Tuple("p0", "p1") @:native("Float64") function float64(): (go.Tuple<{ p0: Float, p1: go.math.big.Accuracy }>);
    /**
        Format implements [fmt.Formatter]. It accepts all the regular
        formats for floating-point numbers ('b', 'e', 'E', 'f', 'F',
        'g', 'G', 'x') as well as 'p' and 'v'. See (*Float).Text for the
        interpretation of 'p'. The 'v' format is handled like 'g'.
        Format also supports specification of the minimum precision
        in digits, the output field width, as well as the format flags
        '+' and ' ' for sign control, '0' for space or zero padding,
        and '-' for left or right justification. See the fmt package
        for details.
    **/
    @:native("Format") function format(s: go.fmt.State, format: go.Rune): Void;
    /**
        GobDecode implements the [encoding/gob.GobDecoder] interface.
        The result is rounded per the precision and rounding mode of
        z unless z's precision is 0, in which case z is set exactly
        to the decoded value.
    **/
    @:native("GobDecode") function gobDecode(buf: go.Slice<go.Byte>): (go.Error);
    /**
        GobEncode implements the [encoding/gob.GobEncoder] interface.
        The [Float] value and all its attributes (precision,
        rounding mode, accuracy) are marshaled.
    **/
    @:native("GobEncode") function gobEncode(): (go.Result<go.Slice<go.Byte>>);
    /**
        Int returns the result of truncating x towards zero;
        or nil if x is an infinity.
        The result is [Exact] if x.IsInt(); otherwise it is [Below]
        for x > 0, and [Above] for x < 0.
        If a non-nil *[Int] argument z is provided, [Int] stores
        the result in z instead of allocating a new [Int].
    **/
    @:go.Tuple("p0", "p1") @:native("Int") function int(z: go.Pointer<go.math.big.Int>): (go.Tuple<{ p0: go.Pointer<go.math.big.Int>, p1: go.math.big.Accuracy }>);
    /**
        Int64 returns the integer resulting from truncating x towards zero.
        If [math.MinInt64] <= x <= [math.MaxInt64], the result is [Exact] if x is
        an integer, and [Above] (x < 0) or [Below] (x > 0) otherwise.
        The result is ([math.MinInt64], [Above]) for x < [math.MinInt64],
        and ([math.MaxInt64], [Below]) for x > [math.MaxInt64].
    **/
    @:go.Tuple("p0", "p1") @:native("Int64") function int64(): (go.Tuple<{ p0: go.Int64, p1: go.math.big.Accuracy }>);
    /**
        IsInf reports whether x is +Inf or -Inf.
    **/
    @:native("IsInf") function isInf(): (Bool);
    /**
        IsInt reports whether x is an integer.
        ±Inf values are not integers.
    **/
    @:native("IsInt") function isInt(): (Bool);
    /**
        MantExp breaks x into its mantissa and exponent components
        and returns the exponent. If a non-nil mant argument is
        provided its value is set to the mantissa of x, with the
        same precision and rounding mode as x. The components
        satisfy x == mant × 2**exp, with 0.5 <= |mant| < 1.0.
        Calling MantExp with a nil argument is an efficient way to
        get the exponent of the receiver.
        
        Special cases are:
        
        	(  ±0).MantExp(mant) = 0, with mant set to   ±0
        	(±Inf).MantExp(mant) = 0, with mant set to ±Inf
        
        x and mant may be the same in which case x is set to its
        mantissa value.
    **/
    @:native("MantExp") function mantExp(mant: go.Pointer<go.math.big.Float>): (go.GoInt);
    /**
        MarshalText implements the [encoding.TextMarshaler] interface.
        Only the [Float] value is marshaled (in full precision), other
        attributes such as precision or accuracy are ignored.
    **/
    @:native("MarshalText") function marshalText(): (go.Result<go.Slice<go.Byte>>);
    /**
        MinPrec returns the minimum precision required to represent x exactly
        (i.e., the smallest prec before x.SetPrec(prec) would start rounding x).
        The result is 0 for |x| == 0 and |x| == Inf.
    **/
    @:native("MinPrec") function minPrec(): (go.GoUInt);
    /**
        Mode returns the rounding mode of x.
    **/
    @:native("Mode") function mode(): (go.math.big.RoundingMode);
    /**
        Mul sets z to the rounded product x*y and returns z.
        Precision, rounding, and accuracy reporting are as for [Float.Add].
        Mul panics with [ErrNaN] if one operand is zero and the other
        operand an infinity. The value of z is undefined in that case.
    **/
    @:native("Mul") function mul(x: go.Pointer<go.math.big.Float>, y: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        Neg sets z to the (possibly rounded) value of x with its sign negated,
        and returns z.
    **/
    @:native("Neg") function neg(x: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        Parse parses s which must contain a text representation of a floating-
        point number with a mantissa in the given conversion base (the exponent
        is always a decimal number), or a string representing an infinite value.
        
        For base 0, an underscore character “_” may appear between a base
        prefix and an adjacent digit, and between successive digits; such
        underscores do not change the value of the number, or the returned
        digit count. Incorrect placement of underscores is reported as an
        error if there are no other errors. If base != 0, underscores are
        not recognized and thus terminate scanning like any other character
        that is not a valid radix point or digit.
        
        It sets z to the (possibly rounded) value of the corresponding floating-
        point value, and returns z, the actual base b, and an error err, if any.
        The entire string (not just a prefix) must be consumed for success.
        If z's precision is 0, it is changed to 64 before rounding takes effect.
        The number must be of the form:
        
        	number    = [ sign ] ( float | "inf" | "Inf" ) .
        	sign      = "+" | "-" .
        	float     = ( mantissa | prefix pmantissa ) [ exponent ] .
        	prefix    = "0" [ "b" | "B" | "o" | "O" | "x" | "X" ] .
        	mantissa  = digits "." [ digits ] | digits | "." digits .
        	pmantissa = [ "_" ] digits "." [ digits ] | [ "_" ] digits | "." digits .
        	exponent  = ( "e" | "E" | "p" | "P" ) [ sign ] digits .
        	digits    = digit { [ "_" ] digit } .
        	digit     = "0" ... "9" | "a" ... "z" | "A" ... "Z" .
        
        The base argument must be 0, 2, 8, 10, or 16. Providing an invalid base
        argument will lead to a run-time panic.
        
        For base 0, the number prefix determines the actual base: A prefix of
        “0b” or “0B” selects base 2, “0o” or “0O” selects base 8, and
        “0x” or “0X” selects base 16. Otherwise, the actual base is 10 and
        no prefix is accepted. The octal prefix "0" is not supported (a leading
        "0" is simply considered a "0").
        
        A "p" or "P" exponent indicates a base 2 (rather than base 10) exponent;
        for instance, "0x1.fffffffffffffp1023" (using base 0) represents the
        maximum float64 value. For hexadecimal mantissae, the exponent character
        must be one of 'p' or 'P', if present (an "e" or "E" exponent indicator
        cannot be distinguished from a mantissa digit).
        
        The returned *Float f is nil and the value of z is valid but not
        defined if an error is reported.
    **/
    @:go.Tuple("f", "b", "err") @:native("Parse") function parse(s: String, base: go.GoInt): (go.Tuple<{ f: go.Pointer<go.math.big.Float>, b: go.GoInt, err: go.Error }>);
    /**
        Prec returns the mantissa precision of x in bits.
        The result may be 0 for |x| == 0 and |x| == Inf.
    **/
    @:native("Prec") function prec(): (go.GoUInt);
    /**
        Quo sets z to the rounded quotient x/y and returns z.
        Precision, rounding, and accuracy reporting are as for [Float.Add].
        Quo panics with [ErrNaN] if both operands are zero or infinities.
        The value of z is undefined in that case.
    **/
    @:native("Quo") function quo(x: go.Pointer<go.math.big.Float>, y: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        Rat returns the rational number corresponding to x;
        or nil if x is an infinity.
        The result is [Exact] if x is not an Inf.
        If a non-nil *[Rat] argument z is provided, [Rat] stores
        the result in z instead of allocating a new [Rat].
    **/
    @:go.Tuple("p0", "p1") @:native("Rat") function rat(z: go.Pointer<go.math.big.Rat>): (go.Tuple<{ p0: go.Pointer<go.math.big.Rat>, p1: go.math.big.Accuracy }>);
    /**
        Scan is a support routine for [fmt.Scanner]; it sets z to the value of
        the scanned number. It accepts formats whose verbs are supported by
        [fmt.Scan] for floating point values, which are:
        'b' (binary), 'e', 'E', 'f', 'F', 'g' and 'G'.
        Scan doesn't handle ±Inf.
    **/
    @:native("Scan") function scan(s: go.fmt.ScanState, ch: go.Rune): (go.Error);
    /**
        Set sets z to the (possibly rounded) value of x and returns z.
        If z's precision is 0, it is changed to the precision of x
        before setting z (and rounding will have no effect).
        Rounding is performed according to z's precision and rounding
        mode; and z's accuracy reports the result error relative to the
        exact (not rounded) result.
    **/
    @:native("Set") function set(x: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        SetFloat64 sets z to the (possibly rounded) value of x and returns z.
        If z's precision is 0, it is changed to 53 (and rounding will have
        no effect). SetFloat64 panics with [ErrNaN] if x is a NaN.
    **/
    @:native("SetFloat64") function setFloat64(x: Float): (go.Pointer<go.math.big.Float>);
    /**
        SetInf sets z to the infinite Float -Inf if signbit is
        set, or +Inf if signbit is not set, and returns z. The
        precision of z is unchanged and the result is always
        [Exact].
    **/
    @:native("SetInf") function setInf(signbit: Bool): (go.Pointer<go.math.big.Float>);
    /**
        SetInt sets z to the (possibly rounded) value of x and returns z.
        If z's precision is 0, it is changed to the larger of x.BitLen()
        or 64 (and rounding will have no effect).
    **/
    @:native("SetInt") function setInt(x: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Float>);
    /**
        SetInt64 sets z to the (possibly rounded) value of x and returns z.
        If z's precision is 0, it is changed to 64 (and rounding will have
        no effect).
    **/
    @:native("SetInt64") function setInt64(x: go.Int64): (go.Pointer<go.math.big.Float>);
    /**
        SetMantExp sets z to mant × 2**exp and returns z.
        The result z has the same precision and rounding mode
        as mant. SetMantExp is an inverse of [Float.MantExp] but does
        not require 0.5 <= |mant| < 1.0. Specifically, for a
        given x of type *[Float], SetMantExp relates to [Float.MantExp]
        as follows:
        
        	mant := new(Float)
        	new(Float).SetMantExp(mant, x.MantExp(mant)).Cmp(x) == 0
        
        Special cases are:
        
        	z.SetMantExp(  ±0, exp) =   ±0
        	z.SetMantExp(±Inf, exp) = ±Inf
        
        z and mant may be the same in which case z's exponent
        is set to exp.
    **/
    @:native("SetMantExp") function setMantExp(mant: go.Pointer<go.math.big.Float>, exp: go.GoInt): (go.Pointer<go.math.big.Float>);
    /**
        SetMode sets z's rounding mode to mode and returns an exact z.
        z remains unchanged otherwise.
        z.SetMode(z.Mode()) is a cheap way to set z's accuracy to [Exact].
    **/
    @:native("SetMode") function setMode(mode: go.math.big.RoundingMode): (go.Pointer<go.math.big.Float>);
    /**
        SetPrec sets z's precision to prec and returns the (possibly) rounded
        value of z. Rounding occurs according to z's rounding mode if the mantissa
        cannot be represented in prec bits without loss of precision.
        SetPrec(0) maps all finite values to ±0; infinite values remain unchanged.
        If prec > [MaxPrec], it is set to [MaxPrec].
    **/
    @:native("SetPrec") function setPrec(prec: go.GoUInt): (go.Pointer<go.math.big.Float>);
    /**
        SetRat sets z to the (possibly rounded) value of x and returns z.
        If z's precision is 0, it is changed to the largest of a.BitLen(),
        b.BitLen(), or 64; with x = a/b.
    **/
    @:native("SetRat") function setRat(x: go.Pointer<go.math.big.Rat>): (go.Pointer<go.math.big.Float>);
    /**
        SetString sets z to the value of s and returns z and a boolean indicating
        success. s must be a floating-point number of the same format as accepted
        by [Float.Parse], with base argument 0. The entire string (not just a prefix) must
        be valid for success. If the operation failed, the value of z is undefined
        but the returned value is nil.
    **/
    @:go.Tuple("p0", "p1") @:native("SetString") function setString(s: String): (go.Tuple<{ p0: go.Pointer<go.math.big.Float>, p1: Bool }>);
    /**
        SetUint64 sets z to the (possibly rounded) value of x and returns z.
        If z's precision is 0, it is changed to 64 (and rounding will have
        no effect).
    **/
    @:native("SetUint64") function setUint64(x: go.UInt64): (go.Pointer<go.math.big.Float>);
    /**
        Sign returns:
          - -1 if x < 0;
          - 0 if x is ±0;
          - +1 if x > 0.
    **/
    @:native("Sign") function sign(): (go.GoInt);
    /**
        Signbit reports whether x is negative or negative zero.
    **/
    @:native("Signbit") function signbit(): (Bool);
    /**
        Sqrt sets z to the rounded square root of x, and returns it.
        
        If z's precision is 0, it is changed to x's precision before the
        operation. Rounding is performed according to z's precision and
        rounding mode, but z's accuracy is not computed. Specifically, the
        result of z.Acc() is undefined.
        
        The function panics if z < 0. The value of z is undefined in that
        case.
    **/
    @:native("Sqrt") function sqrt(x: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        String formats x like x.Text('g', 10).
        (String must be called explicitly, [Float.Format] does not support %s verb.)
    **/
    @:native("String") function string(): (String);
    /**
        Sub sets z to the rounded difference x-y and returns z.
        Precision, rounding, and accuracy reporting are as for [Float.Add].
        Sub panics with [ErrNaN] if x and y are infinities with equal
        signs. The value of z is undefined in that case.
    **/
    @:native("Sub") function sub(x: go.Pointer<go.math.big.Float>, y: go.Pointer<go.math.big.Float>): (go.Pointer<go.math.big.Float>);
    /**
        Text converts the floating-point number x to a string according
        to the given format and precision prec. The format is one of:
        
        	'e'	-d.dddde±dd, decimal exponent, at least two (possibly 0) exponent digits
        	'E'	-d.ddddE±dd, decimal exponent, at least two (possibly 0) exponent digits
        	'f'	-ddddd.dddd, no exponent
        	'g'	like 'e' for large exponents, like 'f' otherwise
        	'G'	like 'E' for large exponents, like 'f' otherwise
        	'x'	-0xd.dddddp±dd, hexadecimal mantissa, decimal power of two exponent
        	'p'	-0x.dddp±dd, hexadecimal mantissa, decimal power of two exponent (non-standard)
        	'b'	-ddddddp±dd, decimal mantissa, decimal power of two exponent (non-standard)
        
        For the power-of-two exponent formats, the mantissa is printed in normalized form:
        
        	'x'	hexadecimal mantissa in [1, 2), or 0
        	'p'	hexadecimal mantissa in [½, 1), or 0
        	'b'	decimal integer mantissa using x.Prec() bits, or 0
        
        Note that the 'x' form is the one used by most other languages and libraries.
        
        If format is a different character, Text returns a "%" followed by the
        unrecognized format character.
        
        The precision prec controls the number of digits (excluding the exponent)
        printed by the 'e', 'E', 'f', 'g', 'G', and 'x' formats.
        For 'e', 'E', 'f', and 'x', it is the number of digits after the decimal point.
        For 'g' and 'G' it is the total number of digits. A negative precision selects
        the smallest number of decimal digits necessary to identify the value x uniquely
        using x.Prec() mantissa bits.
        The prec value is ignored for the 'b' and 'p' formats.
    **/
    @:native("Text") function text(format: go.Byte, prec: go.GoInt): (String);
    /**
        Uint64 returns the unsigned integer resulting from truncating x
        towards zero. If 0 <= x <= [math.MaxUint64], the result is [Exact]
        if x is an integer and [Below] otherwise.
        The result is (0, [Above]) for x < 0, and ([math.MaxUint64], [Below])
        for x > [math.MaxUint64].
    **/
    @:go.Tuple("p0", "p1") @:native("Uint64") function uint64(): (go.Tuple<{ p0: go.UInt64, p1: go.math.big.Accuracy }>);
    /**
        UnmarshalText implements the [encoding.TextUnmarshaler] interface.
        The result is rounded per the precision and rounding mode of z.
        If z's precision is 0, it is changed to 64 before rounding takes
        effect.
    **/
    @:native("UnmarshalText") function unmarshalText(text: go.Slice<go.Byte>): (go.Error);

}