package go.math.big;

/**
    An Int represents a signed multi-precision integer.
    The zero value for an Int represents the value 0.
    
    Operations always take pointer arguments (*Int) rather
    than Int values, and each unique Int value requires
    its own unique *Int pointer. To "copy" an Int value,
    an existing (or newly allocated) Int must be set to
    a new value using the [Int.Set] method; shallow copies
    of Ints are not supported and may lead to errors.
    
    Note that methods may leak the Int's value through timing side-channels.
    Because of this and because of the scope and complexity of the
    implementation, Int is not well-suited to implement cryptographic operations.
    The standard library avoids exposing non-trivial Int methods to
    attacker-controlled inputs and the determination of whether a bug in math/big
    is considered a security vulnerability might depend on the impact on the
    standard library.
**/
@:structInit
@:go.Type({ name: "Int", instanceName: "big.Int", imports: ["math/big"] })
extern class Int {

    /**
        Abs sets z to |x| (the absolute value of x) and returns z.
    **/
    @:native("Abs") function abs(x: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Add sets z to the sum x+y and returns z.
    **/
    @:native("Add") function add(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        And sets z = x & y and returns z.
    **/
    @:native("And") function and(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        AndNot sets z = x &^ y and returns z.
    **/
    @:native("AndNot") function andNot(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Append appends the string representation of x, as generated by
        x.Text(base), to buf and returns the extended buffer.
    **/
    @:native("Append") function append(buf: go.Slice<go.Byte>, base: go.GoInt): (go.Slice<go.Byte>);
    /**
        AppendText implements the [encoding.TextAppender] interface.
    **/
    @:native("AppendText") function appendText(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        Binomial sets z to the binomial coefficient C(n, k) and returns z.
    **/
    @:native("Binomial") function binomial(n: go.Int64, k: go.Int64): (go.Pointer<go.math.big.Int>);
    /**
        Bit returns the value of the i'th bit of x. That is, it
        returns (x>>i)&1. The bit index i must be >= 0.
    **/
    @:native("Bit") function bit(i: go.GoInt): (go.GoUInt);
    /**
        BitLen returns the length of the absolute value of x in bits.
        The bit length of 0 is 0.
    **/
    @:native("BitLen") function bitLen(): (go.GoInt);
    /**
        Bits provides raw (unchecked but fast) access to x by returning its
        absolute value as a little-endian [Word] slice. The result and x share
        the same underlying array.
        Bits is intended to support implementation of missing low-level [Int]
        functionality outside this package; it should be avoided otherwise.
    **/
    @:native("Bits") function bits(): (go.Slice<go.math.big.Word>);
    /**
        Bytes returns the absolute value of x as a big-endian byte slice.
        
        To use a fixed length slice, or a preallocated one, use [Int.FillBytes].
    **/
    @:native("Bytes") function bytes(): (go.Slice<go.Byte>);
    /**
        Cmp compares x and y and returns:
          - -1 if x < y;
          - 0 if x == y;
          - +1 if x > y.
    **/
    @:native("Cmp") function cmp(y: go.Pointer<go.math.big.Int>): (go.GoInt);
    /**
        CmpAbs compares the absolute values of x and y and returns:
          - -1 if |x| < |y|;
          - 0 if |x| == |y|;
          - +1 if |x| > |y|.
    **/
    @:native("CmpAbs") function cmpAbs(y: go.Pointer<go.math.big.Int>): (go.GoInt);
    /**
        Div sets z to the quotient x/y for y != 0 and returns z.
        If y == 0, a division-by-zero run-time panic occurs.
        Div implements Euclidean division (unlike Go); see [Int.DivMod] for more details.
    **/
    @:native("Div") function div(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        DivMod sets z to the quotient x div y and m to the modulus x mod y
        and returns the pair (z, m) for y != 0.
        If y == 0, a division-by-zero run-time panic occurs.
        
        DivMod implements Euclidean division and modulus (unlike Go):
        
        	q = x div y  such that
        	m = x - y*q  with 0 <= m < |y|
        
        (See Raymond T. Boute, “The Euclidean definition of the functions
        div and mod”. ACM Transactions on Programming Languages and
        Systems (TOPLAS), 14(2):127-144, New York, NY, USA, 4/1992.
        ACM press.)
        See [Int.QuoRem] for T-division and modulus (like Go).
    **/
    @:go.Tuple("p0", "p1") @:native("DivMod") function divMod(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>, m: go.Pointer<go.math.big.Int>): (go.Tuple<{ p0: go.Pointer<go.math.big.Int>, p1: go.Pointer<go.math.big.Int> }>);
    /**
        Exp sets z = x**y mod |m| (i.e. the sign of m is ignored), and returns z.
        If m == nil or m == 0, z = x**y unless y <= 0 then z = 1. If m != 0, y < 0,
        and x and m are not relatively prime, z is unchanged and nil is returned.
        
        Modular exponentiation of inputs of a particular size is not a
        cryptographically constant-time operation.
    **/
    @:native("Exp") function exp(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>, m: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        FillBytes sets buf to the absolute value of x, storing it as a zero-extended
        big-endian byte slice, and returns buf.
        
        If the absolute value of x doesn't fit in buf, FillBytes will panic.
    **/
    @:native("FillBytes") function fillBytes(buf: go.Slice<go.Byte>): (go.Slice<go.Byte>);
    /**
        Float64 returns the float64 value nearest x,
        and an indication of any rounding that occurred.
    **/
    @:go.Tuple("p0", "p1") @:native("Float64") function float64(): (go.Tuple<{ p0: Float, p1: go.math.big.Accuracy }>);
    /**
        Format implements [fmt.Formatter]. It accepts the formats
        'b' (binary), 'o' (octal with 0 prefix), 'O' (octal with 0o prefix),
        'd' (decimal), 'x' (lowercase hexadecimal), and
        'X' (uppercase hexadecimal).
        Also supported are the full suite of package fmt's format
        flags for integral types, including '+' and ' ' for sign
        control, '#' for leading zero in octal and for hexadecimal,
        a leading "0x" or "0X" for "%#x" and "%#X" respectively,
        specification of minimum digits precision, output field
        width, space or zero padding, and '-' for left or right
        justification.
    **/
    @:native("Format") function format(s: go.fmt.State, ch: go.Rune): Void;
    /**
        GCD sets z to the greatest common divisor of a and b and returns z.
        If x or y are not nil, GCD sets their value such that z = a*x + b*y.
        
        a and b may be positive, zero or negative. (Before Go 1.14 both had
        to be > 0.) Regardless of the signs of a and b, z is always >= 0.
        
        If a == b == 0, GCD sets z = x = y = 0.
        
        If a == 0 and b != 0, GCD sets z = |b|, x = 0, y = sign(b) * 1.
        
        If a != 0 and b == 0, GCD sets z = |a|, x = sign(a) * 1, y = 0.
    **/
    @:native("GCD") function GCD(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>, a: go.Pointer<go.math.big.Int>, b: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        GobDecode implements the [encoding/gob.GobDecoder] interface.
    **/
    @:native("GobDecode") function gobDecode(buf: go.Slice<go.Byte>): (go.Error);
    /**
        GobEncode implements the [encoding/gob.GobEncoder] interface.
    **/
    @:native("GobEncode") function gobEncode(): (go.Result<go.Slice<go.Byte>>);
    /**
        Int64 returns the int64 representation of x.
        If x cannot be represented in an int64, the result is undefined.
    **/
    @:native("Int64") function int64(): (go.Int64);
    /**
        IsInt64 reports whether x can be represented as an int64.
    **/
    @:native("IsInt64") function isInt64(): (Bool);
    /**
        IsUint64 reports whether x can be represented as a uint64.
    **/
    @:native("IsUint64") function isUint64(): (Bool);
    /**
        Lsh sets z = x << n and returns z.
    **/
    @:native("Lsh") function lsh(x: go.Pointer<go.math.big.Int>, n: go.GoUInt): (go.Pointer<go.math.big.Int>);
    /**
        MarshalJSON implements the [encoding/json.Marshaler] interface.
    **/
    @:native("MarshalJSON") function marshalJSON(): (go.Result<go.Slice<go.Byte>>);
    /**
        MarshalText implements the [encoding.TextMarshaler] interface.
    **/
    @:native("MarshalText") function marshalText(): (go.Result<go.Slice<go.Byte>>);
    /**
        Mod sets z to the modulus x%y for y != 0 and returns z.
        If y == 0, a division-by-zero run-time panic occurs.
        Mod implements Euclidean modulus (unlike Go); see [Int.DivMod] for more details.
    **/
    @:native("Mod") function mod(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        ModInverse sets z to the multiplicative inverse of g in the ring ℤ/nℤ
        and returns z. If g and n are not relatively prime, g has no multiplicative
        inverse in the ring ℤ/nℤ.  In this case, z is unchanged and the return value
        is nil. If n == 0, a division-by-zero run-time panic occurs.
    **/
    @:native("ModInverse") function modInverse(g: go.Pointer<go.math.big.Int>, n: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        ModSqrt sets z to a square root of x mod p if such a square root exists, and
        returns z. The modulus p must be an odd prime. If x is not a square mod p,
        ModSqrt leaves z unchanged and returns nil. This function panics if p is
        not an odd integer, its behavior is undefined if p is odd but not prime.
    **/
    @:native("ModSqrt") function modSqrt(x: go.Pointer<go.math.big.Int>, p: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Mul sets z to the product x*y and returns z.
    **/
    @:native("Mul") function mul(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        MulRange sets z to the product of all integers
        in the range [a, b] inclusively and returns z.
        If a > b (empty range), the result is 1.
    **/
    @:native("MulRange") function mulRange(a: go.Int64, b: go.Int64): (go.Pointer<go.math.big.Int>);
    /**
        Neg sets z to -x and returns z.
    **/
    @:native("Neg") function neg(x: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Not sets z = ^x and returns z.
    **/
    @:native("Not") function not(x: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Or sets z = x | y and returns z.
    **/
    @:native("Or") function or(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        ProbablyPrime reports whether x is probably prime,
        applying the Miller-Rabin test with n pseudorandomly chosen bases
        as well as a Baillie-PSW test.
        
        If x is prime, ProbablyPrime returns true.
        If x is chosen randomly and not prime, ProbablyPrime probably returns false.
        The probability of returning true for a randomly chosen non-prime is at most ¼ⁿ.
        
        ProbablyPrime is 100% accurate for inputs less than 2⁶⁴.
        See Menezes et al., Handbook of Applied Cryptography, 1997, pp. 145-149,
        and FIPS 186-4 Appendix F for further discussion of the error probabilities.
        
        ProbablyPrime is not suitable for judging primes that an adversary may
        have crafted to fool the test.
        
        As of Go 1.8, ProbablyPrime(0) is allowed and applies only a Baillie-PSW test.
        Before Go 1.8, ProbablyPrime applied only the Miller-Rabin tests, and ProbablyPrime(0) panicked.
    **/
    @:native("ProbablyPrime") function probablyPrime(n: go.GoInt): (Bool);
    /**
        Quo sets z to the quotient x/y for y != 0 and returns z.
        If y == 0, a division-by-zero run-time panic occurs.
        Quo implements truncated division (like Go); see [Int.QuoRem] for more details.
    **/
    @:native("Quo") function quo(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        QuoRem sets z to the quotient x/y and r to the remainder x%y
        and returns the pair (z, r) for y != 0.
        If y == 0, a division-by-zero run-time panic occurs.
        
        QuoRem implements T-division and modulus (like Go):
        
        	q = x/y      with the result truncated to zero
        	r = x - y*q
        
        (See Daan Leijen, “Division and Modulus for Computer Scientists”.)
        See [Int.DivMod] for Euclidean division and modulus (unlike Go).
    **/
    @:go.Tuple("p0", "p1") @:native("QuoRem") function quoRem(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>, r: go.Pointer<go.math.big.Int>): (go.Tuple<{ p0: go.Pointer<go.math.big.Int>, p1: go.Pointer<go.math.big.Int> }>);
    /**
        Rand sets z to a pseudo-random number in [0, n) and returns z.
        
        As this uses the [math/rand] package, it must not be used for
        security-sensitive work. Use [crypto/rand.Int] instead.
    **/
    @:native("Rand") function rand(rnd: go.Pointer<go.math.rand.Rand>, n: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Rem sets z to the remainder x%y for y != 0 and returns z.
        If y == 0, a division-by-zero run-time panic occurs.
        Rem implements truncated modulus (like Go); see [Int.QuoRem] for more details.
    **/
    @:native("Rem") function rem(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Rsh sets z = x >> n and returns z.
    **/
    @:native("Rsh") function rsh(x: go.Pointer<go.math.big.Int>, n: go.GoUInt): (go.Pointer<go.math.big.Int>);
    /**
        Scan is a support routine for [fmt.Scanner]; it sets z to the value of
        the scanned number. It accepts the formats 'b' (binary), 'o' (octal),
        'd' (decimal), 'x' (lowercase hexadecimal), and 'X' (uppercase hexadecimal).
    **/
    @:native("Scan") function scan(s: go.fmt.ScanState, ch: go.Rune): (go.Error);
    /**
        Set sets z to x and returns z.
    **/
    @:native("Set") function set(x: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        SetBit sets z to x, with x's i'th bit set to b (0 or 1).
        That is,
          - if b is 1, SetBit sets z = x | (1 << i);
          - if b is 0, SetBit sets z = x &^ (1 << i);
          - if b is not 0 or 1, SetBit will panic.
    **/
    @:native("SetBit") function setBit(x: go.Pointer<go.math.big.Int>, i: go.GoInt, b: go.GoUInt): (go.Pointer<go.math.big.Int>);
    /**
        SetBits provides raw (unchecked but fast) access to z by setting its
        value to abs, interpreted as a little-endian [Word] slice, and returning
        z. The result and abs share the same underlying array.
        SetBits is intended to support implementation of missing low-level [Int]
        functionality outside this package; it should be avoided otherwise.
    **/
    @:native("SetBits") function setBits(abs: go.Slice<go.math.big.Word>): (go.Pointer<go.math.big.Int>);
    /**
        SetBytes interprets buf as the bytes of a big-endian unsigned
        integer, sets z to that value, and returns z.
    **/
    @:native("SetBytes") function setBytes(buf: go.Slice<go.Byte>): (go.Pointer<go.math.big.Int>);
    /**
        SetInt64 sets z to x and returns z.
    **/
    @:native("SetInt64") function setInt64(x: go.Int64): (go.Pointer<go.math.big.Int>);
    /**
        SetString sets z to the value of s, interpreted in the given base,
        and returns z and a boolean indicating success. The entire string
        (not just a prefix) must be valid for success. If SetString fails,
        the value of z is undefined but the returned value is nil.
        
        The base argument must be 0 or a value between 2 and [MaxBase].
        For base 0, the number prefix determines the actual base: A prefix of
        “0b” or “0B” selects base 2, “0”, “0o” or “0O” selects base 8,
        and “0x” or “0X” selects base 16. Otherwise, the selected base is 10
        and no prefix is accepted.
        
        For bases <= 36, lower and upper case letters are considered the same:
        The letters 'a' to 'z' and 'A' to 'Z' represent digit values 10 to 35.
        For bases > 36, the upper case letters 'A' to 'Z' represent the digit
        values 36 to 61.
        
        For base 0, an underscore character “_” may appear between a base
        prefix and an adjacent digit, and between successive digits; such
        underscores do not change the value of the number.
        Incorrect placement of underscores is reported as an error if there
        are no other errors. If base != 0, underscores are not recognized
        and act like any other character that is not a valid digit.
    **/
    @:go.Tuple("p0", "p1") @:native("SetString") function setString(s: String, base: go.GoInt): (go.Tuple<{ p0: go.Pointer<go.math.big.Int>, p1: Bool }>);
    /**
        SetUint64 sets z to x and returns z.
    **/
    @:native("SetUint64") function setUint64(x: go.UInt64): (go.Pointer<go.math.big.Int>);
    /**
        Sign returns:
          - -1 if x < 0;
          - 0 if x == 0;
          - +1 if x > 0.
    **/
    @:native("Sign") function sign(): (go.GoInt);
    /**
        Sqrt sets z to ⌊√x⌋, the largest integer such that z² ≤ x, and returns z.
        It panics if x is negative.
    **/
    @:native("Sqrt") function sqrt(x: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        String returns the decimal representation of x as generated by
        x.Text(10).
    **/
    @:native("String") function string(): (String);
    /**
        Sub sets z to the difference x-y and returns z.
    **/
    @:native("Sub") function sub(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);
    /**
        Text returns the string representation of x in the given base.
        Base must be between 2 and 62, inclusive. The result uses the
        lower-case letters 'a' to 'z' for digit values 10 to 35, and
        the upper-case letters 'A' to 'Z' for digit values 36 to 61.
        No prefix (such as "0x") is added to the string. If x is a nil
        pointer it returns "<nil>".
    **/
    @:native("Text") function text(base: go.GoInt): (String);
    /**
        TrailingZeroBits returns the number of consecutive least significant zero
        bits of |x|.
    **/
    @:native("TrailingZeroBits") function trailingZeroBits(): (go.GoUInt);
    /**
        Uint64 returns the uint64 representation of x.
        If x cannot be represented in a uint64, the result is undefined.
    **/
    @:native("Uint64") function uint64(): (go.UInt64);
    /**
        UnmarshalJSON implements the [encoding/json.Unmarshaler] interface.
    **/
    @:native("UnmarshalJSON") function unmarshalJSON(text: go.Slice<go.Byte>): (go.Error);
    /**
        UnmarshalText implements the [encoding.TextUnmarshaler] interface.
    **/
    @:native("UnmarshalText") function unmarshalText(text: go.Slice<go.Byte>): (go.Error);
    /**
        Xor sets z = x ^ y and returns z.
    **/
    @:native("Xor") function xor(x: go.Pointer<go.math.big.Int>, y: go.Pointer<go.math.big.Int>): (go.Pointer<go.math.big.Int>);

}