package go.net.netip;

/**
    Addr represents an IPv4 or IPv6 address (with or without a scoped
    addressing zone), similar to [net.IP] or [net.IPAddr].
    
    Unlike [net.IP] or [net.IPAddr], Addr is a comparable value
    type (it supports == and can be a map key) and is immutable.
    
    The zero Addr is not a valid IP address.
    Addr{} is distinct from both 0.0.0.0 and ::.
**/
@:structInit
@:go.Type({ name: "Addr", instanceName: "netip.Addr", imports: ["net/netip"] })
extern class Addr {

    /**
        AppendBinary implements the [encoding.BinaryAppender] interface.
    **/
    @:native("AppendBinary") function appendBinary(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        AppendText implements the [encoding.TextAppender] interface,
        It is the same as [Addr.AppendTo].
    **/
    @:native("AppendText") function appendText(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        AppendTo appends a text encoding of ip,
        as generated by [Addr.MarshalText],
        to b and returns the extended buffer.
    **/
    @:native("AppendTo") function appendTo(b: go.Slice<go.Byte>): (go.Slice<go.Byte>);
    /**
        As16 returns the IP address in its 16-byte representation.
        IPv4 addresses are returned as IPv4-mapped IPv6 addresses.
        IPv6 addresses with zones are returned without their zone (use the
        [Addr.Zone] method to get it).
        The ip zero value returns all zeroes.
    **/
    @:native("As16") function as16(): (go.GoArray<go.Byte, 16>);
    /**
        As4 returns an IPv4 or IPv4-in-IPv6 address in its 4-byte representation.
        If ip is the zero [Addr] or an IPv6 address, As4 panics.
        Note that 0.0.0.0 is not the zero Addr.
    **/
    @:native("As4") function as4(): (go.GoArray<go.Byte, 4>);
    /**
        AsSlice returns an IPv4 or IPv6 address in its respective 4-byte or 16-byte representation.
    **/
    @:native("AsSlice") function asSlice(): (go.Slice<go.Byte>);
    /**
        BitLen returns the number of bits in the IP address:
        128 for IPv6, 32 for IPv4, and 0 for the zero [Addr].
        
        Note that IPv4-mapped IPv6 addresses are considered IPv6 addresses
        and therefore have bit length 128.
    **/
    @:native("BitLen") function bitLen(): (go.GoInt);
    /**
        Compare returns an integer comparing two IPs.
        The result will be 0 if ip == ip2, -1 if ip < ip2, and +1 if ip > ip2.
        The definition of "less than" is the same as the [Addr.Less] method.
    **/
    @:native("Compare") function compare(ip2: go.net.netip.Addr): (go.GoInt);
    /**
        Is4 reports whether ip is an IPv4 address.
        
        It returns false for IPv4-mapped IPv6 addresses. See [Addr.Unmap].
    **/
    @:native("Is4") function is4(): (Bool);
    /**
        Is4In6 reports whether ip is an "IPv4-mapped IPv6 address"
        as defined by RFC 4291.
        That is, it reports whether ip is in ::ffff:0:0/96.
    **/
    @:native("Is4In6") function is4In6(): (Bool);
    /**
        Is6 reports whether ip is an IPv6 address, including IPv4-mapped
        IPv6 addresses.
    **/
    @:native("Is6") function is6(): (Bool);
    /**
        IsGlobalUnicast reports whether ip is a global unicast address.
        
        It returns true for IPv6 addresses which fall outside of the current
        IANA-allocated 2000::/3 global unicast space, with the exception of the
        link-local address space. It also returns true even if ip is in the IPv4
        private address space or IPv6 unique local address space.
        It returns false for the zero [Addr].
        
        For reference, see RFC 1122, RFC 4291, and RFC 4632.
    **/
    @:native("IsGlobalUnicast") function isGlobalUnicast(): (Bool);
    /**
        IsInterfaceLocalMulticast reports whether ip is an IPv6 interface-local
        multicast address.
    **/
    @:native("IsInterfaceLocalMulticast") function isInterfaceLocalMulticast(): (Bool);
    /**
        IsLinkLocalMulticast reports whether ip is a link-local multicast address.
    **/
    @:native("IsLinkLocalMulticast") function isLinkLocalMulticast(): (Bool);
    /**
        IsLinkLocalUnicast reports whether ip is a link-local unicast address.
    **/
    @:native("IsLinkLocalUnicast") function isLinkLocalUnicast(): (Bool);
    /**
        IsLoopback reports whether ip is a loopback address.
    **/
    @:native("IsLoopback") function isLoopback(): (Bool);
    /**
        IsMulticast reports whether ip is a multicast address.
    **/
    @:native("IsMulticast") function isMulticast(): (Bool);
    /**
        IsPrivate reports whether ip is a private address, according to RFC 1918
        (IPv4 addresses) and RFC 4193 (IPv6 addresses). That is, it reports whether
        ip is in 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, or fc00::/7. This is the
        same as [net.IP.IsPrivate].
    **/
    @:native("IsPrivate") function isPrivate(): (Bool);
    /**
        IsUnspecified reports whether ip is an unspecified address, either the IPv4
        address "0.0.0.0" or the IPv6 address "::".
        
        Note that the zero [Addr] is not an unspecified address.
    **/
    @:native("IsUnspecified") function isUnspecified(): (Bool);
    /**
        IsValid reports whether the [Addr] is an initialized address (not the zero Addr).
        
        Note that "0.0.0.0" and "::" are both valid values.
    **/
    @:native("IsValid") function isValid(): (Bool);
    /**
        Less reports whether ip sorts before ip2.
        IP addresses sort first by length, then their address.
        IPv6 addresses with zones sort just after the same address without a zone.
    **/
    @:native("Less") function less(ip2: go.net.netip.Addr): (Bool);
    /**
        MarshalBinary implements the [encoding.BinaryMarshaler] interface.
        It returns a zero-length slice for the zero [Addr],
        the 4-byte form for an IPv4 address,
        and the 16-byte form with zone appended for an IPv6 address.
    **/
    @:native("MarshalBinary") function marshalBinary(): (go.Result<go.Slice<go.Byte>>);
    /**
        MarshalText implements the [encoding.TextMarshaler] interface,
        The encoding is the same as returned by [Addr.String], with one exception:
        If ip is the zero [Addr], the encoding is the empty string.
    **/
    @:native("MarshalText") function marshalText(): (go.Result<go.Slice<go.Byte>>);
    /**
        Next returns the address following ip.
        If there is none, it returns the zero [Addr].
    **/
    @:native("Next") function next(): (go.net.netip.Addr);
    /**
        Prefix keeps only the top b bits of IP, producing a Prefix
        of the specified length.
        If ip is a zero [Addr], Prefix always returns a zero Prefix and a nil error.
        Otherwise, if bits is less than zero or greater than ip.BitLen(),
        Prefix returns an error.
    **/
    @:native("Prefix") function prefix(b: go.GoInt): (go.Result<go.net.netip.Prefix>);
    /**
        Prev returns the IP before ip.
        If there is none, it returns the IP zero value.
    **/
    @:native("Prev") function prev(): (go.net.netip.Addr);
    /**
        String returns the string form of the IP address ip.
        It returns one of 5 forms:
        
          - "invalid IP", if ip is the zero [Addr]
          - IPv4 dotted decimal ("192.0.2.1")
          - IPv6 ("2001:db8::1")
          - "::ffff:1.2.3.4" (if [Addr.Is4In6])
          - IPv6 with zone ("fe80:db8::1%eth0")
        
        Note that unlike package net's IP.String method,
        IPv4-mapped IPv6 addresses format with a "::ffff:"
        prefix before the dotted quad.
    **/
    @:native("String") function string(): (String);
    /**
        StringExpanded is like [Addr.String] but IPv6 addresses are expanded with leading
        zeroes and no "::" compression. For example, "2001:db8::1" becomes
        "2001:0db8:0000:0000:0000:0000:0000:0001".
    **/
    @:native("StringExpanded") function stringExpanded(): (String);
    /**
        Unmap returns ip with any IPv4-mapped IPv6 address prefix removed.
        
        That is, if ip is an IPv6 address wrapping an IPv4 address, it
        returns the wrapped IPv4 address. Otherwise it returns ip unmodified.
    **/
    @:native("Unmap") function unmap(): (go.net.netip.Addr);
    /**
        UnmarshalBinary implements the [encoding.BinaryUnmarshaler] interface.
        It expects data in the form generated by MarshalBinary.
    **/
    @:native("UnmarshalBinary") function unmarshalBinary(b: go.Slice<go.Byte>): (go.Error);
    /**
        UnmarshalText implements the encoding.TextUnmarshaler interface.
        The IP address is expected in a form accepted by [ParseAddr].
        
        If text is empty, UnmarshalText sets *ip to the zero [Addr] and
        returns no error.
    **/
    @:native("UnmarshalText") function unmarshalText(text: go.Slice<go.Byte>): (go.Error);
    /**
        WithZone returns an IP that's the same as ip but with the provided
        zone. If zone is empty, the zone is removed. If ip is an IPv4
        address, WithZone is a no-op and returns ip unchanged.
    **/
    @:native("WithZone") function withZone(zone: String): (go.net.netip.Addr);
    /**
        Zone returns ip's IPv6 scoped addressing zone, if any.
    **/
    @:native("Zone") function zone(): (String);

}