package go.net.netip;

/**
    AddrPort is an IP and a port number.
**/
@:structInit
@:go.Type({ name: "AddrPort", instanceName: "netip.AddrPort", imports: ["net/netip"] })
extern class AddrPort {

    /**
        Addr returns p's IP address.
    **/
    @:native("Addr") function addr(): (go.net.netip.Addr);
    /**
        AppendBinary implements the [encoding.BinaryAppendler] interface.
        It returns [Addr.AppendBinary] with an additional two bytes appended
        containing the port in little-endian.
    **/
    @:native("AppendBinary") function appendBinary(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        AppendText implements the [encoding.TextAppender] interface. The
        encoding is the same as returned by [AddrPort.AppendTo].
    **/
    @:native("AppendText") function appendText(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        AppendTo appends a text encoding of p,
        as generated by [AddrPort.MarshalText],
        to b and returns the extended buffer.
    **/
    @:native("AppendTo") function appendTo(b: go.Slice<go.Byte>): (go.Slice<go.Byte>);
    /**
        Compare returns an integer comparing two AddrPorts.
        The result will be 0 if p == p2, -1 if p < p2, and +1 if p > p2.
        AddrPorts sort first by IP address, then port.
    **/
    @:native("Compare") function compare(p2: go.net.netip.AddrPort): (go.GoInt);
    /**
        IsValid reports whether p.Addr() is valid.
        All ports are valid, including zero.
    **/
    @:native("IsValid") function isValid(): (Bool);
    /**
        MarshalBinary implements the [encoding.BinaryMarshaler] interface.
        It returns [Addr.MarshalBinary] with an additional two bytes appended
        containing the port in little-endian.
    **/
    @:native("MarshalBinary") function marshalBinary(): (go.Result<go.Slice<go.Byte>>);
    /**
        MarshalText implements the [encoding.TextMarshaler] interface. The
        encoding is the same as returned by [AddrPort.String], with one exception: if
        p.Addr() is the zero [Addr], the encoding is the empty string.
    **/
    @:native("MarshalText") function marshalText(): (go.Result<go.Slice<go.Byte>>);
    /**
        Port returns p's port.
    **/
    @:native("Port") function port(): (go.UInt16);
    @:native("String") function string(): (String);
    /**
        UnmarshalBinary implements the [encoding.BinaryUnmarshaler] interface.
        It expects data in the form generated by [AddrPort.MarshalBinary].
    **/
    @:native("UnmarshalBinary") function unmarshalBinary(b: go.Slice<go.Byte>): (go.Error);
    /**
        UnmarshalText implements the encoding.TextUnmarshaler
        interface. The [AddrPort] is expected in a form
        generated by [AddrPort.MarshalText] or accepted by [ParseAddrPort].
    **/
    @:native("UnmarshalText") function unmarshalText(text: go.Slice<go.Byte>): (go.Error);

}