package go.net.netip;

/**
    Prefix is an IP address prefix (CIDR) representing an IP network.
    
    The first [Prefix.Bits]() of [Addr]() are specified. The remaining bits match any address.
    The range of Bits() is [0,32] for IPv4 or [0,128] for IPv6.
**/
@:structInit
@:go.Type({ name: "Prefix", instanceName: "netip.Prefix", imports: ["net/netip"] })
extern class Prefix {

    /**
        Addr returns p's IP address.
    **/
    @:native("Addr") function addr(): (go.net.netip.Addr);
    /**
        AppendBinary implements the [encoding.AppendMarshaler] interface.
        It returns [Addr.AppendBinary] with an additional byte appended
        containing the prefix bits.
    **/
    @:native("AppendBinary") function appendBinary(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        AppendText implements the [encoding.TextAppender] interface.
        It is the same as [Prefix.AppendTo].
    **/
    @:native("AppendText") function appendText(b: go.Slice<go.Byte>): (go.Result<go.Slice<go.Byte>>);
    /**
        AppendTo appends a text encoding of p,
        as generated by [Prefix.MarshalText],
        to b and returns the extended buffer.
    **/
    @:native("AppendTo") function appendTo(b: go.Slice<go.Byte>): (go.Slice<go.Byte>);
    /**
        Bits returns p's prefix length.
        
        It reports -1 if invalid.
    **/
    @:native("Bits") function bits(): (go.GoInt);
    /**
        Compare returns an integer comparing two prefixes.
        The result will be 0 if p == p2, -1 if p < p2, and +1 if p > p2.
        Prefixes sort first by validity (invalid before valid), then
        address family (IPv4 before IPv6), then masked prefix address, then
        prefix length, then unmasked address.
    **/
    @:native("Compare") function compare(p2: go.net.netip.Prefix): (go.GoInt);
    /**
        Contains reports whether the network p includes ip.
        
        An IPv4 address will not match an IPv6 prefix.
        An IPv4-mapped IPv6 address will not match an IPv4 prefix.
        A zero-value IP will not match any prefix.
        If ip has an IPv6 zone, Contains returns false,
        because Prefixes strip zones.
    **/
    @:native("Contains") function contains(ip: go.net.netip.Addr): (Bool);
    /**
        IsSingleIP reports whether p contains exactly one IP.
    **/
    @:native("IsSingleIP") function isSingleIP(): (Bool);
    /**
        IsValid reports whether p.Bits() has a valid range for p.Addr().
        If p.Addr() is the zero [Addr], IsValid returns false.
        Note that if p is the zero [Prefix], then p.IsValid() == false.
    **/
    @:native("IsValid") function isValid(): (Bool);
    /**
        MarshalBinary implements the [encoding.BinaryMarshaler] interface.
        It returns [Addr.MarshalBinary] with an additional byte appended
        containing the prefix bits.
    **/
    @:native("MarshalBinary") function marshalBinary(): (go.Result<go.Slice<go.Byte>>);
    /**
        MarshalText implements the [encoding.TextMarshaler] interface,
        The encoding is the same as returned by [Prefix.String], with one exception:
        If p is the zero value, the encoding is the empty string.
    **/
    @:native("MarshalText") function marshalText(): (go.Result<go.Slice<go.Byte>>);
    /**
        Masked returns p in its canonical form, with all but the high
        p.Bits() bits of p.Addr() masked off.
        
        If p is zero or otherwise invalid, Masked returns the zero [Prefix].
    **/
    @:native("Masked") function masked(): (go.net.netip.Prefix);
    /**
        Overlaps reports whether p and o contain any IP addresses in common.
        
        If p and o are of different address families or either have a zero
        IP, it reports false. Like the Contains method, a prefix with an
        IPv4-mapped IPv6 address is still treated as an IPv6 mask.
    **/
    @:native("Overlaps") function overlaps(o: go.net.netip.Prefix): (Bool);
    /**
        String returns the CIDR notation of p: "<ip>/<bits>".
    **/
    @:native("String") function string(): (String);
    /**
        UnmarshalBinary implements the [encoding.BinaryUnmarshaler] interface.
        It expects data in the form generated by [Prefix.MarshalBinary].
    **/
    @:native("UnmarshalBinary") function unmarshalBinary(b: go.Slice<go.Byte>): (go.Error);
    /**
        UnmarshalText implements the encoding.TextUnmarshaler interface.
        The IP address is expected in a form accepted by [ParsePrefix]
        or generated by [Prefix.MarshalText].
    **/
    @:native("UnmarshalText") function unmarshalText(text: go.Slice<go.Byte>): (go.Error);

}