name: build

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        go-version: ['oldstable', 'stable']
        haxe-version: [latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # setup repo
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      # setup go
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      # setup haxe
      - uses: krdlab/setup-haxe@v2.0.2
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Haxe version
        run: haxe --version
      # cache restores
      - uses: actions/cache/restore@v4
        id: setup-cache
        with:
          path: |
            output/bootstrap
          key: ${{ github.sha }}-os-${{ matrix.os }}-build-${{ env.cache-name }}
      # haxelib setup
      - name: Setup hx2go dev
        run: haxelib dev hx2go .
      - name: Install utest
        run: haxelib git utest https://github.com/haxe-utest/utest
      - name: Run bootstrap
        run: haxe Bootstrap.hxml
      - name: Run isolated test
        run: cd tests/isolated && haxe build.hxml
      - name: Run testbed
        run: haxe Testbed.hxml
      - name: Run tests
        run: haxe Tests.hxml
      - name: Extern tests
        run: cd hx2go-extern && git pull && haxe Testbed.hxml
      # cache saves
      - name: cache save
        id: cache-setup
        uses: actions/cache/save@v4
        env:
          cache-name: cache-setup
        if: always()
        with:
          path: |
            output/bootstrap
          key: ${{ github.sha }}-${{ matrix.os }}-build-${{ env.cache-name }}