name: build

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: latest
      - name: Haxe version
        run: haxe --version
      - uses: actions/cache/restore@v4
        id: regression-cache-restore
        with:
          path: |
            haxe/tests/unit/bin/go/main/unittests.txt
          key: ${{ github.ref_name }}-${{ matrix.os }}-regression-${{ github.run_id }}
          restore-keys: |
            ${{ github.ref_name }}-${{ matrix.os }}-regression-
      - name: Setup hx2go dev
        run: haxelib dev hx2go .
      - name: Install utest
        run: haxelib git utest https://github.com/haxe-utest/utest
      - name: Run bootstrap
        run: haxe Bootstrap.hxml
      - name: Run isolated test
        run: cd tests/isolated && haxe build.hxml
      - name: Run testbed
        run: haxe Testbed.hxml
      - name: Run tests baseline
        run: haxe Tests-each.hxml --interp
      - name: Run tests
        run: haxe Tests.hxml
      - name: Extern tests
        run: cd hx2go-extern && haxe Testbed.hxml
      - uses: actions/checkout@v6
        with:
          repository: pxshadow/haxe
          ref: go-target
          path: haxe
      - name: Run haxe unit tests
        run: haxe scripts/haxeunit.hxml
      - name: Save regression cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            haxe/tests/unit/bin/go/main/unittests.txt
          key: ${{ github.ref_name }}-${{ matrix.os }}-regression-${{ github.run_id }}
